### ISSUE TITLE
提几个小建议

### ISSUE THREAD

**Issue by Darling-Lee** [Hiram-Wong/ZyPlayer#100]
1.允许多播放窗口，而不是每次点击一个视频都退出正在看的变为新点击的；
2.在播放页面显示其他源的同节目，当播放的节目源不可用时，可以快速从播放页选择其他源进行播放；
3.请把软件名称改为项目名称ZyPlayer而不是一串小写的zyplayer，看起来超级别扭；

**Comment by Hiram-Wong** [comment]
1.不会改，爱优腾都是这么设计，而且太多窗口占用资源多
2.可以考虑，但实现复杂，每个源都检索可能会阻塞
3.不会改，历史遗留原因，更新会出问题改仓库名，该软件名不通操作系统会显示不一样

**Comment by Hiram-Wong** [comment]
2 多源功能不给予实现，多数据查询数据库没有这么好的性能，多个源可能上千条数据过滤
