### ISSUE TITLE
3.210导入失败

### ISSUE THREAD

**Issue by jingkanyunqi** [Hiram-Wong/ZyPlayer#102]
软件接口请求 一键配置地址失败
远端接口 请求地址失败
本地导入成功1秒 
刷新没有变化 

使用界面提供的地址  https://zy.hiram.top/config.json]
[https://zy.hiram.top/easyconfig.json

**Comment by Hiram-Wong** [comment]
提供报错截图

**Comment by jingkanyunqi** [comment]
软件接口和远端都不行，别人给的本地导入也不行。显示导入成功1秒刷新，还是空白
&nbsp;


◇尘埃灬
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月21日(星期六) 中午11:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Hiram-Wong/ZyPlayer] 3.210导入失败 (Issue #102)






提供报错截图

-
直接回复此邮件，在GitHub上查看，或取消订阅.
您收到此消息是因为您创建了该线程。消息ID:<希拉姆·王/ ZyPlayer /发行/ 102 / ***@***.***与&gt;.

**Comment by Hiram-Wong** [comment]
> 软件接口和远端都不行，别人给的本地导入也不行。显示导入成功1秒刷新，还是空白 &nbsp; ◇尘埃灬 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年10月21日(星期六) 中午11:25 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Hiram-Wong/ZyPlayer] 3.210导入失败 (Issue #102) 提供报错截图 - 直接回复此邮件，在GitHub上查看，或取消订阅. 您收到此消息是因为您创建了该线程。消息ID:<希拉姆·王/ ZyPlayer /发行/ 102 / ***@***.***与&gt;.

先重置软件，再重新导入，试试

**Comment by cooper1x** [comment]
我的是导入成功提示，但实际没有导入进去。
<img width="1000" alt="image" src="https://github.com/Hiram-Wong/ZyPlayer/assets/9080789/87b30726-5a8c-4546-9992-79f611e62780">
<img width="1000" alt="image" src="https://github.com/Hiram-Wong/ZyPlayer/assets/9080789/8a39ef01-3d13-4d1c-abda-b8bbfbd60541">
<img width="1000" alt="image" src="https://github.com/Hiram-Wong/ZyPlayer/assets/9080789/95ceddb1-02f9-47a8-9340-18f968451b0e">
