### ISSUE TITLE
怎么添加内置源呢？

### ISSUE THREAD

**Issue by earduyun** [Hiram-Wong/ZyPlayer#106]

**Comment by Hiram-Wong** [comment]
看 3.2.10 的 realse 有说明

**Comment by earduyun** [comment]
感谢大佬回复，我是想把源写进程序里，然后安装完直接就能用

**Comment by Hiram-Wong** [comment]
> 感谢大佬回复，我是想把源写进程序里，然后安装完直接就能用

这个你需要二开，判断agreementMask为 false 时，调用方法对应的数据
