### ISSUE TITLE
3.2.10 组内搜索和全站搜索不能搜索出来

### ISSUE THREAD

**Issue by mlwrx1978** [Hiram-Wong/ZyPlayer#108]
源使用的是在下载页公布的一键导入
在本站可以搜索出来的影视 设置成全站搜索或者组内搜索 就找不到了 
弱弱的问下 设置搜索下的 站点 豆瓣 夸克 百度 这几个应该怎么设置
依次试了一样的问题

**Comment by hiredsir** [comment]
我也发现这个问题
开始还以为是自己编辑有错误，后来发现原因了。
  （测试多次，当搜索至其中某条资源时 
    该条资源中没有被搜索的相关的电影节目时，
    它就会停止搜索，不会往下再搜了）
假如：
   你有10条资源站，当设置《本站搜索》时，10条源都是正常，且能够搜索
  （当然被搜索的电影或节目 在此站内没有被收录的 除外）。
比如，
   搜索电影《赌神4》，
   第1、2、3、4条源有《赌神4》，也能正常搜索出来，
   第5条源没有《赌神4》，
   第6、7、8、9、10条源有《赌神4》、也能正常搜索出来，
这时，
   若设置成《组内搜索》或《全站搜索》，（1-10源同一组）再搜索《赌神4》，
结果
   第1、2、3、4条源，正常被搜索出来，
   因为第5源没有这部电影，？？？它就会在此处停止搜索？？？
   导致第6、7、8、9、10条源，原本有《赌神4》却没有被搜索，
同理，
   若第1条源，没有《厨神》，而第23456789都有《厨神》，
   这种情况搜索，会因为第1条源中没有《厨神》，它就会结束搜索，
   此时就会显示“什么也没有搜索到”

希望作者能看到，下一个版本修复这个问题

**Comment by Hiram-Wong** [comment]
最近没有时间处理，有空看下。工作都难保了

**Comment by Hiram-Wong** [comment]
> 我也发现这个问题 开始还以为是自己编辑有错误，后来发现原因了。 （测试多次，当搜索至其中某条资源时 该条资源中没有被搜索的相关的电影节目时， 它就会停止搜索，不会往下再搜了） 假如： 你有10条资源站，当设置《本站搜索》时，10条源都是正常，且能够搜索 （当然被搜索的电影或节目 在此站内没有被收录的 除外）。 比如， 搜索电影《赌神4》， 第1、2、3、4条源有《赌神4》，也能正常搜索出来， 第5条源没有《赌神4》， 第6、7、8、9、10条源有《赌神4》、也能正常搜索出来， 这时， 若设置成《组内搜索》或《全站搜索》，（1-10源同一组）再搜索《赌神4》， 结果 第1、2、3、4条源，正常被搜索出来， 因为第5源没有这部电影，？？？它就会在此处停止搜索？？？ 导致第6、7、8、9、10条源，原本有《赌神4》却没有被搜索， 同理， 若第1条源，没有《厨神》，而第23456789都有《厨神》， 这种情况搜索，会因为第1条源中没有《厨神》，它就会结束搜索， 此时就会显示“什么也没有搜索到”
> 
> 希望作者能看到，下一个版本修复这个问题

已排查到问题，下个版本修复
