### ISSUE TITLE
为什么输入任何影视源都不显示？总是显示网络请求失败

### ISSUE THREAD

**Issue by wwb521** [Hiram-Wong/ZyPlayer#109]
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/58287307/c64420b3-2c8f-4ee6-b302-b89695a12e20)

**Comment by wwb521** [comment]
https://cyuan.netlify.app/ 这个里面的源能用么？

**Comment by Hiram-Wong** [comment]
查看 realse 最新版本里面说明
