### ISSUE TITLE
咋不能播放18+的源呢？？

### ISSUE THREAD

**Issue by 13174771** [Hiram-Wong/ZyPlayer#11]
18+的源咋不能列表显示了额？？？

**Comment by Hiram-Wong** [comment]
有源链接吗，我看看

**Comment by love41417137** [comment]
> 有源链接吗，我看看

链接在此 https://raw.iqiq.io/Hunlongyu/ZY-Player-Resources/main/Sites/20220713.json
  3.2版本不能聚合搜索  搜索显示的还是第一个资源里面的

**Comment by Hiram-Wong** [comment]
> > 有源链接吗，我看看
> 
> 
> 
> 链接在此 https://raw.iqiq.io/Hunlongyu/ZY-Player-Resources/main/Sites/20220713.json
> 
>   3.2版本不能聚合搜索  搜索显示的还是第一个资源里面的  

最新版本已支持 xml，看readme 格式导入

**Comment by 13174771** [comment]
https://raw.githubusercontent.com/13174771/ZY-Player-Resources/main/20230529.json
老大给看看这个怎么不能显示，帮忙修改下，谢谢！！！

**Comment by 13174771** [comment]
<img width="702" alt="171129" src="https://github.com/Hiram-Wong/ZyPlayer/assets/116151320/01e3f40c-883c-467e-94b0-3e8db78026cd">

就显示的是这样的~！

**Comment by Hiram-Wong** [comment]
> <img alt="171129" width="702" src="https://user-images.githubusercontent.com/116151320/241694895-01e3f40c-883c-467e-94b0-3e8db78026cd.png">
> 就显示的是这样的~！

注意参数 注意参数

**Comment by 13174771** [comment]
{
    "id": 49
    "key": "putaozy",
    "name": "葡萄资源",
    "api": "https://caiji.putaozy.net/inc/api.php",
    "type": 0,
    "search": 1,
    "playUrl": "",
    "group": "18+",
    "isActive": true,
    "status": true,
  },


这样修改了也不对呢？？？问题出在哪里啊？？？

**Comment by 13174771** [comment]
OK已经搞定了，谢谢！
