### ISSUE TITLE
窗口自由缩放

### ISSUE THREAD

**Issue by Sck89Yr** [Hiram-Wong/ZyPlayer#112]
我喜欢边玩游戏的变追剧，游戏窗口化的时候，播放器缩放到一定大小的时候就不能继续缩放了，用画中画的时候缩放窗口会保持比例，能不能调整一下可以自由缩放？

**Comment by Hiram-Wong** [comment]
不行，播放器改变大小布局有问题，目前已经调整到最小不会破坏整体效果了
