### ISSUE TITLE
增加软件主体界面记住上一次关闭前调整的自定义大小的功能

### ISSUE THREAD

**Issue by Clorasun** [Hiram-Wong/ZyPlayer#113]
软件主界面
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/92291796/7ac17cd3-97f2-4475-beae-4b5160e79b91)
在我的显示器上是这样观感有点差,希望可以支持窗口记忆上一次调整的尺寸
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/92291796/f378ff5b-c366-4e3f-bbcc-545905c9f5d6)

**Comment by Hiram-Wong** [comment]
新版本增加 v3.3.1
