### ISSUE TITLE
V3.3.0（通用版本）在win7打不开

### ISSUE THREAD

**Issue by hiredsir** [Hiram-Wong/ZyPlayer#114]
zyplayer-win-3.3.0.exe（通用版本） 在win7系统上提示
【无法定位程序输入点 DiscardVirtualMemory于动态链接库KERNEL32.dll上】
本想自行解决这个问题，折腾了半天，最后查到百度上说这个Kernel32.dll最低受支持要win8
请问一下，除了升级系统，或用回zyplayer-win-3.2.10.exe版本，还有什么办法吗？
谢谢

**Comment by Hiram-Wong** [comment]
3.3.0不支持win7，需要自己打包
