### ISSUE TITLE
我下载完之后双击程序没有反应

### ISSUE THREAD

**Issue by Teika714** [Hiram-Wong/ZyPlayer#115]
下载完文件安装完之后，桌面上双击zyplayer没有反应是咋回事呀，打不开，哭了

**Comment by Hiram-Wong** [comment]
什么操作系统

**Comment by xiamo008** [comment]
我也是 安装好了， 没反应 重启电脑也不行，我是Windows 10 企业版 LTSC

**Comment by Mubai-meng** [comment]
版本下错了吧

**Comment by xiamo008** [comment]
exe的 几个版本我全部都下了

**Comment by Hiram-Wong** [comment]
> exe的 几个版本我全部都下了

进程有启动吗

**Comment by xiamo008** [comment]
> > exe的 几个版本我全部都下了
> 
> 进程有启动吗

没有，点击了就没反应，那怕用管理员方式也不行

**Comment by Hiram-Wong** [comment]
> > > exe的 几个版本我全部都下了
> > 
> > 
> > 进程有启动吗
> 
> 没有，点击了就没反应，那怕用管理员方式也不行

方便远程看下吗，发邮件到 admin@catni.cn

**Comment by yws112358** [comment]
检查下杀软（尤其windows defender） 会因为 攻击面减少 禁止explorer启动该exe程序  
加入排除文件夹即可
