### ISSUE TITLE
可以兼容tvbox的源吗？

### ISSUE THREAD

**Issue by xiangyi83010997** [Hiram-Wong/ZyPlayer#117]
很多tvbox的现成源有很多大佬维护，如果可以兼容的话就不愁没有视频源了

**Comment by suiye007** [comment]
我自己也是写TVBox源的，这个写源的教程也没有，也不通用，有点浪费啊，现在只能配一些采集站点的，但分类又不精确

**Comment by Hiram-Wong** [comment]
> 我自己也是写TVBox源的，这个写源的教程也没有，也不通用，有点浪费啊，现在只能配一些采集站点的，但分类又不精确

技术架构不同，无法实现 tvbox 那套，分类本来就是直接api获取的 cms 的，和软件无关。再者已经支持道长 drpy 即 js 源够用

**Comment by suiye007** [comment]
> > 我自己也是写TVBox源的，这个写源的教程也没有，也不通用，有点浪费啊，现在只能配一些采集站点的，但分类又不精确
> 
> 技术架构不同，无法实现 tvbox 那套，分类本来就是直接api获取的 cms 的，和软件无关。再者已经支持道长 drpy 即 js 源够用

好的，非常感谢回复，支持道长的就行，我先写个试一试
