### ISSUE TITLE
更新之后有BUG，有两个关闭，最大化，最小化，按钮

### ISSUE THREAD

**Issue by FurcasX** [Hiram-Wong/ZyPlayer#118]
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/119423577/590d25e0-73f3-4216-85be-a7e19adf0149)

**Comment by Hiram-Wong** [comment]
已知问题，少写了一部分代码

**Comment by Hiram-Wong** [comment]
已修复 v3.3.1
