### ISSUE TITLE
老哥是否考虑换个LOGO，这色调看着挺扎眼😀

### ISSUE THREAD

**Issue by fourbeauty** [Hiram-Wong/ZyPlayer#123]
#
[归档.zip](https://github.com/Hiram-Wong/ZyPlayer/files/13689996/default.zip)
看哥的 zy  是 24 的创意挺好，就是色调看着有点晃眼，建议设计得朴实一些更好

**Comment by Hiram-Wong** [comment]
感觉怪怪的，你可以在帮忙设计设计，可以的话可加联系方式

**Comment by lowy** [comment]
图标确实看着不是那么清晰

**Comment by Hiram-Wong** [comment]
> 图标确实看着不是那么清晰
不会设计工具，你们可以设计，合适的可以替换

**Comment by lowy** [comment]
我也不会弄 就简单用了个反色 因为桌面是深色主题 所以背景用了黑色 个人比较倾向于紫色那款 因为比较梦幻 贴合影视类造梦的感觉 
![zyplayerls](https://github.com/Hiram-Wong/ZyPlayer/assets/6565177/1334dbe5-1d3a-4651-ac95-6abf8d64d6f6)
![zyplayerzs](https://github.com/Hiram-Wong/ZyPlayer/assets/6565177/8cde4eec-be4d-4366-ad91-ba4e4c5547a2)

**Comment by Hiram-Wong** [comment]
> 我也不会弄 就简单用了个反色 因为桌面是深色主题 所以背景用了黑色 个人比较倾向于紫色那款 因为比较梦幻 贴合影视类造梦的感觉 ![zyplayerls](https://private-user-images.githubusercontent.com/6565177/292079971-1334dbe5-1d3a-4651-ac95-6abf8d64d6f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDAyMDEsIm5iZiI6MTcwMzEzOTkwMSwicGF0aCI6Ii82NTY1MTc3LzI5MjA3OTk3MS0xMzM0ZGJlNS0xZDNhLTQ2NTEtYWM5NS02YWJmOGQ2NGQ2ZjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjFUMDYyNTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDcxOWMyYmU5ZTVkYjVkNWE4YjFjNDU2OGM5MTQ1MzlhMTg4MDY0YjdjZjcwMjJlNTIxMTI1OTdiMTZkMDFhYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.P5o9cZ2Gw6JsU0XvAjCMrZFjNEGdd0Tlm5b3hs6QT34) ![zyplayerzs](https://private-user-images.githubusercontent.com/6565177/292080014-8cde4eec-be4d-4366-ad91-ba4e4c5547a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDAyMDEsIm5iZiI6MTcwMzEzOTkwMSwicGF0aCI6Ii82NTY1MTc3LzI5MjA4MDAxNC04Y2RlNGVlYy1iZTRkLTQzNjYtYWQ5MS1iYTRlNGM1NTQ3YTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjFUMDYyNTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTVlY2IxNDMzOGIyZWY5MDcyYzkxMzZiMDU5OWJmOGI1MzM1ZDQ1YmI4YzFlNDllNTgyMmIyYWM0ZjdkNWNjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WHTjgh8QeH9NeMLFbC5npJZUzEOq6BYAuoZbLzMjKMQ)

亮瞎我的眼

**Comment by fourbeauty** [comment]
> 感觉怪怪的，你可以在帮忙设计设计，可以的话可加联系方式

可以呀，一起帮忙更新下 我的WX ： ixishi

**Comment by fourbeauty** [comment]
![Uploading ZYPLAYER2.png…]()

**Comment by fourbeauty** [comment]
![ZYPLAYER2](https://github.com/Hiram-Wong/ZyPlayer/assets/118109192/40d667e3-fd12-482b-9602-b76cd41147b5)

**Comment by Hiram-Wong** [comment]
> ![ZYPLAYER2](https://private-user-images.githubusercontent.com/118109192/300262076-40d667e3-fd12-482b-9602-b76cd41147b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NDg1MjcsIm5iZiI6MTcwNjQ0ODIyNywicGF0aCI6Ii8xMTgxMDkxOTIvMzAwMjYyMDc2LTQwZDY2N2UzLWZkMTItNDgyYi05NjAyLWI3NmNkNDExNDdiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQxMzIzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDY1Nzg4NzFiNjBiZWYxNjJlODNiMWQ1YThiM2RhNmM4OGRiZDMwY2M2MDFjY2FkMDNkOGRmMmM1OTI5YjYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pfysL_YnBjK0y8HCtWdQ1LSQsb6o7euwuo968zv5EfY)

我希望在 zy 两个字母之上改造出具有影音的象形

**Comment by fourbeauty** [comment]
> > ![ZYPLAYER2](https://private-user-images.githubusercontent.com/118109192/300262076-40d667e3-fd12-482b-9602-b76cd41147b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NDg1MjcsIm5iZiI6MTcwNjQ0ODIyNywicGF0aCI6Ii8xMTgxMDkxOTIvMzAwMjYyMDc2LTQwZDY2N2UzLWZkMTItNDgyYi05NjAyLWI3NmNkNDExNDdiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQxMzIzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDY1Nzg4NzFiNjBiZWYxNjJlODNiMWQ1YThiM2RhNmM4OGRiZDMwY2M2MDFjY2FkMDNkOGRmMmM1OTI5YjYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pfysL_YnBjK0y8HCtWdQ1LSQsb6o7euwuo968zv5EfY)
> 
> 我希望在 zy 两个字母之上改造出具有影音的象形

![ZYPLAYER3](https://github.com/Hiram-Wong/ZyPlayer/assets/118109192/58982eaf-5d3a-4cd6-9838-08e4bc1aef8b)

**Comment by fourbeauty** [comment]
![ZYPLAYER4](https://github.com/Hiram-Wong/ZyPlayer/assets/118109192/f619fcae-db9a-4152-9a6a-8147bd3d2947)

**Comment by fourbeauty** [comment]
![zyplayer12](https://github.com/Hiram-Wong/ZyPlayer/assets/118109192/db794db3-465c-4f78-8727-f542650d7f5e)
![zyplayer12](https://github.com/Hiram-Wong/ZyPlayer/assets/118109192/7eefbebb-4ec3-4f1c-b57a-a18c4f7b36c4)

**Comment by fourbeauty** [comment]
![zyplayer12](https://github.com/Hiram-Wong/ZyPlayer/assets/118109192/18a663fa-fc07-4780-bd54-f9328487b31c)
![zyplayer11](https://github.com/Hiram-Wong/ZyPlayer/assets/118109192/fdc37d61-2125-4106-9b14-05f6d9e41911)

**Comment by fourbeauty** [comment]
![zyplayer13](https://github.com/Hiram-Wong/ZyPlayer/assets/118109192/df0de29a-9e42-49b7-a017-ee6db6cfbe05

**Comment by fourbeauty** [comment]
![zyplayer13](https://github.com/Hiram-Wong/ZyPlayer/assets/118109192/8930c364-f3f1-4386-ab00-eafb7f6416fc)
![zyplayer10](https://github.com/Hiram-Wong/ZyPlayer/assets/118109192/31d03422-8c64-4541-8653-3a5735927c05)

**Comment by fourbeauty** [comment]
按大佬的原LOGO色彩做了几稿，回家过年了……明年再见了

**Comment by fourbeauty** [comment]
大佬已上传了几版稿子，看看有没有合用的，回家过年了，有需要的话明年再处理了
________________________________
发件人: Hiram·Wong ***@***.***>
发送时间: 2024年1月28日 13:25
收件人: Hiram-Wong/ZyPlayer ***@***.***>
抄送: fourbeauty ***@***.***>; Author ***@***.***>
主题: Re: [Hiram-Wong/ZyPlayer] 老哥是否考虑换个LOGO，这色调看着挺扎眼😀 (Issue #123)


[ZYPLAYER2]<https://private-user-images.githubusercontent.com/118109192/300262076-40d667e3-fd12-482b-9602-b76cd41147b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NDg1MjcsIm5iZiI6MTcwNjQ0ODIyNywicGF0aCI6Ii8xMTgxMDkxOTIvMzAwMjYyMDc2LTQwZDY2N2UzLWZkMTItNDgyYi05NjAyLWI3NmNkNDExNDdiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQxMzIzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDY1Nzg4NzFiNjBiZWYxNjJlODNiMWQ1YThiM2RhNmM4OGRiZDMwY2M2MDFjY2FkMDNkOGRmMmM1OTI5YjYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pfysL_YnBjK0y8HCtWdQ1LSQsb6o7euwuo968zv5EfY>

我希望在 zy 两个字母之上改造出具有影音的象形
