### ISSUE TITLE
看到作者有设计配色的意愿，借花献佛，推荐用人工智能生成，阿里的通义万相现在还免费试用

### ISSUE THREAD

**Issue by arlingus** [Hiram-Wong/ZyPlayer#124]
看到作者有设计配色的意愿，借花献佛，推荐用人工智能生成，阿里的通义万相现在还免费试用，这里上传两个样本，作者可以试试，输入文字描述需求，就可以生成各种各样的图片，包括LOGO、配色等，其实不需要找专业人员设计了。

<img width="704" alt="配色表" src="https://github.com/Hiram-Wong/ZyPlayer/assets/144001516/a417b1e1-3059-43fa-bf67-e008e798ee5d">
<img width="464" alt="LOGO" src="https://github.com/Hiram-Wong/ZyPlayer/assets/144001516/66d2866c-40e9-442b-b6a8-7561e4d8a270">
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/144001516/fc7fdb86-ac65-4a64-81af-837c1a4c5a13)
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/144001516/ac53c7a1-2b4a-4d3f-9c5b-39cacce337ab)

**Comment by Hiram-Wong** [comment]
这个风格不适合做图标，同时还需要避免非原创风险
