### ISSUE TITLE
【需要与bug】搜索结果不能显示不全

### ISSUE THREAD

**Issue by seraphjerry** [Hiram-Wong/ZyPlayer#125]
当搜索关键词结果不止一页时，只能显示当前网站搜索首页的内容，剩下的内容无法搜索出来。
不知是否可以实现？

**Comment by Hiram-Wong** [comment]
之前几个版本修复过，不存在该问题

**Comment by seraphjerry** [comment]
> 之前几个版本修复过，不存在该问题

还有个问题，不知道是接口问题还是软件bug。

譬如：https://zmwjp.com/api?ac=videolist，这个网站接口可以在软件中显示内容，但是无法播放，也无法进行搜索。
还有几个网站接口也是相同的问题。

以上接口在tvbox（影视仓）可以搜索内容。但网站搜索结果有跟多页时，只能显示首页的内容。

**Comment by Hiram-Wong** [comment]
> > 之前几个版本修复过，不存在该问题
> 
> 还有个问题，不知道是接口问题还是软件bug。
> 
> 譬如：[https://zmwjp.com/api?ac=videolist，这个网站接口可以在软件中显示内容，但是无法播放，也无法进行搜索。](https://zmwjp.com/api?ac=videolist%EF%BC%8C%E8%BF%99%E4%B8%AA%E7%BD%91%E7%AB%99%E6%8E%A5%E5%8F%A3%E5%8F%AF%E4%BB%A5%E5%9C%A8%E8%BD%AF%E4%BB%B6%E4%B8%AD%E6%98%BE%E7%A4%BA%E5%86%85%E5%AE%B9%EF%BC%8C%E4%BD%86%E6%98%AF%E6%97%A0%E6%B3%95%E6%92%AD%E6%94%BE%EF%BC%8C%E4%B9%9F%E6%97%A0%E6%B3%95%E8%BF%9B%E8%A1%8C%E6%90%9C%E7%B4%A2%E3%80%82) 还有几个网站接口也是相同的问题。
> 
> 以上接口在tvbox（影视仓）可以搜索内容。但网站搜索结果有跟多页时，只能显示首页的内容。

能抓个包给我吗，看下正确的搜索路径是多少
