### ISSUE TITLE
有个不是很大众的小建议

### ISSUE THREAD

**Issue by allonmymind** [Hiram-Wong/ZyPlayer#128]
能否把release文件名中的版本号取消掉，有时候没有梯子打不开release页面，不方便下载，如果文件名不含版本号，我可以使用代理前缀+https://githubxxxx/release/latest/xxx固定链接输入到浏览器进行下载

**Comment by Hiram-Wong** [comment]
版本号不就是为了区分

**Comment by allonmymind** [comment]
> 版本号不就是为了区分

![image](https://github.com/Hiram-Wong/ZyPlayer/assets/18719713/3af3c26f-2707-406f-83fe-b6e9795b0769)
私以为，release标题就有版本号，而且app也支持在线更新，文件名里面如果能改取消版本号的话，我就能用简单的wget命令定时拉取最新的安装包到nas里面了，docker-compose这个项目好像就是这样的，哈哈

**Comment by Hiram-Wong** [comment]
写个 shell脚本，获取 lastest 版本号然后拼接后wget

**Comment by allonmymind** [comment]
> 写个 shell脚本，获取 lastest 版本号然后拼接后wget

#!/bin/bash

repo_owner="Hiram-Wong"  # 替换为仓库所有者的用户名或组织名
repo_name="ZyPlayer"  # 替换为仓库的名称

# 使用 GitHub API 获取 release 列表
api_url="https://api.github.com/repos/$repo_owner/$repo_name/releases"
response=$(curl -s $api_url)

# 提取最新版本号
latest_version=$(echo $response | jq -r '.[0].tag_name')

# 输出最新版本号
echo "Latest version of $repo_owner/$repo_name is: $latest_version"

感谢，确实这样就解决了
