### ISSUE TITLE
请问有木有安卓平台或者IOS平台的吗

### ISSUE THREAD

**Issue by CxiaoyuN** [Hiram-Wong/ZyPlayer#13]
请问有木有安卓平台或者IOS平台的吗

**Comment by Hiram-Wong** [comment]
安卓推荐 tvbox 类软件
 ios 推荐 le 或者keer

**Comment by jahem** [comment]
> 请问有木有安卓平台或者IOS平台的吗

安卓可以試一下這個https://github.com/qallen028/ZyPlayer

**Comment by CxiaoyuN** [comment]
ios有推荐吗？大佬们，┭┮﹏┭┮

**Comment by CxiaoyuN** [comment]
> keer

le 或者keer是啥软件，有链接吗
