### ISSUE TITLE
大佬咱们后续能支持比如饭太硬这种接口类型吗？

### ISSUE THREAD

**Issue by cooldcc** [Hiram-Wong/ZyPlayer#130]
http://饭xx.top/tv  类似这种聚合的

**Comment by Ucopyrightable** [comment]
支持提议

**Comment by npljy** [comment]
大佬已回复过不会支持tvbox

**Comment by murazi** [comment]
> 大佬已回复过不会支持tvbox

![image](https://github.com/Hiram-Wong/ZyPlayer/assets/4424520/1f9f51d4-f6f6-46dc-bf3c-682cbdf20b57)
我看不是支持吗？不过没用过

**Comment by dqzboy** [comment]
> > 大佬已回复过不会支持tvbox
> 
> ![image](https://private-user-images.githubusercontent.com/4424520/305138932-1f9f51d4-f6f6-46dc-bf3c-682cbdf20b57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMjU5OTYsIm5iZiI6MTcwODIyNTY5NiwicGF0aCI6Ii80NDI0NTIwLzMwNTEzODkzMi0xZjlmNTFkNC1mNmY2LTQ2ZGMtYmYzYy02ODJjYmRmMjBiNTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMThUMDMwODE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmI4NWM1MDRkZjYxM2NmYzI0Mjg4NDVlMDRmODNkZjE1NmVmMjgxZmJhOGFmMWFjMmJkZjI5ZTc5MmUyZGNmZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tbOW_WJffeTGagwCiFpGE01cROszpgA6c1hvtmt_9YE) 我看不是支持吗？不过没用过

饭太硬这种的接口格式不支持，所以不能直接拿来用

**Comment by wenjialu82** [comment]
> > 大佬已回复过不会支持tvbox
> 
> ![image](https://private-user-images.githubusercontent.com/4424520/305138932-1f9f51d4-f6f6-46dc-bf3c-682cbdf20b57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzY1ODcsIm5iZiI6MTcwODQzNjI4NywicGF0aCI6Ii80NDI0NTIwLzMwNTEzODkzMi0xZjlmNTFkNC1mNmY2LTQ2ZGMtYmYzYy02ODJjYmRmMjBiNTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjBUMTMzODA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmFhYjFmNjIzZDJjZGVjMDNiMmY3NjUxOGU5ZmRkNDZmNzMwN2FjNWViNDMzNjE3ODRiODcwMTIzMTI1N2M3MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ExoRMji5viY-NlTAqAojc4hY27lqI1VTZZ8uuEolM0I) 我看不是支持吗？不过没用过

我安装好没有“一键配置”呢？

**Comment by smalllh** [comment]
tvbox不是主流的接口吗，为啥后续不支持

**Comment by Hiram-Wong** [comment]
统一回复：技术架构和方向不同
