### ISSUE TITLE
自建的xiaoya tvbox如何添加到zyplayer？

### ISSUE THREAD

**Issue by happymy** [Hiram-Wong/ZyPlayer#132]
tvbox的配置地址：http://xxx:4567/sub/0
如何添加到zyplayer里？

[SUB0.zip](https://github.com/Hiram-Wong/ZyPlayer/files/14045896/SUB0.zip)

**Comment by BroMouse** [comment]
http://xxx:4567/vod1

**Comment by happymy** [comment]
不能播放，云盘没有文件传输过来。。。

**Comment by happymy** [comment]
可能是之前刮削导致云盘暂时黑名单，今早恢复了。都能播放了。

**Comment by happymy** [comment]
> 老哥是填的哪个位置？我试了`数据管理 - 一键配置\配置导入`都不行 我的tvbox订阅`http://192.168.123.2:4567/vod1`填进去用不了一片空白，但是用作者的能正常显示#48

刮削会导致云盘黑名单，已经改用猫影视了。
