### ISSUE TITLE
道长的DRPY如何添加的

### ISSUE THREAD

**Issue by sysh8888** [Hiram-Wong/ZyPlayer#138]
道长的DRPY如何添加的呀，我类型选DRPY【js0】，在接口处填入JS地址https://cdn.jsdelivr.net/gh/hjdhnx/dr_py@main/js/cokemv.js，但却无法使用。麻烦有教程吗

**Comment by Hiram-Wong** [comment]
方法一：基础配置->数据管理->一键配置->选择 drpy  http://127.0.0.1:5705/config/1?ver=0&mode=0
[![pFwg2Ps.png](https://s11.ax1x.com/2024/02/29/pFwg2Ps.png)](https://imgse.com/i/pFwg2Ps)
方法二：影视配置-添加->类型选择 drpy[js0]   http://192.168.215.2:5705/vod?pwd=dzyyds&rule=567电影院
[![pFwgyVg.png](https://s11.ax1x.com/2024/02/29/pFwgyVg.png)](https://imgse.com/i/pFwgyVg)

不是 js 文件
