### ISSUE TITLE
为什么有些资源站搜索不到内容？比如索尼资源

### ISSUE THREAD

**Issue by arlingus** [Hiram-Wong/ZyPlayer#139]
为什么有些资源站搜索不到内容？比如索尼资源，   "name": "索尼",      "api": "https://suoniapi.com/api.php/provide/vod/",使用zyplayer搜索的时候什么影片都搜索不到，config.json里类似的搜索不到内容的资源站很多，大概有一半

**Comment by Hiram-Wong** [comment]
搜索配置怎么配置的

**Comment by gib888** [comment]
索尼资源有内容，但播放不了

**Comment by arlingus** [comment]
> 搜索配置怎么配置的
是只添加视频源的时候的聚合搜索么？这个选的本站或者聚合都搜索不到内容的，大佬能就索尼这个资源试试给个解决方法么？

**Comment by Hiram-Wong** [comment]
> > 搜索配置怎么配置的
> > 是只添加视频源的时候的聚合搜索么？这个选的本站或者聚合都搜索不到内容的，大佬能就索尼这个资源试试给个解决方法么？

索尼资源 搜索站点返回不对，建议设置关闭

**Comment by arlingus** [comment]
好吧，谢谢大佬测试，不过这个资源还是挺有实力的，有些应用可以搜索，不知道为什么
