### ISSUE TITLE
新版关于新增的系统托盘和界面

### ISSUE THREAD

**Issue by xiamu2002** [Hiram-Wong/ZyPlayer#143]
<img width="467" alt="iShot_2024-03-02_11 37 50" src="https://github.com/Hiram-Wong/ZyPlayer/assets/51028479/fe6c5157-f194-4c55-8bd3-1f6877bdea14">

一，这个托盘Mac下一直是黑色的，深色壁纸下很不协调，不知道哪里改，也没法关啊。感觉要么跟随系统，要么支持选择，能自定义就更好点。点上去无任何功能的话，加了好像暂时也没什么意义，还增加了烦恼。

<img width="310" alt="iShot_2024-03-02_12 03 34" src="https://github.com/Hiram-Wong/ZyPlayer/assets/51028479/779127a8-f588-482e-a738-92bbdd869a70">

二，右侧设置选项没有了，但是这个卡片提示移动到影视选项下一直展示，希望能有隐藏选项或移到别处。

**Comment by Hiram-Wong** [comment]
1.目前做不了，系统不提供壁纸的颜色是什么状态
2.点击前往配置就是到设置页面

**Comment by lowy** [comment]
应该是弄反了 等下一版吧

**Comment by fourbeauty** [comment]
> 1.目前做不了，系统不提供壁纸的颜色是什么状态 2.点击前往配置就是到设置页面
希望能完善，强迫症会受不了，UI 优化空间很大，有些文字、图标间距不是很合理，操作起来有点杂乱

**Comment by Hiram-Wong** [comment]
> 应该是弄反了 等下一版吧

已找到macos方案

**Comment by Hiram-Wong** [comment]
> > 1.目前做不了，系统不提供壁纸的颜色是什么状态 2.点击前往配置就是到设置页面
> > 希望能完善，强迫症会有些受不了，UI有优化空间，有些文字、图标间距也不是很合理，操作起来有点杂乱，前往配置可以考虑去除，与HIPy更配可以放到设置中去，

毕竟不是做 ui 的，就是随便玩玩
