### ISSUE TITLE
自动测速

### ISSUE THREAD

**Issue by templklklk** [Hiram-Wong/ZyPlayer#144]
搜索结果太多，普遍比较卡，得一个个对比速度。
希望搜索能自动测速，自动检测并显示各个资源的速度，方便找到最快的那个（自动高亮）。

类似[我只想好好观影](https://greasyfork.org/en/scripts/459540-%E6%88%91%E5%8F%AA%E6%83%B3%E5%A5%BD%E5%A5%BD%E8%A7%82%E5%BD%B1)这个用户脚本的功能：
![309518391-7db4d9a9-7e00-4baf-b4b1-ec5d4665d17a](https://github.com/Hiram-Wong/ZyPlayer/assets/59308951/a5ee7880-9e38-429a-ba15-16eb0aa223ef)

**Comment by Hiram-Wong** [comment]
没必要，你觉得慢的你直接关掉某个资源的搜索就行，他这种也是要先经过一系列的数据判断产生的测速本身就不准，每个都先探测一遍搜索前会等待很长时间
