### ISSUE TITLE
请问大佬，设置VLC ，环境变量也配置好了，视频播放时点击视频播放没反应怎么回事？

### ISSUE THREAD

**Issue by gib888** [Hiram-Wong/ZyPlayer#148]

**Comment by Hiram-Wong** [comment]
有图吗

**Comment by kingsey** [comment]
> 有图吗

同VLC，能调用商店的VLC UWP那个半残版，但只是打开VLC并不播放内容。而全功能的桌面版并不能设置为VLC链接的默认打开应用（微软背锅），设置环境变量也无法调用。

**Comment by Hiram-Wong** [comment]
试一下这个https://www.cnblogs.com/wangrui38/p/13748640.html

**Comment by gib888** [comment]
谢谢大佬回复，选择播放后好像连接不上VLC，打不开VLC播放器.

**Comment by Hiram-Wong** [comment]
> 谢谢大佬回复，选择播放后好像连接不上VLC，打不开VLC播放器.

更新最新版本，直接指定路径
