### ISSUE TITLE
希望开发者可以新增支持TVBO接口

### ISSUE THREAD

**Issue by itscolor** [Hiram-Wong/ZyPlayer#15]
如题，希望开发者可以新增支持TVBOX接口，这样接口方便，画质更好~
不支持大佬是否有适配计划？

**Comment by itscolor** [comment]
感谢开发者，最新版本支持了.

**Comment by gegewuwuwu** [comment]
> 感谢开发者，最新版本支持了.

确实支持了，但是找的json url添加不了，不知道大佬添加那种类型的？

**Comment by fuxin-mail** [comment]
> 如题，希望开发者可以新增支持TVBOX接口，这样接口方便，画质更好~ 不支持大佬是否有适配计划？

TVBO接口怎么添加？也是和一键配置一样操作吗？

**Comment by itscolor** [comment]
> 



> > 如题，希望开发者可以新增支持TVBOX接口，这样接口方便，画质更好~ 不支持大佬是否有适配计划？
> 
> TVBO接口怎么添加？也是和一键配置一样操作吗？

就在一键配置那个地方，有TVBOX的接口选择，不过目前没有完全兼容，我还是用的普通接口，就在公众号搜的

**Comment by fuxin-mail** [comment]
> > 
> 
> > > 如题，希望开发者可以新增支持TVBOX接口，这样接口方便，画质更好~ 不支持大佬是否有适配计划？
> > 
> > 
> > TVBO接口怎么添加？ 也是和一键配置一样操作吗？
> 
> 就在一键配置那个地方，有TVBOX的接口选择，不过目前没有完全兼容，我还是用的普通接口，就在公众号搜的

就是drpy接口吗？

**Comment by itscolor** [comment]
> > > 
> > 
> > 
> > > > 如题，希望开发者可以新增支持TVBOX接口，这样接口方便，画质更好~ 不支持大佬是否有适配计划？
> > > 
> > > 
> > > TVBO接口怎么添加？ 也是和一键配置一样操作吗？
> > 
> > 
> > 就在一键配置那个地方，有TVBOX的接口选择，不过目前没有完全兼容，我还是用的普通接口，就在公众号搜的
> 
> 就是drpy接口吗？

那你不是最新版本，最新版本，有三个接口，最后一个就是TVBOX接口。

**Comment by fuxin-mail** [comment]
> > > > 
> > > 
> > > 
> > > > > 如题，希望开发者可以新增支持TVBOX接口，这样接口方便，画质更好~ 不支持大佬是否有适配计划？
> > > > 
> > > > 
> > > > TVBO接口怎么添加？ 也是和一键配置一样操作吗？
> > > 
> > > 
> > > 就在一键配置那个地方，有TVBOX的接口选择，不过目前没有完全兼容，我还是用的普通接口，就在公众号搜的
> > 
> > 
> > 就是drpy接口吗？
> 
> 那你不是最新版本，最新版本，有三个接口，最后一个就是TVBOX接口。

太好了！能支持TVBOX源就多了

**Comment by Hiram-Wong** [comment]
> > > > > 
> > > > 
> > > > 
> > > > > > 如题，希望开发者可以新增支持TVBOX接口，这样接口方便，画质更好~ 不支持大佬是否有适配计划？
> > > > > 
> > > > > 
> > > > > TVBO接口怎么添加？ 也是和一键配置一样操作吗？
> > > > 
> > > > 
> > > > 就在一键配置那个地方，有TVBOX的接口选择，不过目前没有完全兼容，我还是用的普通接口，就在公众号搜的
> > > 
> > > 
> > > 就是drpy接口吗？
> > 
> > 
> > 那你不是最新版本，最新版本，有三个接口，最后一个就是TVBOX接口。
> 
> 太好了！能支持TVBOX源就多了

只支持部分，对于 tvbox type3 爬虫的不支持

**Comment by 2805671972** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > > > 如题，希望开发者可以新增支持TVBOX接口，这样接口方便，画质更好~ 不支持大佬是否有适配计划？
> > > > > > 
> > > > > > 
> > > > > > TVBO接口怎么添加？ 也是和一键配置一样操作吗？
> > > > > 
> > > > > 
> > > > > 就在一键配置那个地方，有TVBOX的接口选择，不过目前没有完全兼容，我还是用的普通接口，就在公众号搜的
> > > > 
> > > > 
> > > > 就是drpy接口吗？
> > > 
> > > 
> > > 那你不是最新版本，最新版本，有三个接口，最后一个就是TVBOX接口。
> > 
> > 
> > 太好了！能支持TVBOX源就多了
> 
> 只支持部分，对于 tvbox type3 爬虫的不支持

那还是可惜啊，现在来说TVBOX的源，又稳定又方便，未来要是能多支持点就好了
