### ISSUE TITLE
【建议】鼠标双击逻辑能否修改或提供设置选项呢？

### ISSUE THREAD

**Issue by ashurajo** [Hiram-Wong/ZyPlayer#150]
目前是双击暂停/播放
能否修改为单击鼠标左键暂停/播放
双击改为全屏/还原窗口大小
😀

**Comment by Hiram-Wong** [comment]
西瓜播放器默认就是单击鼠标左键暂停/播放，双击播放器没提供快捷操作

**Comment by ashurajo** [comment]
> 西瓜播放器默认就是单击鼠标左键暂停/播放，双击播放器没提供快捷操作

刚去搜索了一下文档，里面提到这个：

closeVideoDblclick
类型: Boolean
默认值: false
pc端: 是否关闭双击播放器进入全屏的能力
mobile端: 是否关闭双击切换暂停/播放的能力

不知道对大佬有参考价值吗。

https://h5player.bytedance.com/config/#closevideodblclick
