### ISSUE TITLE
3.3.2老板键每次打开都需要重新设置一次才生效

### ISSUE THREAD

**Issue by itxxq** [Hiram-Wong/ZyPlayer#153]
1、3.3.2老板键每次打开都需要重新设置一次才生效
2、搜索历史回车或者点击某个历史记录后，应该关闭搜索历史弹框。

**Comment by Hiram-Wong** [comment]
1.第一个问题已知，代码已经修复，等下个版本

**Comment by Hiram-Wong** [comment]
2.下个版本优化 交互方面问题
