### ISSUE TITLE
我想在本地做一些修改测试，好提供更多的建议，但是打包出错

### ISSUE THREAD

**Issue by Darling-Lee** [Hiram-Wong/ZyPlayer#154]
我做好修改后，按照redme上的方法，运行yarn electron:build:linux出错：yarn run v1.22.21
error Command "electron:build:linux" not found.

运行yarn build:linux也出错：yarn run v1.22.21
$ npm run build && electron-builder --linux

> zyplayer@3.3.3 build
> electron-vite build

sh: 行 1: electron-vite: 未找到命令

是什么问题吗？请大大赐教

**Comment by Hiram-Wong** [comment]
yarn build:linux

**Comment by Hiram-Wong** [comment]
你那个是老版本命令yarn electron:build:linux，3.3.2 (即现在 main 仓库)之后都是yarn build:linux
readme 忘记改了，感谢提示

**Comment by Darling-Lee** [comment]
> 你那个是老版本命令yarn electron:build:linux，3.3.2 (即现在 main 仓库)之后都是yarn build:linux readme 忘记改了，感谢提示

是的，这个我也运行过，会提示错误：
yarn run v1.22.21
$ npm run build && electron-builder --linux
zyplayer@3.3.3 build
electron-vite build

sh: 行 1: electron-vite: 未找到命令

这是什么依赖没有解决吗？

**Comment by Hiram-Wong** [comment]
先运行yarn

**Comment by Hiram-Wong** [comment]
> 先运行yarn

运行yarn add electron-vite -D

**Comment by Darling-Lee** [comment]
> > 先运行yarn
> 
> 运行yarn add electron-vite -D

好了，谢谢大佬
