### ISSUE TITLE
能支持影视猫的nodejs接口吗?

### ISSUE THREAD

**Issue by mymine** [Hiram-Wong/ZyPlayer#155]
能支持影视猫的nodejs接口吗?cms采集和appv2都没什么好接口。
(https://github.com/catvod/CatVodOpen)

**Comment by Hiram-Wong** [comment]
最近在适配 drpy 的 js 接口

**Comment by Hiram-Wong** [comment]
> 能支持影视猫的nodejs接口吗?cms采集和appv2都没什么好接口。 (https://github.com/catvod/CatVodOpen)

我看他这个只能在打包就给写死了，不能自定义。这样子我会有法律风险

**Comment by mymine** [comment]
> > 能支持影视猫的nodejs接口吗?cms采集和appv2都没什么好接口。 (https://github.com/catvod/CatVodOpen)
> 
> 我看他这个只能在打包就给写死了，不能自定义。这样子我会有法律风险

老猫影视就是因为法律风险才停更的。吃过一次亏了后新猫放出来这个接口应该没问题吧！毕竟吃过一次亏了，不可能再吃第二次亏吧。

**Comment by Hiram-Wong** [comment]
> > > 能支持影视猫的nodejs接口吗?cms采集和appv2都没什么好接口。 (https://github.com/catvod/CatVodOpen)
> > 
> > 
> > 我看他这个只能在打包就给写死了，不能自定义。这样子我会有法律风险
> 
> 老猫影视就是因为法律风险才停更的。吃过一次亏了后新猫放出来这个接口只有接口示例，没有编译，要编译后才能运行。没有具体的内容。毕竟吃过一次亏了，不可能再吃第二次亏吧。应该没问题

需要编译的情况下大大增加了使用者的成本，对小白不合适

**Comment by mymine** [comment]
> > > > 能支持影视猫的nodejs接口吗?cms采集和appv2都没什么好接口。 (https://github.com/catvod/CatVodOpen)
> > > 
> > > 
> > > 我看他这个只能在打包就给写死了，不能自定义。这样子我会有法律风险
> > 
> > 
> > 老猫影视就是因为法律风险才停更的。吃过一次亏了后新猫放出来这个接口只有接口示例，没有编译，要编译后才能运行。没有具体的内容。毕竟吃过一次亏了，不可能再吃第二次亏吧。应该没问题
> 
> 需要编译的情况下大大增加了使用者的成本，对小白不合适

采集接口和APP接口都没有什么好源了。又没人维护源的话，也就能看看直播了。小白的话，不都是去开会员看视频吗😂

**Comment by Hiram-Wong** [comment]
catbox 数据是什么传的，有示例吗

**Comment by mymine** [comment]
> catbox 数据是什么传的，有示例吗

接口文件吗？
https://www.lanzoub.com/tp/iDUas1s7as2h
这是http://github.com/catvod/catvodopen打包好的接口文件

**Comment by Hiram-Wong** [comment]
不能实现需要本地代理的

**Comment by mymine** [comment]
> 不能实现需要本地代理的

哦，那关闭了
