### ISSUE TITLE
过刻记录问题

### ISSUE THREAD

**Issue by jie0613** [Hiram-Wong/ZyPlayer#157]
**版本:3.3.2 配置导入:[https://zy.catni.cn/config_v3.json]**

**问题:**
下图里,我**打开最后一个视频会跳到第二个视频;倒数第三个视频就打开第一个视频;**
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/163984870/2911bc02-15c2-402b-8f6e-1b631c5ab64a)

并且过刻记录与实际使用的接口不一致
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/163984870/9a4b85d4-cdc8-4ea7-a6bc-7221b1df85ce)
上图中我打开的金鹰资源,但是到了过刻里面就变成下图
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/163984870/2d95d5d5-53f9-4b42-a7fd-3014f9721b46)
也无法打开,播放器提示undefined

**总结:只要是搜索结果里面的视频打开后再去过刻里面打开,就一定是混乱的**

**Comment by jie0613** [comment]
测试发现,选择西瓜播放器就一定会出现

**Comment by jie0613** [comment]
测试发现,记录里面会直接与影视配置-资源默认设置有关, 
**过刻里面无视搜索结果选择的资源地址,直接与默认资源匹配**

**Comment by Hiram-Wong** [comment]
感谢提醒，下个版本修复
