### ISSUE TITLE
linux使用本地播放器VLC出现错误

### ISSUE THREAD

**Issue by aiyi-rain** [Hiram-Wong/ZyPlayer#160]
在Arch Linux的kde6环境下使用VLC本地播放器出现位置错误。
![Uploading 屏幕截图_20240324_160835.png…]()

**Comment by aiyi-rain** [comment]
![Uploading 屏幕截图_20240324_160835.png…]()

**Comment by aiyi-rain** [comment]
无法读取文件 vlc://http//[2409:8087:1e03:21::2]:6060/cms001/ch00000090990000001188/index.m3u8

**Comment by Hiram-Wong** [comment]
什么版本

**Comment by aiyi-rain** [comment]
用的是linux-3.32-x86-64.appimage,电脑系统是arch linux 。

**Comment by Hiram-Wong** [comment]
命令行里面执行一下 whereis vlc 这个命令和 vlc 这个命令看下有没有输出

**Comment by aiyi-rain** [comment]
有的，输出正常
vlc: /usr/bin/vlc /usr/lib/vlc /usr/include/vlc /usr/share/vlc /usr/share/man/man1/vlc.1.gz

**Comment by Hiram-Wong** [comment]
命令行下执行 vlc://http//[2409:8087:1e03:21::2]:6060/cms001/ch00000090990000001188/index.m3u8看看

**Comment by Hiram-Wong** [comment]
我边用 ipv6 测试http://[2409:8087:1e03:21::2]:6060/cms001/ch00000090990000001188/index.m3u8这个打不开，应该是失效的或者源有其他限制

**Comment by aiyi-rain** [comment]
更换其他视频也是同样情况
无法读取文件 vlc://https//cdn.wlcdn99.com:777/d6d8308d/index.m3u8

**Comment by aiyi-rain** [comment]
使用西瓜播放器可以播放

**Comment by Hiram-Wong** [comment]
这似乎看起来是 vlc 本身软件的问题，无法解决。

**Comment by aiyi-rain** [comment]
好吧😑，那就使用西瓜播放器。Sent from my iPhoneOn Mar 24, 2024, at 18:56, Hiram·Wong ***@***.***> wrote:﻿
这似乎看起来是 vlc 本身软件的问题，无法解决。
