### ISSUE TITLE
关于增设功能需求

### ISSUE THREAD

**Issue by Dsy0113** [Hiram-Wong/ZyPlayer#161]
1、能否增设可设置化视频检索内容屏蔽功能，例如：历史，武打，情感
2、能否增设视频内文字和视频广告内容屏蔽或跳过或去除机制。
3、能否增设视频源与Andirod的源共用，PC源存在失效和选择局限性。
希望博主可以看到，谢谢您的理解和支持。辛苦

**Comment by Hiram-Wong** [comment]
1.第一个可用源类别过滤
2.技术积累问题， 暂未没找到框架网络请求拦截接口
3.架构问题，不能共用

**Comment by Dsy0113** [comment]
第一个类别，我看只能在单个源上设置，如果有多个源，每个都需要设置，可否考虑在基础设置一栏内也增设一个类别过滤功能



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月26日(周二) 中午11:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hiram-Wong/ZyPlayer] 关于增设功能需求 (Issue #161)




 
1.第一个可用源类别过滤
 2.技术积累问题， 暂未没找到框架网络请求拦截接口
 3.架构问题，不能共用

**Comment by Dsy0113** [comment]
> 1.第一个可用源类别过滤2.技术积累问题,暂未没找到框架网络请求拦截接口3.架构问题,不能共用

而且第一个类别我设置了，看着没啥用。可以在基础配置里面加上一个功能，比如下面这个：

基础配置-过滤（分为：主要分类-青少年模式）
主要类别内容为页面展示可看类别
青少年模式内容为页面不显示屏蔽内容

**Comment by queand** [comment]
1.能否增加下一集的按键，要不每次跳转就会跳回小屏，需要重新全屏
2.能否增加视频下载功能，使用第三方下载软件有时无法成功下载

**Comment by Hiram-Wong** [comment]
> 1.能否增加下一集的按键，要不每次跳转就会跳回小屏，需要重新全屏 2.能否增加视频下载功能，使用第三方下载软件有时无法成功下载

第二点不行，违反法律法规。同时第三方更专业做这个都不行，那我就更不行

**Comment by Hiram-Wong** [comment]
> 1.能否增加下一集的按键，要不每次跳转就会跳回小屏，需要重新全屏 2.能否增加视频下载功能，使用第三方下载软件有时无法成功下载

第一点播放器代码重构了，最新版本已经优化

**Comment by Hiram-Wong** [comment]
> 1、能否增设可设置化视频检索内容屏蔽功能，例如：历史，武打，情感 2、能否增设视频内文字和视频广告内容屏蔽或跳过或去除机制。 3、能否增设视频源与Andirod的源共用，PC源存在失效和选择局限性。 希望博主可以看到，谢谢您的理解和支持。辛苦

第二点已经最新版本实现，仅支持部分插播广告
