### ISSUE TITLE
过刻-收藏显示问题

### ISSUE THREAD

**Issue by jie0613** [Hiram-Wong/ZyPlayer#162]
点收藏/追后
![1711499392341](https://github.com/Hiram-Wong/ZyPlayer/assets/163984870/03a3c538-220e-4e3f-b095-9a30e982492a)

这时候还是正常的，但是点了右上角的更新后

![image](https://github.com/Hiram-Wong/ZyPlayer/assets/163984870/bdded216-740a-4cad-95bc-bb7e511370f7)
 显示被删除，猜测是不是处理反馈的时候接收到无新内容就判定资源异常？

切到别的页面，然后回到收藏又变成第一张图片

**Comment by Hiram-Wong** [comment]
100%复线吗

**Comment by jie0613** [comment]
> 100%复线吗

没错，我刚刚测试的结果
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/163984870/40a28f65-333f-4540-8d9f-a25ea761d359)

**Comment by jie0613** [comment]
资源已经更新
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/163984870/7d57f6fc-da7a-4d03-970a-f465ff0ff0ef)

**Comment by Hiram-Wong** [comment]
> > 100%复线吗
> 
> 没错，我刚刚测试的结果 ![image](https://private-user-images.githubusercontent.com/163984870/317589518-40a28f65-333f-4540-8d9f-a25ea761d359.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MDU0NzUsIm5iZiI6MTcxMTYwNTE3NSwicGF0aCI6Ii8xNjM5ODQ4NzAvMzE3NTg5NTE4LTQwYTI4ZjY1LTMzM2YtNDU0MC04ZDlmLWEyNWVhNzYxZDM1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQwNTUyNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDM0ZDQyNTcxMTUxNGY2ZGZlNmUwMGEyNmFmMjBjNjczOTlmODRmNzYzNzkzOWQzYTdiYzJjM2NkZWQwMzFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bNQvr8quWRkJt6C20EZgpc8hh1eoWdkF7tqu-GmbqX8)

复现不出来，导出一份完整数据给我看下

**Comment by Hiram-Wong** [comment]
你是点刷新出现的问题，还是更新

**Comment by Hiram-Wong** [comment]
知道问题在哪里了，下个版本修复

**Comment by evileonline** [comment]
3.3.3版本，这个点击更新按钮后，仍然显示“该源应该被删除了哦”的信息。
[config.json](https://github.com/Hiram-Wong/ZyPlayer/files/14926517/config.json)
这个还是100%复现的。

**Comment by Hiram-Wong** [comment]
> 3.3.3版本，这个点击更新按钮后，仍然显示“该源应该被删除了哦”的信息。 [config.json](https://github.com/Hiram-Wong/ZyPlayer/files/14926517/config.json) 这个还是100%复现的。

https://github.com/Hiram-Wong/ZyPlayer/actions/runs/8616146989
使用这个，3.3.4 还没发布

**Comment by evileonline** [comment]
> > 3.3.3版本，这个点击更新按钮后，仍然显示“该源应该被删除了哦”的信息。 [config.json](https://github.com/Hiram-Wong/ZyPlayer/files/14926517/config.json) 这个还是100%复现的。
> 
> https://github.com/Hiram-Wong/ZyPlayer/actions/runs/8616146989 使用这个，3.3.4 还没发布

不是太会搞这个，下载后保存在文本里，改成JSON的格式，用配置一键导入，无法导入
![Snip20240410_1](https://github.com/Hiram-Wong/ZyPlayer/assets/36870868/e098170f-4a77-46d6-83d4-702ba59b7f31)

**Comment by evileonline** [comment]
![Snip20240410_3](https://github.com/Hiram-Wong/ZyPlayer/assets/36870868/0e2f90d9-5483-4f1d-bc2b-0db6db55335c)
@Hiram-Wong

**Comment by Hiram-Wong** [comment]
> ![Snip20240410_3](https://private-user-images.githubusercontent.com/36870868/321224433-0e2f90d9-5483-4f1d-bc2b-0db6db55335c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NjA3NDIsIm5iZiI6MTcxMjc2MDQ0MiwicGF0aCI6Ii8zNjg3MDg2OC8zMjEyMjQ0MzMtMGUyZjkwZDktNTQ4My00ZjFkLWJjMmItMGRiNmRiNTUzMzVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDE0NDcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmOTA2NTg1MDA4N2VkYzIzMmQxZDYzYjVmMWM0YzJmZDNiYjIxZGUyODYxNzJiMmVmMTNhZTUyM2Y4MDhlNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.snaFgZ1qFqE1DsWRFCAozfDN_3ymmzcPOxuxRPDIn1k) @Hiram-Wong

查看#48

**Comment by jie0613** [comment]
> > 3.3.3版本，这个点击更新按钮后，仍然显示“该源应该被删除了哦”的信息。 [config.json](https://github.com/Hiram-Wong/ZyPlayer/files/14926517/config.json) 这个还是100%复现的。
> 
> https://github.com/Hiram-Wong/ZyPlayer/actions/runs/8616146989 使用这个，3.3.4 还没发布

安装链接里的版本后
出现新问题,点了右上角"更新"按钮后显示正确
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/163984870/32e32544-a9f4-4ece-9248-b2e6c24bae9c)

但是重新打开收藏页面后就变成历史数据了,如下图
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/163984870/38cbde95-46db-40b4-8be7-d4776638e308)


更新信息无法保存???

**Comment by jie0613** [comment]
第二个问题
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/163984870/7c73e755-6108-4d34-8203-5ffac6892510)
上图出现的操作是:播放页面取消"在追",接着点"追"就会出现"该源应该被删除了哦" 
无法点击播放,提示"请求资源站失败,请检查网络"

**Comment by Hiram-Wong** [comment]
> > > 3.3.3版本，这个点击更新按钮后，仍然显示“该源应该被删除了哦”的信息。 [config.json](https://github.com/Hiram-Wong/ZyPlayer/files/14926517/config.json) 这个还是100%复现的。
> > 
> > 
> > https://github.com/Hiram-Wong/ZyPlayer/actions/runs/8616146989 使用这个，3.3.4 还没发布
> 
> 安装链接里的版本后 出现新问题,点了右上角"更新"按钮后显示正确 ![image](https://private-user-images.githubusercontent.com/163984870/321552144-32e32544-a9f4-4ece-9248-b2e6c24bae9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4Mjc3NDMsIm5iZiI6MTcxMjgyNzQ0MywicGF0aCI6Ii8xNjM5ODQ4NzAvMzIxNTUyMTQ0LTMyZTMyNTQ0LWE5ZjQtNGVjZS05MjQ4LWIyZTZjMjRiYWU5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQwOTI0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzlkN2RlMGNlNzdmNTY5NWIyZjJmNDYzODA5YTg4OTQ2NDBmNzFkNjNkNTAwOWVlMjljN2VmYTU0ZmM2NGNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Rq5gdDDh8UtMRMlxi2UEUcqB5nmeRRMVDUYg0v71gis)
> 
> 但是重新打开收藏页面后就变成历史数据了,如下图 ![image](https://private-user-images.githubusercontent.com/163984870/321552379-38cbde95-46db-40b4-8be7-d4776638e308.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4Mjc3NDMsIm5iZiI6MTcxMjgyNzQ0MywicGF0aCI6Ii8xNjM5ODQ4NzAvMzIxNTUyMzc5LTM4Y2JkZTk1LTQ2ZGItNDBiNC04YmU3LWQ0Nzc2NjM4ZTMwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQwOTI0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWY5MjRjMzQ3NzI4ZmE5OTk4NzBiYTkyYzJmMmE0NmU4ZjdmNmViOWUzMWQxMmUwNTA2ZDYwOTk2NTk1MDQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eZki37ZgFMCwnHEth92LVssWZ8CVxD237O-CDqkw0-A)
> 
> 更新信息无法保存???

设计如此，只有通过播放才会更新数据。不然这里直接更新了数据再次更新就不会在显示了，导致你实际没看到这集数

**Comment by Hiram-Wong** [comment]
> 上图出现的操作是:播放页面取消"在追",接着点"追"就会出现"该源应该被删除了哦"
> 无法点击播放,提示"请求资源站失败,请检查网络"

不存在该问题，取消"在追"只是删除这条数据，接着点"追"重新添加这条数据应该是在最下面

**Comment by jie0613** [comment]
> > > > 3.3.3版本，这个点击更新按钮后，仍然显示“该源应该被删除了哦”的信息。 [config.json](https://github.com/Hiram-Wong/ZyPlayer/files/14926517/config.json) 这个还是100%复现的。
> > > 
> > > 
> > > https://github.com/Hiram-Wong/ZyPlayer/actions/runs/8616146989 使用这个，3.3.4 还没发布
> > 
> > 
> > 安装链接里的版本后 出现新问题,点了右上角"更新"按钮后显示正确 ![image](https://private-user-images.githubusercontent.com/163984870/321552144-32e32544-a9f4-4ece-9248-b2e6c24bae9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4Mjc3NDMsIm5iZiI6MTcxMjgyNzQ0MywicGF0aCI6Ii8xNjM5ODQ4NzAvMzIxNTUyMTQ0LTMyZTMyNTQ0LWE5ZjQtNGVjZS05MjQ4LWIyZTZjMjRiYWU5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQwOTI0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzlkN2RlMGNlNzdmNTY5NWIyZjJmNDYzODA5YTg4OTQ2NDBmNzFkNjNkNTAwOWVlMjljN2VmYTU0ZmM2NGNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Rq5gdDDh8UtMRMlxi2UEUcqB5nmeRRMVDUYg0v71gis)
> > 但是重新打开收藏页面后就变成历史数据了,如下图 ![image](https://private-user-images.githubusercontent.com/163984870/321552379-38cbde95-46db-40b4-8be7-d4776638e308.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4Mjc3NDMsIm5iZiI6MTcxMjgyNzQ0MywicGF0aCI6Ii8xNjM5ODQ4NzAvMzIxNTUyMzc5LTM4Y2JkZTk1LTQ2ZGItNDBiNC04YmU3LWQ0Nzc2NjM4ZTMwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQwOTI0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWY5MjRjMzQ3NzI4ZmE5OTk4NzBiYTkyYzJmMmE0NmU4ZjdmNmViOWUzMWQxMmUwNTA2ZDYwOTk2NTk1MDQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eZki37ZgFMCwnHEth92LVssWZ8CVxD237O-CDqkw0-A)
> > 更新信息无法保存???
> 
> 设计如此，只有通过播放才会更新数据。不然这里直接更新了数据再次更新就不会在显示了，导致你实际没看到这集数


https://github.com/Hiram-Wong/ZyPlayer/assets/163984870/fc7d6306-f8ff-4e22-9d1e-d3edcff31ea9

我也是测试软件很多个了..ZY也用了几款

**Comment by jie0613** [comment]
> > > > 3.3.3版本，这个点击更新按钮后，仍然显示“该源应该被删除了哦”的信息。 [config.json](https://github.com/Hiram-Wong/ZyPlayer/files/14926517/config.json) 这个还是100%复现的。
> > > 
> > > 
> > > https://github.com/Hiram-Wong/ZyPlayer/actions/runs/8616146989 使用这个，3.3.4 还没发布
> > 
> > 
> > 安装链接里的版本后 出现新问题,点了右上角"更新"按钮后显示正确 ![image](https://private-user-images.githubusercontent.com/163984870/321552144-32e32544-a9f4-4ece-9248-b2e6c24bae9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4Mjc3NDMsIm5iZiI6MTcxMjgyNzQ0MywicGF0aCI6Ii8xNjM5ODQ4NzAvMzIxNTUyMTQ0LTMyZTMyNTQ0LWE5ZjQtNGVjZS05MjQ4LWIyZTZjMjRiYWU5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQwOTI0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzlkN2RlMGNlNzdmNTY5NWIyZjJmNDYzODA5YTg4OTQ2NDBmNzFkNjNkNTAwOWVlMjljN2VmYTU0ZmM2NGNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Rq5gdDDh8UtMRMlxi2UEUcqB5nmeRRMVDUYg0v71gis)
> > 但是重新打开收藏页面后就变成历史数据了,如下图 ![image](https://private-user-images.githubusercontent.com/163984870/321552379-38cbde95-46db-40b4-8be7-d4776638e308.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4Mjc3NDMsIm5iZiI6MTcxMjgyNzQ0MywicGF0aCI6Ii8xNjM5ODQ4NzAvMzIxNTUyMzc5LTM4Y2JkZTk1LTQ2ZGItNDBiNC04YmU3LWQ0Nzc2NjM4ZTMwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQwOTI0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWY5MjRjMzQ3NzI4ZmE5OTk4NzBiYTkyYzJmMmE0NmU4ZjdmNmViOWUzMWQxMmUwNTA2ZDYwOTk2NTk1MDQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eZki37ZgFMCwnHEth92LVssWZ8CVxD237O-CDqkw0-A)
> > 更新信息无法保存???
> 
> 设计如此，只有通过播放才会更新数据。不然这里直接更新了数据再次更新就不会在显示了，导致你实际没看到这集数

无言,只有上录制视频

https://github.com/Hiram-Wong/ZyPlayer/assets/163984870/32030463-4b07-4013-bce6-794c6412bad2

**Comment by jie0613** [comment]
> > 上图出现的操作是:播放页面取消"在追",接着点"追"就会出现"该源应该被删除了哦"
> > 无法点击播放,提示"请求资源站失败,请检查网络"
> 
> 不存在该问题，取消"在追"只是删除这条数据，接着点"追"重新添加这条数据应该是在最下面

不存在就不存在吧,我还是上个视频证明一下

https://github.com/Hiram-Wong/ZyPlayer/assets/163984870/0ae60beb-99f2-44f6-939d-3f6d01eeeb4e

**Comment by Hiram-Wong** [comment]
> > > 上图出现的操作是:播放页面取消"在追",接着点"追"就会出现"该源应该被删除了哦"
> > > 无法点击播放,提示"请求资源站失败,请检查网络"
> > 
> > 
> > 不存在该问题，取消"在追"只是删除这条数据，接着点"追"重新添加这条数据应该是在最下面
> 
> 不存在就不存在吧,我还是上个视频证明一下
> 
>  Rec.0004.mp4

确实存在该问题 在#162讨论

**Comment by evileonline** [comment]
@Hiram-Wong 这个用action里的安装包，收藏中的视频，点击更新后，看完后，下次重新进入软件，继续点击更新，上一次看完的视频仍旧显示更新内容
![Snip20240425_1](https://github.com/Hiram-Wong/ZyPlayer/assets/36870868/42335ec1-14f4-4b04-9db7-d3a2366e38ca)
