### ISSUE TITLE
站源的添加模式能否支持订阅模式，和订阅切换

### ISSUE THREAD

**Issue by hjdhnx** [Hiram-Wong/ZyPlayer#163]
如题，我注意到现有的源添加机制是从外部导入和内部手动添加，但是不方便切换。

如果可以像tvbox一样配置个链接，只显示链接里的源和解析直播等东西，增加订阅过的链接列表可以随时切换，这个叫做订阅模式就非常方便。

**Comment by Hiram-Wong** [comment]
与当初设计相违背，暂不基于实现相关功能
