### ISSUE TITLE
关于应用窗口问题

### ISSUE THREAD

**Issue by xuchen521** [Hiram-Wong/ZyPlayer#168]
### 这个功能解决了什么问题

每次打开软件，界面都会回到初始的尺寸大小，每次都要进行拉伸改变尺寸

### 你建议的方案是什么

建议增加窗口大小更改的记忆功能，还有就是安装新版本后，收藏的全部消失了

**Comment by Hiram-Wong** [comment]
1.第一个功能已经有了，设置里开启，正常退出只会记录主窗口
2.升级日志已经说明，不再解释
