### ISSUE TITLE
这个玩意能不能对新手友好一点

### ISSUE THREAD

**Issue by linsan970809** [Hiram-Wong/ZyPlayer#169]
### 这个功能解决了什么问题

我已算是用过ZY的,大概知道怎么回事,但是当我下载安装这个3.3.3!我懵逼了,我感觉我就是下载了一个垃圾,搜索不到电影,不知道怎么配置源,我还算是懂一点这些东西的我都一头雾水.

### 你建议的方案是什么

打开能用

**Comment by hiredsir** [comment]
可我怎么感觉这是目前最强大的播放器，想看啥就能看啥呢，
你要打开能用？是指是配置好资源吗？
那也得为人家考虑一下风险，人家不收一分钱，还给你担法律风险吗，
不知怎么配置？先别说懂不懂一点，就算不懂，只要仔细看看，就能找到你想要的

**Comment by hiredsir** [comment]
若是新手，那请教问题是不是应该虚心一点，态度好一点点，不要上来就是一通贬低，

**Comment by linsan970809** [comment]
> 若是新手，那请教问题是不是应该虚心一点，态度好一点点，不要上来就是一通贬低，

我没有贬低,我在陈述事实,一把枪,没有子弹就是废铁.
V2RAY风险高不?但是配置文档很清楚.

**Comment by jizhujian** [comment]
如果你耐心点细心点，就会发现Release说明中有宝藏。学会感恩。

**Comment by Hiram-Wong** [comment]
感谢您的建议，但是该建议不会采纳，这么做直接摆明和法律对着干，目前该模式已经面临法律分析。
同时该项目没有加入任何广告和收费，包括提供的源数据也是自己的服务器，没有让大家付费，一直坚持本心简洁的原则，代码开源没有任何加密。
Readme有配置说明，Release中特殊版本发布一般都有说明配置方法，或者查看Discussions #48 
如果遇到配置相关问题可以提 issue 看到回及时解答

**Comment by Hiram-Wong** [comment]
当然大家如果能提供源，我从源服务器分发给大家一键配置，可以整合更优质的源。

**Comment by kumamiko** [comment]
适当有点门槛，其实能少很多问题……

**Comment by jie0613** [comment]
懒人版最后没多少生存下来就可见最后的结局

**Comment by Earplug** [comment]
你可以自己写一个的

**Comment by murazi** [comment]
> ### 这个功能解决了什么问题
> 我已算是用过ZY的,大概知道怎么回事,但是当我下载安装这个3.3.3!我懵逼了,我感觉我就是下载了一个垃圾,搜索不到电影,不知道怎么配置源,我还算是懂一点这些东西的我都一头雾水.
> 
> ### 你建议的方案是什么
> 打开能用

这就像，你去社区申请免费得到一个碗，然后自称是见过世面的新手，希望将碗摆在桌子上就能自动盛满你想要吃的

**Comment by Mubai-meng** [comment]
说话方法不讨好哦

**Comment by wenwenwen888** [comment]
笑死，伸手党要求还挺高
