### ISSUE TITLE
windwos 平台，看直播只有图像没有声音!

### ISSUE THREAD

**Issue by hangyubin** [Hiram-Wong/ZyPlayer#17]
windwos 平台，看直播只有图像没有声音!

**Comment by hellomyladyo** [comment]
附议

**Comment by Hiram-Wong** [comment]
1.源本身有就问题
2.播放器兼容有问题

有播放地址吗

**Comment by hellomyladyo** [comment]
https://jsd.cdn.zzko.cn/gh/ls125781003/dmtg@master/zy.json

**Comment by Hiram-Wong** [comment]
> https://jsd.cdn.zzko.cn/gh/ls125781003/dmtg@master/zy.json

那个源 能频道

**Comment by hellomyladyo** [comment]
ray直播

**Comment by hangyubin** [comment]
把源放在potplayer 播放 正常

**Comment by Hiram-Wong** [comment]
尝试更换播放器，只有图像没有声音是因为是 h265，目前只有西瓜播放器支持，兼容性可能存在问题

**Comment by aceslup** [comment]
ray直播下的用艺术播放器有音画
