### ISSUE TITLE
加油

### ISSUE THREAD

**Issue by Chinese19** [Hiram-Wong/ZyPlayer#170]
加油

**Comment by Chinese19** [comment]
![Uploading QQ截图20240409155706.png…]()

**Comment by Chinese19** [comment]
![Uploading QQ截图20240409155706.png…]()

**Comment by Chinese19** [comment]
无法定位程序输入点DiscardVirtualMemory 于动态链接库
KERNEL32.dll上。

**Comment by Hiram-Wong** [comment]
readme 已经说明了 win7 内容，不再赘述。
