### ISSUE TITLE
传入自定义播放器的播放地址不能有空格

### ISSUE THREAD

**Issue by sf467** [Hiram-Wong/ZyPlayer#171]
### zyplayer 版本

3.3.3-1

### 重现步骤

播放webdav云盘内的视频时，如果文件地址包含空格

### 期望结果

视频正常播放

### 实际结果

播放地址被截断

### 系统架构

x64

### 系统版本

archlinux

### 补充说明

或许可以给播放地址加个引号

**Comment by sf467** [comment]
> 给出具体链接

这是mpv播放器显示出的地址
![图片](https://github.com/Hiram-Wong/ZyPlayer/assets/121373973/d2db4bee-c975-4937-abd9-7ff9f608c43e)
这是实际的文件名
![图片](https://github.com/Hiram-Wong/ZyPlayer/assets/121373973/e4ba9ad2-e827-47c9-ab43-d7f84b9b85a6)
Take On Me 被截断了，mpv只得到了第一个空格之前的字符

**Comment by Hiram-Wong** [comment]
下个版本修复

**Comment by Hiram-Wong** [comment]
3.3.4新版本已更新该内容
