### ISSUE TITLE
增加当前版本显示

### ISSUE THREAD

**Issue by JinLong369** [Hiram-Wong/ZyPlayer#172]
### 这个功能解决了什么问题

咱这个软件有当前版本的显示吗？忘了之前安装的什么版本，在设置里一通找，没找到【关于】等类似的版本介绍信息。

有时可能对照发布信息看看新版本更新内容，没重要的就不更了.....

### 你建议的方案是什么

希望软件中能增加当前版本号的显示

**Comment by Hiram-Wong** [comment]
最新版本全平台都可以通过右小角托盘有个关于，mac 还可以通用状态栏有个关于

**Comment by JinLong369** [comment]
找到了，略微有些隐蔽🤣
