### ISSUE TITLE
时刻页面取消"在追",接着点"追"就会出现"该源应该被删除了哦"

### ISSUE THREAD

**Issue by Hiram-Wong** [Hiram-Wong/ZyPlayer#173]
时刻页面取消"在追",接着点"追"就会出现"该源应该被删除了哦"

https://github.com/Hiram-Wong/ZyPlayer/assets/163984870/0ae60beb-99f2-44f6-939d-3f6d01eeeb4e

_Originally posted by @jie0613 in https://github.com/Hiram-Wong/ZyPlayer/issues/162#issuecomment-2049413307_

**Comment by Hiram-Wong** [comment]
下个版本修复

**Comment by mzj632** [comment]
纯小白，不知道该怎么配置，能教一下吗

**Comment by Hiram-Wong** [comment]
> 纯小白，不知道该怎么配置，能教一下吗

查看Discussions #48

**Comment by Hiram-Wong** [comment]
> @Hiram-Wong 这个点击更新按钮，所有的视频无法及时更新，一直显示如下图系列内容；已做过[#48](https://github.com/Hiram-Wong/ZyPlayer/discussions/48)的数据更新，问题依旧存在 刚进入界面时，大主宰今日已看如下图 ![Snip20240419_2](https://private-user-images.githubusercontent.com/36870868/323944210-7147cb66-98d0-4e1a-b838-a1a215a44f54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1Mjc0NDAsIm5iZiI6MTcxMzUyNzE0MCwicGF0aCI6Ii8zNjg3MDg2OC8zMjM5NDQyMTAtNzE0N2NiNjYtOThkMC00ZTFhLWI4MzgtYTFhMjE1YTQ0ZjU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDExNDU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmYWY1YTdkYTkwMTlkNGJlYjA5YTMzOWE2ZjRiOTg0OWExYzViZjFmMTNmZTA1ZTg2MzUxYjEzYTVkMjFlOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vvsfZUcA8u3ggf2RJ_0i0DL8W1Yz9uZWBlXvyHGPg7E)
> 
> 如果点击更新后，会显示如下图新的内容 ![Snip20240419_8](https://private-user-images.githubusercontent.com/36870868/323944375-e7951135-e08c-46c8-859c-a37c684f569c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1Mjc0NDAsIm5iZiI6MTcxMzUyNzE0MCwicGF0aCI6Ii8zNjg3MDg2OC8zMjM5NDQzNzUtZTc5NTExMzUtZTA4Yy00NmM4LTg1OWMtYTM3YzY4NGY1NjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDExNDU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjZmIwMWU2MDk2OWMyYzIzYTg2ODJmNDkxYTUwYmM4ZWQzZmI2ZDZlNWEyYjQ4Y2QwMDQ4NDY2ODBiYTc4ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NtXAHhyxdnQob6tLGtuFUqRxMEiGPF4h6ipi2kggwfc)

你用的是哪里下的 realse 下的话没修复，action 修复了

**Comment by evileonline** [comment]
> > @Hiram-Wong 这个点击更新按钮，所有的视频无法及时更新，一直显示如下图系列内容；已做过[#48](https://github.com/Hiram-Wong/ZyPlayer/discussions/48)的数据更新，问题依旧存在 刚进入界面时，大主宰今日已看如下图 ![Snip20240419_2](https://private-user-images.githubusercontent.com/36870868/323944210-7147cb66-98d0-4e1a-b838-a1a215a44f54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1Mjc0NDAsIm5iZiI6MTcxMzUyNzE0MCwicGF0aCI6Ii8zNjg3MDg2OC8zMjM5NDQyMTAtNzE0N2NiNjYtOThkMC00ZTFhLWI4MzgtYTFhMjE1YTQ0ZjU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDExNDU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmYWY1YTdkYTkwMTlkNGJlYjA5YTMzOWE2ZjRiOTg0OWExYzViZjFmMTNmZTA1ZTg2MzUxYjEzYTVkMjFlOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vvsfZUcA8u3ggf2RJ_0i0DL8W1Yz9uZWBlXvyHGPg7E)
> > 如果点击更新后，会显示如下图新的内容 ![Snip20240419_8](https://private-user-images.githubusercontent.com/36870868/323944375-e7951135-e08c-46c8-859c-a37c684f569c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1Mjc0NDAsIm5iZiI6MTcxMzUyNzE0MCwicGF0aCI6Ii8zNjg3MDg2OC8zMjM5NDQzNzUtZTc5NTExMzUtZTA4Yy00NmM4LTg1OWMtYTM3YzY4NGY1NjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDExNDU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjZmIwMWU2MDk2OWMyYzIzYTg2ODJmNDkxYTUwYmM4ZWQzZmI2ZDZlNWEyYjQ4Y2QwMDQ4NDY2ODBiYTc4ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NtXAHhyxdnQob6tLGtuFUqRxMEiGPF4h6ipi2kggwfc)
> 
> 你用的是哪里下的 realse 下的话没修复，action 修复了

从github上realse下载更新的，action修复的话，请问链接从哪里下载使用？

**Comment by Hiram-Wong** [comment]
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/30908279/66de8dbd-d5c6-4362-99ec-a88cae53579e)


不会就等下个版本修复

**Comment by Hiram-Wong** [comment]
3.3.4新版本已更新该内容
