### ISSUE TITLE
双击应用打不开

### ISSUE THREAD

**Issue by Userlgz** [Hiram-Wong/ZyPlayer#175]
### zyplayer 版本

3.3.3

### 重现步骤

win10系统，双击打不开应用，有时候可以在任务管理器中看见进程

### 系统版本

win10

**Comment by Hiram-Wong** [comment]
点右下角托盘显示或者使用老板键，估计是触发隐藏

**Comment by Userlgz** [comment]
> 点右下角托盘显示或者使用老板键，估计是触发隐藏

右下角托盘没有应用，而且任务管理器里的进程会自己关掉。

**Comment by Userlgz** [comment]
兼容模式和管理员运行都不行

**Comment by Hiram-Wong** [comment]
> 兼容模式和管理员运行都不行

提供远程看下

**Comment by Userlgz** [comment]
![Uploading recording.gif…]()

**Comment by Userlgz** [comment]
老板键是什么？

**Comment by Hiram-Wong** [comment]
看不到图片，发到邮箱hiram@catni.cn

**Comment by WaterCalm** [comment]
请问这个问题最后如何解决的？我也遇到了类似问题……双击打不开，zyplayer.exe 进程出现一下然后就消失了。托盘里也没有任何图标
