### ISSUE TITLE
希望增加去切片广告的功能

### ISSUE THREAD

**Issue by yanshixin3** [Hiram-Wong/ZyPlayer#178]
### 这个功能解决了什么问题

希望增加去切片广告的功能，

### 你建议的方案是什么

希望增加去切片广告的功能，

**Comment by Hiram-Wong** [comment]
无法实现，electron 无法篡改返回数据。

只能通过一些可以去广告的接口

**Comment by yanshixin3** [comment]
不行吗？我看到TVbox上有一个去切片广告开关的所以问下，不知道他们怎么做到的

**Comment by Hiram-Wong** [comment]
能底层拦截篡改数据就可以做，electron 只能拦截不能篡改

**Comment by hjdhnx** [comment]
倒是可以单独在源里写本地代理规则实现某个源去广告

**Comment by hjdhnx** [comment]
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/49803097/8befdd6e-6348-4ddc-9ee8-af7451e42e8c)

**Comment by hjdhnx** [comment]
新版本已支持，此issue可关闭
