### ISSUE TITLE
[图标]在linux下图标显示异常 

### ISSUE THREAD

**Issue by batcast** [Hiram-Wong/ZyPlayer#179]
### zyplayer 版本

3.3.3

### 重现步骤

在麒麟系统或者ElementaryOS都显示异常，其他系统没试过。

### 期望结果

软件图标在桌面或者程序列表正常显示。

### 系统架构

X64

### 系统版本

ElementaryOS

**Comment by batcast** [comment]
> 使用的什么格式 image 还是 deb

deb，都是通过dpkg -i 本地安装。

**Comment by batcast** [comment]
> 使用的什么格式 image 还是 deb

对了，麒麟系统是arm64 deb。

**Comment by batcast** [comment]
![VirtualBox_ubuntu_26_04_2024_11_16_17](https://github.com/Hiram-Wong/ZyPlayer/assets/8342318/7dd9eeab-4f0d-446e-b496-ab1a4235e15b)
今天，我特地在ubuntu 24.04 测试了下，还是图标异常。

**Comment by Hiram-Wong** [comment]
有没有 vnc 可以远程的机器，我试试

**Comment by batcast** [comment]
> 程的机器，我试试

我不会用vnc，可以用todesk 或者qq吗？

**Comment by Hiram-Wong** [comment]
> > 程的机器，我试试
> 
> 我不会用vnc，可以用todesk 或者qq吗？

todesk可以

**Comment by batcast** [comment]
879 017 753 邀请您进行远程控制
ToDesk设备代码:879 017 753
临时密码:cvd4h5gf
点击链接直接进行远程控制：
https://wechat.todesk.com/invite-page?id=JfQ30rJPBaCG6F6eCrm2r

**Comment by Hiram-Wong** [comment]
预留问题下个版本解决

**Comment by Hiram-Wong** [comment]
3.3.4新版本已更新该内容
