### ISSUE TITLE
玩不明白哎用海洋cms这个版本就会失败

### ISSUE THREAD

**Issue by XTTGO** [Hiram-Wong/ZyPlayer#18]
如题，有没有需要注意的地方

**Comment by Hiram-Wong** [comment]
海洋 cms 接口啥样的，有地址吗看看

**Comment by fuxin-mail** [comment]
我昨天用的二开版本看了一晚上挺好，今天突然报网络请求失败，请手动刷新，刷新是左下角按钮吗？今天不能用啥情况？换了其他接口也一样呢？

**Comment by Hiram-Wong** [comment]
> 我昨天用的二开版本看了一晚上挺好，今天突然报网络请求失败，请手动刷新，刷新是左下角按钮吗？今天不能用啥情况

确认网络环境，关闭软解

**Comment by fuxin-mail** [comment]
就在刚才重新打开软件突然又可以了，好神奇，这故障还怕给开发者告状啊哈哈

**Comment by fuxin-mail** [comment]
搜索经常搜不到，这是刚才搜索提示的error:AxiosError: Network Error

**Comment by fuxin-mail** [comment]
难道是我网卡硬件有问题？

**Comment by fuxin-mail** [comment]
![屏幕截图 2023-05-17 172644](https://github.com/Hiram-Wong/ZyPlayer/assets/64723923/8045aafc-510c-445f-8f21-de4b8b93f4a0)

**Comment by fuxin-mail** [comment]
![QQ图片20230517184007](https://github.com/Hiram-Wong/ZyPlayer/assets/64723923/c9a9f18f-1310-42ca-b318-6cf6e2bbf6ad)

**Comment by Hiram-Wong** [comment]
> 搜索经常搜不到，这是刚才搜索提示的error:AxiosError: Network Error

网络请求错误，发下源看看，确保网络环境

**Comment by fuxin-mail** [comment]
https://jsd.cdn.zzko.cn/gh/ls125781003/dmtg@master/zy.json，明明是粘贴到一键配置了，也提示成功，再次打开一键配置里还是空的

**Comment by Hiram-Wong** [comment]
> [https://jsd.cdn.zzko.cn/gh/ls125781003/dmtg@master/zy.json，明明是粘贴到一键配置了，也提示成功，再次打开一键配置里还是空的](https://jsd.cdn.zzko.cn/gh/ls125781003/dmtg@master/zy.json%EF%BC%8C%E6%98%8E%E6%98%8E%E6%98%AF%E7%B2%98%E8%B4%B4%E5%88%B0%E4%B8%80%E9%94%AE%E9%85%8D%E7%BD%AE%E4%BA%86%EF%BC%8C%E4%B9%9F%E6%8F%90%E7%A4%BA%E6%88%90%E5%8A%9F%EF%BC%8C%E5%86%8D%E6%AC%A1%E6%89%93%E5%BC%80%E4%B8%80%E9%94%AE%E9%85%8D%E7%BD%AE%E9%87%8C%E8%BF%98%E6%98%AF%E7%A9%BA%E7%9A%84)

留个联系方式看看

**Comment by fuxin-mail** [comment]
fuxin-mail@qq.com

**Comment by XTTGO** [comment]
> 
这是网址 http://lzizy.net/help/#SeaCms
资源库地址：https://cj.lziapi.com/api.php/seacms/vod/at/xml/
量子m3u8地址：https://cj.lziapi.com/api.php/seacms/vod/from/lzm3u8/at/xml/
量子云地址：https://cj.lziapi.com/api.php/seacms/vod/from/liangzi/at/xml/
量子下载资源地址：https://cj.lziapi.com/api.php/providedown/vod/at/xml/
