### ISSUE TITLE
【nodejs】目前使用猫影视nodejs环境的问题

### ISSUE THREAD

**Issue by seraphjerry** [Hiram-Wong/ZyPlayer#181]
### zyplayer 版本

3.3.4

### 重现步骤

在本机用运行nodejs环境，启动猫影源后。
zyplayer可以正常显示站点内容和播放，但是自定义的分类，无法使用。

![测试](https://github.com/Hiram-Wong/ZyPlayer/assets/152712616/8c13c494-8c5c-48e6-93db-886c633eab21)
![豆瓣](https://github.com/Hiram-Wong/ZyPlayer/assets/152712616/ef4b03b4-0ad9-41eb-9fbf-f5d1c33b0faa)

### 期望结果

希望大佬越做越好！！！还需要测试人要不？

### 系统架构

x64

### 系统版本

win10

**Comment by Hiram-Wong** [comment]
提供下这个源

**Comment by seraphjerry** [comment]
> 提供下这个源

只要自定义的分类，都无法正常索引。
怎么把JS给你？QQ??

**Comment by Hiram-Wong** [comment]
> > 提供下这个源
> 
> 只要自定义的分类，都无法正常索引。 怎么把JS给你？QQ??

邮箱 hiram@catni.cn

**Comment by seraphjerry** [comment]
> 提供下这个源

这个是用猫影视nodejs中豆瓣的源。

**Comment by seraphjerry** [comment]
> > > 提供下这个源
> > 
> > 
> > 只要自定义的分类，都无法正常索引。 怎么把JS给你？QQ??
> 
> 邮箱 [hiram@catni.cn](mailto:hiram@catni.cn)

已发送

**Comment by Hiram-Wong** [comment]
这个数据结构怎么和catvod 仓库势力不一样了，我晕

**Comment by seraphjerry** [comment]
> 这个数据结构怎么和catvod 仓库势力不一样了，我晕

目前测试了几个nodejs的网站源可以正常显示，播放【play】和搜索【search】都可以，但是分类选择用不了。

现在我正研究你的新版中的写源工具。是不是和海阔视界类似？没用过，不知道有没有写好的源，给我几个，我参考一下。

我自己写过几个影视仓的json源，不知道能不能嵌套进去，还没搞明白。

**Comment by Hiram-Wong** [comment]
> > 这个数据结构怎么和catvod 仓库势力不一样了，我晕
> 
> 目前测试了几个nodejs的网站源可以正常显示，播放【play】和搜索【search】都可以，但是分类选择用不了。
> 
> 现在我正研究你的新版中的写源工具。是不是和海阔视界类似？没用过，不知道有没有写好的源，给我几个，我参考一下。
> 
> 我自己写过几个影视仓的json源，不知道能不能嵌套进去，还没搞明白。

就是 js 源，参考 drpy 或者 hipy 里面的即可

**Comment by Hiram-Wong** [comment]
再给我提供一份源

**Comment by Hiram-Wong** [comment]
> 再给我提供一份源

豆瓣这个二级，搜索，播放数据下面都没写我调半天，我晕

**Comment by seraphjerry** [comment]
你试试这个js源



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月28日(周日) 晚上10:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hiram-Wong/ZyPlayer] 【nodejs】目前使用猫影视nodejs环境的问题 (Issue #181)




  
再给我提供一份源
  
豆瓣这个二级，搜索，播放数据下面都没写我调半天，我晕

**Comment by Hiram-Wong** [comment]
> 豆瓣这个二级，搜索，播放数据下面都没写

豆瓣这个二级，搜索，播放数据下面都没写 哥们
<img width="427" alt="image" src="https://github.com/Hiram-Wong/ZyPlayer/assets/30908279/9c965dd9-3de3-48ab-ba82-7ff303775fb6">

**Comment by seraphjerry** [comment]
给你发了一个素白白的js。豆瓣本身也没视频，只是简介而已。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月29日(周一) 下午4:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hiram-Wong/ZyPlayer] 【nodejs】目前使用猫影视nodejs环境的问题 (Issue #181)




  
豆瓣这个二级，搜索，播放数据下面都没写
  
豆瓣这个二级，搜索，播放数据下面都没写 哥们
 image.png (view on web)

**Comment by Hiram-Wong** [comment]
> 给你发了一个素白白的js。豆瓣本身也没视频，只是简介而已。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年4月29日(周一) 下午4:38 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Hiram-Wong/ZyPlayer] 【nodejs】目前使用猫影视nodejs环境的问题 (Issue #181) 豆瓣这个二级，搜索，播放数据下面都没写 豆瓣这个二级，搜索，播放数据下面都没写 哥们 image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

没收到邮件

**Comment by seraphjerry** [comment]
附近是素白白影视的js，你测试一下，收到后告知~~~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hiram-Wong/ZyPlayer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月28日(星期天) 晚上10:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hiram-Wong/ZyPlayer] 【nodejs】目前使用猫影视nodejs环境的问题 (Issue #181)





  
再给我提供一份源
  
豆瓣这个二级，搜索，播放数据下面都没写我调半天，我晕

**Comment by GGreyCat** [comment]
zyplayer是怎么使用猫影视源的？

**Comment by seraphjerry** [comment]
附近人人影视js，素白白，可能失效了。我再调调。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hiram-Wong/ZyPlayer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月28日(星期天) 晚上10:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hiram-Wong/ZyPlayer] 【nodejs】目前使用猫影视nodejs环境的问题 (Issue #181)





  
再给我提供一份源
  
豆瓣这个二级，搜索，播放数据下面都没写我调半天，我晕

**Comment by seraphjerry** [comment]
> 猫影视文件放哪里 zyplayer影视配置怎么添加

需要自己搭建nodejs环境，看我上面的图
