### ISSUE TITLE
能不能增加电视直播源有效性检查和响应时间检查

### ISSUE THREAD

**Issue by kimwang1978** [Hiram-Wong/ZyPlayer#182]
### 这个功能解决了什么问题

自己整理的直播源经常失效需要更新，手工一个个点太麻烦了，能不能在画面上加个批量检测功能，然后有效的加上响应时间，这同一个台我也根据情况选择最快的台。

之前中下面这里2.8.8版本中好像看到这个功能（只有有效性检查，没有响应时间数据），不过这里好像两三年没有维护了
https://github.com/Hunlongyu/ZY-Player

### 你建议的方案是什么

添加个别检测和批量检测，失效的灰色显示，可以批量清除失效频道。
最后检测的响应时间也显示出来，方便选择最快，如果有画质分辨率信息就更好了。

**Comment by Hiram-Wong** [comment]
设置里有个选项是延迟和缩略图

不知是否对你有帮助

<img width="1000" alt="image" src="https://github.com/Hiram-Wong/ZyPlayer/assets/30908279/c4b33c06-0ff3-4ee1-8be3-8f31cb29a00b">
