### ISSUE TITLE
yarn build:win提示memory allocation of 188975760 bytes failed

### ISSUE THREAD

**Issue by dcount107** [Hiram-Wong/ZyPlayer#186]
### zyplayer 版本

3.3.4

### 重现步骤

yarn build:win

### 实际结果

[plugin:vite:resolve] [plugin vite:resolve] Module "os" has been externalized for browser compatibility, imported by "D:/My_WorkShop/Electron_WorkShop/ZyPlayer-3.3.4/node_modules/ip/lib/ip.js". See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
transforming (3172) ..\..\node_modules\monaco-editor\esm\vs\basic-languages\protobuf\protobuf.contribution.jsmemory allocation of 188975760 bytes failed
error Command failed with exit code 3221226505.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### 系统架构

windows

### 系统版本

windows 11

**Comment by dcount107** [comment]
源代码未做任何修改，node版本18.20，内存32GB，可以确定可用内存大于18GB。既然无法复现该问题，应该是我电脑的问题，我再试试，谢谢。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月3日(星期五) 下午5:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Hiram-Wong/ZyPlayer] yarn build:win提示memory allocation of 188975760 bytes failed (Issue #186)














 
复现不了该问题，电脑内存多大，是否修改过东西

**Comment by Hiram-Wong** [comment]
你可以多打几次试试
