### ISSUE TITLE
有些直播没有声音

### ISSUE THREAD

**Issue by towerstreet** [Hiram-Wong/ZyPlayer#19]
感谢大佬维护这么好的软件！使用中发现有些直播没有声音，但在kodi里面是正常的。望测试修复。

**Comment by Hiram-Wong** [comment]
> 感谢大佬维护这么好的软件！使用中发现有些直播没有声音，但在kodi里面是正常的。望测试修复。

提供下 m3u8 地址，我看看

**Comment by towerstreet** [comment]
> > 感谢大佬维护这么好的软件！使用中发现有些直播没有声音，但在kodi里面是正常的。望测试修复。
> 
> 提供下 m3u8 地址，我看看

就是道长仓库的那个一键配置里面的
