### ISSUE TITLE
版本升级后drpy源不支持

### ISSUE THREAD

**Issue by 9E307** [Hiram-Wong/ZyPlayer#192]
### zyplayer 版本

3.34

### 重现步骤

我在自己的服务器上自建了道长的drpy，一直使用3.29版本用了半年多，今天心血来潮升级到3.34版本，然后里面的源就无法工作了。恢复出厂设置或者重装之后再重新一键配置，依然不行，装回老的3.29版本 drpy就恢复正常。请问如何解决？

### 期望结果

让自建的drpy在新版本里正常工作

### 系统架构

X64

### 系统版本

Windows7，Windows11

**Comment by Hiram-Wong** [comment]
给出报错信息

**Comment by hjdhnx** [comment]
> 道长的drpy

请问你用的是drpy的js1吗，里面全是type=3的js源的那个。如果是的话，你导入新版zyplayer里选择hipy，是可以用的

**Comment by hjdhnx** [comment]
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/49803097/3911b663-79b0-4db9-8fab-54eb8f67e2ed)
亲测drpy的js1源选择hipy导入，没问题的，能用能播

**Comment by hjdhnx** [comment]
再次测试，drpy的js0源也是没问题的。
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/49803097/b39b8167-8e34-485f-8861-6edcc2d880f1)

**Comment by 9E307** [comment]
谢谢您的提醒，但是我依然无法导入，而且软件没有错误提示窗口，点击确定之后就没有了反应。我正准备重新搭建一次drpy看看。
