### ISSUE TITLE
希望增加触控支持的播放器

### ISSUE THREAD

**Issue by nigyta8** [Hiram-Wong/ZyPlayer#199]
### 这个功能解决了什么问题

作为少数原生支持arm64的播放器，非常感谢开发者对woa的不离不弃。不过woa的设备基本上是触屏的，西瓜和呆呆却是不支持手势操作的，个人感觉增加手势操作的播放器能极大提升应用的体验。顺带有一个小问题，自定义播放器唤起potplayer和vlc均会出现无法打开mrl文件的问题，求问有无解决方法

### 你建议的方案是什么

内置触控手势支持的播放器选项

**Comment by Hiram-Wong** [comment]
没有设备测试，

目前已知的是因为是桌面应用都不支持拖拽等快捷操作，这些播放器都得在手机环境下才支持

所以要实现的话只能手动造轮子就比较麻烦了
