### ISSUE TITLE
软件未退出的情况下关闭电脑，再次开机右下角有图标，就是打不开软件。

### ISSUE THREAD

**Issue by dddCGCs** [Hiram-Wong/ZyPlayer#202]
### zyplayer 版本

3.3.3

### 重现步骤

安装好软件，配置好源地址，不关机就没问题，如果软件在打开的状态下关机，再次开机软件无法打开，右下角有图标，任务栏也有窗口，但是无法打开软件界面。。

### 系统架构

x64

### 系统版本

win10，ltsb精简版本

**Comment by Hiram-Wong** [comment]
正常退出正常吗

右下角有图标点显示可以吗
