### ISSUE TITLE
自定义播放器:播放无法打开调用自定义播放器

### ISSUE THREAD

**Issue by CharleVV** [Hiram-Wong/ZyPlayer#204]
### zyplayer 版本

3.3.4

### 重现步骤

配置-基础配置-播放器-自定义(调用系统)，添加自定义播放器后，播放无响应，无法打开播放器。

### 系统架构

x64

### 系统版本

Windows10

**Comment by Hiram-Wong** [comment]
https://github.com/Hiram-Wong/ZyPlayer/actions/runs/9051968441

尝试这个版本，划到最下面

**Comment by CharleVV** [comment]
已尝试安装最新构建版本，依旧无法打开自定义播放器。以下为自定义播放器设置，软件安装路径确认无误。
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/16551922/8d656710-4b38-426f-ac7d-29d0f261b487)

**Comment by Hiram-Wong** [comment]
路径前后加双引号

**Comment by Hiram-Wong** [comment]
有空格

**Comment by CharleVV** [comment]
![0198569F](https://github.com/Hiram-Wong/ZyPlayer/assets/16551922/4fd8ced4-a3d5-4142-beb6-92a80fba6f0c)
感谢，原来如此。
