### ISSUE TITLE
AI智能去广告开关[在基础配置里增加。同时每个详情选集上增加]

### ISSUE THREAD

**Issue by hjdhnx** [Hiram-Wong/ZyPlayer#205]
### 这个功能解决了什么问题

解决了菠菜站的资源总是看赌博广告的问题

### 你建议的方案是什么

1.页面组件|基础配置里增加智能去广告开关[switch组件] 
2.页面详情页，选集解析按钮旁边增加一个开关
3.fastify服务增加一个/fixAdM3u8接口，支持传入url和headers参数
4.访问接口，传递url=http.xx.m3u8&type=m3u8,服务内部通过类似drpy3.ts的fixm3u8Ai的逻辑将直链地址获取文本并且处理完内容，返回对应的m3u8的response
5.嗅探出直链或着调用免嗅探得到直链后判定直链是m3u8类型并且去广告开关打开的情况，自动把播放器连接设置为fastify服务的接口连接加url=m3u8的连接，如果m3u8有防盗等东西，可能还要传入headers里的referer。如果是嗅探来的，headers可以默认传嗅探过程中使用的headers，如果是免嗅探来的，免嗅探返回的数据里理论上也有headers。
6.此功能原理简单，但是涉及页面修改，道长比较菜，不然就自己加了。

**Comment by fourbeauty** [comment]
现在的赌博广告真肆无忌惮了

**Comment by hjdhnx** [comment]
> 现在的赌博广告真肆无忌惮了

新版本支持了，现在各种资源视频也有很好的观影体验
