### ISSUE TITLE
添加影视配置尝试多个json都显示无数据

### ISSUE THREAD

**Issue by Dog-Elder** [Hiram-Wong/ZyPlayer#209]
### zyplayer 版本

3.3.4

### 重现步骤

![动画](https://github.com/Hiram-Wong/ZyPlayer/assets/56543937/741f1344-3356-4002-9022-0426969562b7)

### 补充说明

自己关闭了VPN还是不可使用

**Comment by Hiram-Wong** [comment]
使用方法错误，

**Comment by Hiram-Wong** [comment]
认真阅读 #48
