### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by Dqqaz** [Hiram-Wong/ZyPlayer#21]
尊敬的开发者，能否为软件增加一个记录窗口大小状态的工能，默认窗口大小太小了

**Comment by Hiram-Wong** [comment]
> 尊敬的开发者，能否为软件增加一个记录窗口大小状态的工能，默认窗口大小太小了

之前考虑过，由于数据库选型问题导致实现比较复杂，然后哎呦疼并没有这个功能就去掉了
