### ISSUE TITLE
建议可以增加详细的使用手册，对于小白不是很懂基础管理的配置，另外增加源的下载和分享，找不源呢。

### ISSUE THREAD

**Issue by flyinghmx** [Hiram-Wong/ZyPlayer#211]
### 这个功能解决了什么问题

建议可以增加详细的使用手册，对于小白不是很懂基础管理的配置，另外增加源的下载和分享，找不源呢。

### 你建议的方案是什么

建议可以增加详细的使用手册，对于小白不是很懂基础管理的配置，另外增加源的下载和分享，找不源呢。

**Comment by Hiram-Wong** [comment]
请先仔细查看 #48 和 https://zy.catni.cn/
