### ISSUE TITLE
能不能打包一个安卓版本的

### ISSUE THREAD

**Issue by DifferentSparkler** [Hiram-Wong/ZyPlayer#214]
### zyplayer 版本

能不能打包一个安卓版本的

### 重现步骤

能不能打包一个安卓版本的

### 报错信息

能不能打包一个安卓版本的

### 期望结果

能不能打包一个安卓版本的

### 实际结果

能不能打包一个安卓版本的

### 系统信息

能不能打包一个安卓版本的

### 补充说明

能不能打包一个安卓版本的

**Comment by hjdhnx** [comment]
打包好了，拿去吧

https://wwi.lanzoup.com/i1JTt1yrfuib

**Comment by DifferentSparkler** [comment]
> 打包好了，拿去吧
> 
> https://wwi.lanzoup.com/i1JTt1yrfuib

好人一生平安，能不能教我一下怎么打包呀
