### ISSUE TITLE
添加源显示Cannot delete property '0' of [object String用得你给的

### ISSUE THREAD

**Issue by liuihu** [Hiram-Wong/ZyPlayer#217]
### zyplayer 版本

3.3.4

### 重现步骤

用#48给的源显示如题

### 系统信息

win64

**Comment by Hiram-Wong** [comment]
给出链接

**Comment by liuihu** [comment]
> 给出链接

3.3.2 后版本建议使用 基础设置->数据管理->配置导入->远端导入---地址[https://zy.catni.cn/api/config_v3.json]->导入

**Comment by Hiram-Wong** [comment]
没问题的这个链接，给出远程

**Comment by liuihu** [comment]
> 没问题的这个链接，给出远程
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=5200974324186439147 skey=@crypt_19e19c85_d51b2485df369d88d83653232241dde5 mmweb_appid=wx_webfilehelper](https://github.com/Hiram-Wong/ZyPlayer/assets/51263527/7857760d-3d3e-4d9a-8f10-81b6c704ffdd)

**Comment by Hiram-Wong** [comment]
上远程

**Comment by liuihu** [comment]
> 给出远程
749 803 850
7u13je

**Comment by Hiram-Wong** [comment]
设备不在线，什么远程工具 向日葵还是 todesk

**Comment by liuihu** [comment]
> 设备不在线，什么远程工具 向日葵还是 todesk

teamviewer

**Comment by Hiram-Wong** [comment]
6 360 误报，用火绒吧，360流氓

**Comment by liuihu** [comment]
thanks  想给你生个猴子

**Comment by xiayinsh** [comment]
> 6 360 误报，用火绒吧，360流氓

版主，这个问题确实存在，我也碰到了， 但是可以使用本地导入解决
