### ISSUE TITLE
[播放页面] 增加无边框播放页面

### ISSUE THREAD

**Issue by itxxq** [Hiram-Wong/ZyPlayer#218]
### 这个功能解决了什么问题

让播放页面更加简洁

### 你建议的方案是什么

参考腾讯视频无边框播放页面

**Comment by Hiram-Wong** [comment]
实现不了 能力有限 自己使用画画中画

**Comment by Hiram-Wong** [comment]
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/30908279/c1c352e8-ffe2-47b1-a769-419659773693)

**Comment by Hiram-Wong** [comment]
最小支持480*280, 开发版下载地址如下https://github.com/Hiram-Wong/ZyPlayer/actions/runs/9236689362
