### ISSUE TITLE
[影视分类] 请求增加推荐页

### ISSUE THREAD

**Issue by hjdhnx** [Hiram-Wong/ZyPlayer#221]
### 这个功能解决了什么问题

在源里辛苦写了推荐数据，zy没法可视化调试的问题。而且推荐数据也方便无聊的人跟着推荐看剧。有时候不知道想看什么就从推荐的剧随便点点咯

### 你建议的方案是什么

t3/t4源基本都有推荐页面。希望在分类最左边增加推荐区域。如果这个源有推荐数据则显示，没有则不显示，并默认显示的第一个分类的数据

**Comment by zjccc1999** [comment]
支持

**Comment by Duter2016** [comment]
这个功能之前在老版的zy-player 2.85里有这个功能，推荐数据是使用的豆瓣的，现在还保留着安装着这个版本的软件！也希望zyplayer能老版的这个功能移植过来！

**Comment by Hiram-Wong** [comment]
> 这个功能之前在老版的zy-player 2.85里有这个功能，推荐数据是使用的豆瓣的，现在还保留着安装着这个版本的软件！也希望zyplayer能老版的这个功能移植过来！

豆瓣数据下个版本回归

**Comment by Duter2016** [comment]
豆瓣热门电影：

[https://movie.douban.com/j/search_subjects?type=movie&tag=热门&sort=recommend&page_limit=200&page_start=1](https://movie.douban.com/j/search_subjects?type=movie&tag=热门&sort=recommend&page_limit=200&page_start=1)

豆瓣热门剧集：

[https://movie.douban.com/j/search_subjects?type=tv&tag=热门&sort=recommend&page_limit=200&page_start=1](https://movie.douban.com/j/search_subjects?type=tv&tag=热门&sort=recommend&page_limit=200&page_start=1)

豆瓣热门美剧：

[https://movie.douban.com/j/search_subjects?type=tv&tag=美剧&sort=recommend&page_limit=200&page_start=1](https://movie.douban.com/j/search_subjects?type=tv&tag=美剧&sort=recommend&page_limit=200&page_start=1)

豆瓣热门英剧：

[https://movie.douban.com/j/search_subjects?type=tv&tag=英剧&sort=recommend&page_limit=200&page_start=1](https://movie.douban.com/j/search_subjects?type=tv&tag=英剧&sort=recommend&page_limit=200&page_start=1)

豆瓣热门国产剧：

[https://movie.douban.com/j/search_subjects?type=tv&tag=国产剧&sort=recommend&page_limit=200&page_start=1](https://movie.douban.com/j/search_subjects?type=tv&tag=国产剧&sort=recommend&page_limit=200&page_start=1)

豆瓣高分电影：

[https://movie.douban.com/j/search_subjects?type=movie&tag=豆瓣高分&sort=recommend&page_limit=200&page_start=1](https://movie.douban.com/j/search_subjects?type=movie&tag=豆瓣高分&sort=recommend&page_limit=200&page_start=1)

豆瓣热门动漫：

[https://movie.douban.com/j/search_subjects?type=tv&tag=日本动画&sort=recommend&page_limit=200&page_start=1](https://movie.douban.com/j/search_subjects?type=tv&tag=日本动画&sort=recommend&page_limit=200&page_start=1)

豆瓣热门纪录片：

[https://movie.douban.com/j/search_subjects?type=tv&tag=纪录片&sort=recommend&page_limit=200&page_start=1](https://movie.douban.com/j/search_subjects?type=tv&tag=纪录片&sort=recommend&page_limit=200&page_start=1)

豆瓣热门综艺：

[https://movie.douban.com/j/search_subjects?type=tv&tag=综艺&sort=recommend&page_limit=200&page_start=1](https://movie.douban.com/j/search_subjects?type=tv&tag=综艺&sort=recommend&page_limit=200&page_start=1)

豆瓣热门动画电影：

[https://movie.douban.com/j/search_subjects?type=movie&tag=动画&sort=recommend&page_limit=200&page_start=1](https://movie.douban.com/j/search_subjects?type=movie&tag=动画&sort=recommend&page_limit=200&page_start=1)

豆瓣冷门佳片：

[https://movie.douban.com/j/search_subjects?type=movie&tag=冷门佳片&sort=recommend&page_limit=200&page_start=1](https://movie.douban.com/j/search_subjects?type=movie&tag=冷门佳片&sort=recommend&page_limit=200&page_start=1)
