### ISSUE TITLE
[组件名称] 任务栏 内能否只显示一个

### ISSUE THREAD

**Issue by feipinxiang** [Hiram-Wong/ZyPlayer#223]
### 这个功能解决了什么问题

任务栏占用太多，能否减少点任务栏占用？
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/2398548/8382e7d7-f0f5-4ba0-9d8e-2dfaf03fabb7)

### 你建议的方案是什么

比如pip、播放窗口不显示在任务栏

**Comment by Hiram-Wong** [comment]
不存在该问题，应该是你电脑设置了什么东西

**Comment by feipinxiang** [comment]
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/2398548/a80e87b7-9a08-4040-ba79-f802a4e1670c)
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/2398548/fa251b2b-c140-4b8b-9841-9cfef4088516)
没有设置什么东西啊。如果开合并就是小图标的形式，不开合并就是下面这种形式
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/2398548/a20d6f32-406d-4c74-ac5b-aa5de064680a)

**Comment by feipinxiang** [comment]
3.3.4刚升级了下3.3.6 还是这样的，应该不是版本的问题
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/2398548/00e26320-241f-435e-8f58-e51483fe4ddd)

**Comment by fourbeauty** [comment]
> 3.3.4刚升级了下3.3.6 还是这样的，应该不是版本的问题. Windows 10 专业版 22H2 19045.4412 ![image](https://private-user-images.githubusercontent.com/2398548/333043733-00e26320-241f-435e-8f58-e51483fe4ddd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MzA0NjksIm5iZiI6MTcxNjUzMDE2OSwicGF0aCI6Ii8yMzk4NTQ4LzMzMzA0MzczMy0wMGUyNjMyMC0yNDFmLTQzNWUtOGY1OC1lNTE0ODNmZTRkZGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjRUMDU1NjA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzY1NWM1MTk2OGI2NmVmZjVmZjlkOTA1M2RkZmNiZGI2OWNhZGUwY2M1M2YyNmE3YzM4NDQ3ZjE4MzI0ZTRiZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KddudSU04_q7kJDLHHHMM7ny5pNYTRPwOUwzawTKpZk)
一个窗口一个任务栏图标合理的，合并了就不对了

**Comment by Hiram-Wong** [comment]
<img width="1512" alt="image" src="https://github.com/Hiram-Wong/ZyPlayer/assets/30908279/3293ed41-bb32-44ed-b784-0a103b6d13ae">
win11显示状态

**Comment by feipinxiang** [comment]
> <img alt="image" width="1512" src="https://private-user-images.githubusercontent.com/30908279/333778941-3293ed41-bb32-44ed-b784-0a103b6d13ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDQ1MDUsIm5iZiI6MTcxNjY0NDIwNSwicGF0aCI6Ii8zMDkwODI3OS8zMzM3Nzg5NDEtMzI5M2VkNDEtYmIzMi00NGVkLWI3ODQtMGExMDNiNmQxM2FlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDEzMzY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhMTljNTI2YmMyYzM4MjI2YjMzMzg0NzVkY2I0M2IzMDk4OGU2ZjFmNzUyMDY1NjFlYWMxMGVkYjU4NDg3YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xTnPqah2xGWB6abJkmL2O7Ge_wG_99AybGT_oDIUeRE"> win11显示状态

看图片win11应该也是多个任务栏，只不过你的是合并状态。上面哥们说的也在理，想了下好像没有两全其美的办法，我先关闭了。
