### ISSUE TITLE
为什么这么卡呢，播放太慢了，而且切换源时，搜索条件不起作用吗[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by yuf19-2022** [Hiram-Wong/ZyPlayer#227]
### 这个功能解决了什么问题

为什么这么卡呢，播放太慢了，而且切换源时，搜索条件不起作用吗

### 你建议的方案是什么

为什么这么卡呢，播放太慢了，而且切换源时，搜索条件不起作用吗

**Comment by Hiram-Wong** [comment]
卡就换啊，搜索是全局的啊，设置里可以设置搜索全局还是单个啊，觉得烂可以不用

**Comment by Hiram-Wong** [comment]
烂你还用，你是犯贱吗

**Comment by Hiram-Wong** [comment]
爱用不用把，软件就这样

**Comment by psbelejden** [comment]
> > 卡就换啊，搜索是全局的啊，设置里可以设置搜索全局还是单个啊，觉得烂可以不用
> 
> 你是个sb吧，我就说说就冒犯你了？本来就烂，卡的一比，换个屁哪个不卡？，一切换源就搜索莫名其妙的跟我的搜索有屁的关系

我发现你才是个臭sb把

**Comment by Hiram-Wong** [comment]
> > > 卡就换啊，搜索是全局的啊，设置里可以设置搜索全局还是单个啊，觉得烂可以不用
> 
> > 
> 
> > 你是个sb吧，我就说说就冒犯你了？本来就烂，卡的一比，换个屁哪个不卡？，一切换源就搜索莫名其妙的跟我的搜索有屁的关系
> 
> 
> 
> 我发现你才是个臭sb把 

就此打住我，切勿人身攻击
