### ISSUE TITLE
[hipy] 搜索结果页及推荐内容页bug

### ISSUE THREAD

**Issue by seraphjerry** [Hiram-Wong/ZyPlayer#228]
### zyplayer 版本

3.3.6

### 重现步骤

![搜索页](https://github.com/Hiram-Wong/ZyPlayer/assets/152712616/c869bff3-d5a0-48d4-9afd-355a421184ab)
![推荐信息页](https://github.com/Hiram-Wong/ZyPlayer/assets/152712616/449d981b-8bc9-4e10-ae14-b678a1c83821)

第一个：使用hipy源进行搜索显示后的内容，无法进入内容详细页面，提示：请求资源站失败，请检查网络（如图一：360影视[官]），但从这个资源站进入可以进入内容详细页页面。

第二个：目前推荐内容页面无任何内容显示：如图二

### 系统信息

win10

**Comment by Hiram-Wong** [comment]
推荐内容不显示你那边网络问题，接口正常

**Comment by seraphjerry** [comment]
应该不是，道长群里多人测试都有问题，目前测试多个版本：zyplayer-win-3.3.5-x64-0514-1智能去广版本正常。






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月25日(星期六) 下午4:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Hiram-Wong/ZyPlayer] [hipy] 搜索结果页及推荐内容页bug (Issue #228)














 
推荐内容不显示你那边网络问题，接口正常

**Comment by Hiram-Wong** [comment]
<img width="1000" alt="image" src="https://github.com/Hiram-Wong/ZyPlayer/assets/30908279/f42e46af-f162-406d-bf9b-a1e920043ffd">

**Comment by seraphjerry** [comment]
关于第一个问题：我又测了几遍，关于搜索页无法进入详细页，目前选择本站搜索可以正常进入。但是组内搜索和聚合搜索都有问题。

关于第二个问题：我升级最新版的3.3.6，无法显示搜索推荐内容。退回3.3.5之后可以正常显示了。

**Comment by seraphjerry** [comment]
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/152712616/a713bebb-9fd6-4f79-98ae-6d24cf9227a0)

这是群里其他人测试的结果

**Comment by seraphjerry** [comment]
第二个问题，找到解决方法了，我用户代理设置为空，ua的问题，修改后可以正常显示搜索的推荐内容了。

第一个bug，经过多人测试，都发现有问题。只限hipy源在使用的组内搜索和聚合搜索时会复现，本站搜索没有问题。 但采集源和nodejs源没有这个问题。

**Comment by Hiram-Wong** [comment]
开发版下载地址https://github.com/Hiram-Wong/ZyPlayer/actions/runs/9236689362
