### ISSUE TITLE
[播放器功能反馈]关于玩家播放器

### ISSUE THREAD

**Issue by nigyta8** [Hiram-Wong/ZyPlayer#238]
### zyplayer 版本

3.3.6

### 重现步骤

玩家播放器的进度条不会自动沉降（消失）

### 期望结果

不知道是播放器问题还是bug，希望可以修复

### 系统信息

Windows11 on arm 23h2

**Comment by Hiram-Wong** [comment]
我这正常

**Comment by nigyta8** [comment]
我重装一下试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月1日(周六) 中午11:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hiram-Wong/ZyPlayer] [播放器功能反馈]关于玩家播放器 (Issue #238)




 
我这正常

**Comment by nigyta8** [comment]
依旧未能自动消失



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月1日(周六) 中午11:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hiram-Wong/ZyPlayer] [播放器功能反馈]关于玩家播放器 (Issue #238)




 
我这正常

**Comment by Hiram-Wong** [comment]
其他正常吗，就玩家有问题吗

**Comment by nigyta8** [comment]
其余正常，只不过好像只有玩家支持触屏，我也是一直触屏使用，不知道有无关系



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月1日(周六) 中午11:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hiram-Wong/ZyPlayer] [播放器功能反馈]关于玩家播放器 (Issue #238)




 
其他正常吗，就玩家有问题吗

**Comment by Hiram-Wong** [comment]
晚点看一下

**Comment by nigyta8** [comment]
麻烦大佬了，感谢🙏



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月1日(周六) 中午12:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hiram-Wong/ZyPlayer] [播放器功能反馈]关于玩家播放器 (Issue #238)




 
晚点看一下

**Comment by Hiram-Wong** [comment]
没发现问题，你试试这个版本是否正常https://github.com/Hiram-Wong/ZyPlayer/actions/runs/9322765266

最下面有个下载

**Comment by Hiram-Wong** [comment]
该问题需要触发什么额外条件吗，比如点击全屏还是啥的，有没有更完整的触发条件

**Comment by nigyta8** [comment]
现在才看到这个邮件。没有任何触发条件，已重装24h2 arm ltsc，从头重新配置，玩家播放器底栏不会消失的问题依旧存在，可能小米平板5有毒(´இ皿இ｀)



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月5日(周三) 凌晨1:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hiram-Wong/ZyPlayer] [播放器功能反馈]关于玩家播放器 (Issue #238)




 
该问题需要触发什么额外条件吗，比如点击全屏还是啥的，有没有更完整的触发条件

**Comment by Hiram-Wong** [comment]
> 现在才看到这个邮件。没有任何触发条件，已重装24h2 arm ltsc，从头重新配置，玩家播放器底栏不会消失的问题依旧存在，可能小米平板5有毒(´இ皿இ｀)
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年6月5日(周三) 凌晨1:01 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Hiram-Wong/ZyPlayer] [播放器功能反馈]关于玩家播放器 (Issue #238) 该问题需要触发什么额外条件吗，比如点击全屏还是啥的，有没有更完整的触发条件 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

窗口模式播放，点一下非视频区域也不行吗

**Comment by nigyta8** [comment]
录了个视频，给您看下▄█▀█●



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月1日(周日) 晚上6:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hiram-Wong/ZyPlayer] [播放器功能反馈]关于玩家播放器 (Issue #238)




  
现在才看到这个邮件。没有任何触发条件，已重装24h2 arm ltsc，从头重新配置，玩家播放器底栏不会消失的问题依旧存在，可能小米平板5有毒(´இ皿இ｀)
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年6月5日(周三) 凌晨1:01 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [Hiram-Wong/ZyPlayer] [播放器功能反馈]关于玩家播放器 (Issue #238) 该问题需要触发什么额外条件吗，比如点击全屏还是啥的，有没有更完整的触发条件 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
窗口模式播放，点一下非视频区域也不行吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
 
 	
 	 		 			从QQ邮箱发来的超大附件 	
 	 		 				 					 						 							 						 					
 					 						 							VID_20240901_183641.mp4 							 (130.5MB, 2024年10月1日 18:37) 						 						 							进入下载页面 							：https://wx.mail.qq.com/ftn/download?func=3&k=c8cf47312b290b79fabc1931366663650098103934666365121f4f4501045a5d05031a5752575a480001000819555753041d06020707535302510f57575f74656179736e06565151070907006b575b560104061f5916577124499023efd3f3625379ac63e89280eceb1bd0563466636537303731&key=c8cf47312b290b79fabc1931366663650098103934666365121f4f4501045a5d05031a5752575a480001000819555753041d06020707535302510f57575f74656179736e06565151070907006b575b560104061f5916577124499023efd3f3625379ac63e89280eceb1bd0563466636537303731&code=70714fce&from=
