### ISSUE TITLE
不支持音频/视频格式，但源能下载解析出来播放

### ISSUE THREAD

**Issue by liao-1** [Hiram-Wong/ZyPlayer#24]

**Comment by Hiram-Wong** [comment]
请提供链接

**Comment by liao-1** [comment]
http://39.136.66.36/cdnrrs.gz.chinamobile.com/PLTV/88888888/224/3221225682/1/index.m3u8?fmt=ts2hls
http://39.136.66.36/cdnrrs.gz.chinamobile.com/PLTV/88888888/224/3221225682/1/index.m3u8?fmt=ts2hls
http://39.136.66.36/cdnrrs.gz.chinamobile.com/PLTV/88888888/224/3221225672/1/index.m3u8?fmt=ts2hls

**Comment by liao-1** [comment]
> 请提供链接
http://39.136.66.36/cdnrrs.gz.chinamobile.com/PLTV/88888888/224/3221225682/1/index.m3u8?fmt=ts2hls
http://39.136.66.36/cdnrrs.gz.chinamobile.com/PLTV/88888888/224/3221225682/1/index.m3u8?fmt=ts2hls
http://39.136.66.36/cdnrrs.gz.chinamobile.com/PLTV/88888888/224/3221225672/1/index.m3u8?fmt=ts2hls

**Comment by liao-1** [comment]
> 请提供链接https://gitee.com/liaoqizhong/mydezhibo1/raw/master/gz1.m3u8
