### ISSUE TITLE
播放器 所有线路是否可以直接全部显示

### ISSUE THREAD

**Issue by GGreyCat** [Hiram-Wong/ZyPlayer#240]
### 这个功能解决了什么问题

一目了然的看到全部线路的情况 

### 你建议的方案是什么

左右方向箭头改成下拉悬浮式的
或者 直接换行输出的
或者 列表样式的
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/60751934/2069d798-027c-4ce0-b2bd-5bf0320443d3)

![image](https://github.com/Hiram-Wong/ZyPlayer/assets/60751934/c740c77b-ede6-481a-9a6a-71459237f370)

![image](https://github.com/Hiram-Wong/ZyPlayer/assets/60751934/5be8177d-320b-433a-b5ff-e829f8bb76ce)

**Comment by hjdhnx** [comment]
![Screenshot_2024-06-03-18-14-09-174_com example hi](https://github.com/Hiram-Wong/ZyPlayer/assets/49803097/8752c292-a68c-4fb0-9178-b4a3ee3968e0)
![Screenshot_2024-06-03-18-14-12-542_com example hi](https://github.com/Hiram-Wong/ZyPlayer/assets/49803097/47a04b71-6891-45cb-a783-04ade72857db)
如图所示默认是左右切换，点击弹出就比较好。平时不需要全部显示出来

**Comment by Hiram-Wong** [comment]
3.3.8 版本采用爱x艺设计，关闭此 issue
