### ISSUE TITLE
影视界面 现在因为源太多了 想看某个网站翻找比较困难

### ISSUE THREAD

**Issue by GGreyCat** [Hiram-Wong/ZyPlayer#241]
### 这个功能解决了什么问题

解决 在影视界面找某一个网站困难的问题

### 你建议的方案是什么

方法1
方法2
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/60751934/46c5bb56-5d8d-4b21-a0ba-39159f2c282a)
如果可以在方法2后面加个排序图标

**Comment by hjdhnx** [comment]
方案2比较好

**Comment by Hiram-Wong** [comment]
感谢您提出的宝贵意见，下个版本加入，搜索功能已实现，针对排序能力暂无精力研究

**Comment by outline-x** [comment]
求大佬分享源，拜托拜托

**Comment by Francis10032** [comment]
> 請問搜尋功能可以用了嗎? 我不管怎麼找都 找到一片空白.. 明明看得到..都找不到.. ![20240923_001](https://private-user-images.githubusercontent.com/30289756/369707203-8a44402f-d8b2-42d9-b658-71f4bfcf8f76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTk1MTAsIm5iZiI6MTczMTY1OTIxMCwicGF0aCI6Ii8zMDI4OTc1Ni8zNjk3MDcyMDMtOGE0NDQwMmYtZDhiMi00MmQ5LWI2NTgtNzFmNGJmY2Y4Zjc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDA4MjY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwYjQ5MjRlN2VlOWZiYzRiZTY4YzcwMGVkODNkOTFiZDQyOTI5ODMwYTVhNzczNTlhOGZkYTBlYzVkNTBkNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Nl8BYwAckkrH7jzSE4YVG0uITW43-OJbQn0O7bA4ulA) ![20240923_002](https://private-user-images.githubusercontent.com/30289756/369707205-5375c1c8-1d78-4e38-b69d-09d81454bf6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTk1MTAsIm5iZiI6MTczMTY1OTIxMCwicGF0aCI6Ii8zMDI4OTc1Ni8zNjk3MDcyMDUtNTM3NWMxYzgtMWQ3OC00ZTM4LWI2OWQtMDlkODE0NTRiZjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDA4MjY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNzJjMzMxNzA0NmY3YjQwMWM2ODM0ZTkwYWZkYmJkYzNjNmNiZDM4NTBhZWRmMDcxNzVlNWNmYWVkNjJiZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aaw9XCFyEpNkXmwcW5_d7Pck1EckYc6VToY9xxpPP2g)
基础配置中搜索选聚合，影视配置中编辑每一个源，将搜索设置为聚合。
