### ISSUE TITLE
[电视界面] 加入列表模式（去图标）

### ISSUE THREAD

**Issue by GGreyCat** [Hiram-Wong/ZyPlayer#242]
### 这个功能解决了什么问题

解决想要使用列表式的习惯

### 你建议的方案是什么

去图标化
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/60751934/6665731d-97d0-4c57-8c47-9758f0299e92)

**Comment by Hiram-Wong** [comment]
感谢你提出的宝贵意见，针对该需求咱不给予实现
