### ISSUE TITLE
[影视配置] 随着源越来越多 管理起来也越来越麻烦了 （需要仓库）

### ISSUE THREAD

**Issue by GGreyCat** [Hiram-Wong/ZyPlayer#243]
### 这个功能解决了什么问题

cms和js不能一起 检测   需要分开 加入仓库功能

### 你建议的方案是什么

加入可以随时切换的仓库功能
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/60751934/0510e44c-549a-4db8-ac59-63da15d5a992)
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/60751934/e390eca6-b320-410d-b879-3dd05ab303a8)

**Comment by malimaliao** [comment]
按cms/js/app更合理，其实tvbox多仓的方式很臃肿，越来越理工男风格

**Comment by wtming** [comment]
因为每个接口都有几个需要的源，又不能同时使用，导来导去的很麻烦，有个仓库的话可以对不同的接口随时都能切换，或者能在导入新的接口的时候不会完全覆盖老的数据，只是增加新的源

**Comment by Hiram-Wong** [comment]
> 因为每个接口都有几个需要的源，又不能同时使用，导来导去的很麻烦，有个仓库的话可以对不同的接口随时都能切换，或者能在导入新的接口的时候不会完全覆盖老的数据，只是增加新的源

暂不考虑该变动，建议自己合并数据源

**Comment by wtming** [comment]
> > 因为每个接口都有几个需要的源，又不能同时使用，导来导去的很麻烦，有个仓库的话可以对不同的接口随时都能切换，或者能在导入新的接口的时候不会完全覆盖老的数据，只是增加新的源
> 
> 既然如此，爲什麽你不講這幾個源放在一個接口呢？或者説，你根本沒有想過自己維護一個接口？

我当然可以放在一起，而且也已经有自己的接口了，但是每个人都有不同的喜好，你是想让每个使用这个软件的人都自己维护一个接口？

**Comment by HelloMusician** [comment]
开源的东西，别较劲，有得用就得了呗
