### ISSUE TITLE
[直播组件]开关按钮显示错误

### ISSUE THREAD

**Issue by wtming** [Hiram-Wong/ZyPlayer#247]
### zyplayer 版本

3.3.6

### 重现步骤

3.3.5版本也有这个问题，就是直播源列表里，开关按钮点击时会在鼠标上方又显示一个新的开关按钮，有开启关闭效果，但是实际上没有任何效果。

### 系统信息

win10

**Comment by Hiram-Wong** [comment]
没懂 上截图

**Comment by Hiram-Wong** [comment]
下个版本修复，没有啥影响

**Comment by wtming** [comment]
> 下个版本修复，没有啥影响

希望增加一个主页，添加豆瓣推荐

**Comment by Hiram-Wong** [comment]
#221
