### ISSUE TITLE
你好这个播放器能支持cmsv10视频站上的播放器导入吗

### ISSUE THREAD

**Issue by cengzhijie3** [Hiram-Wong/ZyPlayer#254]
### 这个功能解决了什么问题

你好这个播放器能支持cmsv10视频站上的播放器导入吗

### 你建议的方案是什么

你好这个播放器能支持cmsv10视频站上的播放器导入吗

**Comment by Hiram-Wong** [comment]
感谢您提出的建议，该提议没有实际意义，暂无计划
