### ISSUE TITLE
[bug] 基础配置修改后无法保存

### ISSUE THREAD

**Issue by seraphjerry** [Hiram-Wong/ZyPlayer#255]
### zyplayer 版本

3.3.7

### 重现步骤

1.基础配置里面:，好几个内容修改后，重启软件都无法保存
   如：默认播放器修改后，重启后会变回西瓜播放器

2.窗口调整大小后，无法记住【算需求】。

希望基本设置可以增加个保存应用的按钮。

**Comment by Hiram-Wong** [comment]
1.应该是你tbl_setting表数据格式有问题导致的
2.打开窗口位置即可

**Comment by seraphjerry** [comment]
好的，初始化，重新编辑导入配置文件后，正常了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hiram-Wong/ZyPlayer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月9日(星期天) 中午11:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hiram-Wong/ZyPlayer] [bug] 基础配置修改后无法保存 (Issue #255)





 
1.应该是你tbl_setting表数据格式有问题导致的
 2.打开窗口位置即可
