### ISSUE TITLE
[写源工具  智脑 ai] 问题

### ISSUE THREAD

**Issue by GGreyCat** [Hiram-Wong/ZyPlayer#256]
### 这个功能解决了什么问题

问题1 超时提示 5000 改了配置里的超时倒是能解决 但如果能分开就好了
问题2 
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/60751934/4b80583d-c2eb-4519-a3b2-8406c2f82ef1)
筛选出来的内容 关键字没有双引号  其他的还是单引号 希望修改
问题3 外层好像不能是 div 标签  否则会报错

### 你建议的方案是什么

问题1 超时提示 5000 改了配置里的超时倒是能解决 但如果能分开就好了
问题2 
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/60751934/4b80583d-c2eb-4519-a3b2-8406c2f82ef1)
筛选出来的内容 关键字没有双引号  其他的还是单引号 希望修改
问题3 外层好像不能是 div 标签  否则会报错

**Comment by Hiram-Wong** [comment]
1.不会改
2.js里key不带双引号不会影响
3.报什么错

**Comment by GGreyCat** [comment]
失败:AxiosError: timeout of 10000ms exceeded
失败:AxiosError: Request failed with status code 500
但有时修改需求后 又管了

**Comment by Hiram-Wong** [comment]
第一个是超时，第二个是openai返回错误或者代理平台限制
