### ISSUE TITLE
[tv] MACOS, 电视一直在加载中无法播放

### ISSUE THREAD

**Issue by torans** [Hiram-Wong/ZyPlayer#258]
### zyplayer 版本

3.3.6

### 重现步骤

https://zy.catni.cn/api/config_v3.json

### 系统信息

MACOS(14,5) intel

### 补充说明

节目能加载出来，电视点击后无法播放，一直转圈圈

**Comment by Hiram-Wong** [comment]
ipv4 的基本都挂了，需要自己找
