### ISSUE TITLE
配置了影视资源后，软件打开都是白屏，配置也没有

### ISSUE THREAD

**Issue by 13174771** [Hiram-Wong/ZyPlayer#259]
### zyplayer 版本

3.3.6

### 重现步骤

配置了影视资源后，软件打开都是白屏，配置也没有，没有任何数据了，怎么能导出我的配置数据呢？？？
![1](https://github.com/Hiram-Wong/ZyPlayer/assets/116151320/5aa84359-4e23-487c-a1e2-c401b9cd20e4)

### 系统信息

win11

**Comment by Hiram-Wong** [comment]
数据损坏了，应该是导入的数据没有按照要求格式，重装吧

**Comment by 13174771** [comment]
重新安装也不行，在配置数据的时候出现的问题，现在什么都打不开，都是空白的，设置也不能打开了。

**Comment by user201905** [comment]
配置完后，点过刷新吗

**Comment by Hiram-Wong** [comment]
请先严格按照标准数据结构检查你的数据

**Comment by wtming** [comment]
> 请先严格按照标准数据结构检查你的数据

请问您和云星日记有关系吗？为什么您这新版本还没发布，他那已经有3.3.7版本了？

**Comment by Hiram-Wong** [comment]
> > 请先严格按照标准数据结构检查你的数据
> 
> 
> 
> 请问您和云星日记有关系吗？为什么您这新版本还没发布，他那已经有3.3.7版本了？

你要说关系也有关系，你要说没关系也没关系。代码还是我正常提交都是beta测试的，没正式发布罢了，他只是打个包发出来罢了

**Comment by HH346581** [comment]
一样问题不能使用一键配置  只能使用本地导入

**Comment by Hiram-Wong** [comment]
> 一样问题不能使用一键配置  只能使用本地导入
> 
> 

只能说明你用的数据不是标准数据，请先严格按照标准数据结构检查你的数据

**Comment by 13174771** [comment]
把C:\Users\Administrator\AppData\Roaming\zyplayer里的配置文件删除，在重新配置就好了
