### ISSUE TITLE
有没有安卓包

### ISSUE THREAD

**Issue by yuf19-2022** [Hiram-Wong/ZyPlayer#26]

**Comment by jahem** [comment]
https://wwza.lanzouo.com/b04duy3xi【密码：c3nr】

**Comment by Hiram-Wong** [comment]
> https://wwza.lanzouo.com/b04duy3xi【密码：c3nr】

大佬牛逼https://github.com/qallen028/ZyPlayer

**Comment by qallen028** [comment]
> > [https://wwza.lanzouo.com/b04duy3xi【密码：c3nr】](https://wwza.lanzouo.com/b04duy3xi%E3%80%90%E5%AF%86%E7%A0%81%EF%BC%9Ac3nr%E3%80%91)
> 
> 大佬牛逼https://github.com/qallen028/ZyPlayer

不敢不敢，在你大佬面前我只是个小弟，我还是紧跟大佬的更新步伐

**Comment by CxiaoyuN** [comment]
苹果有吗 (●'◡'●)
