### ISSUE TITLE
IPTV电视播放只有声音没有画面

### ISSUE THREAD

**Issue by murazi** [Hiram-Wong/ZyPlayer#261]
### zyplayer 版本

找不到版本号标识，就是最近下的版本

### 重现步骤

IPTV源没问题，在电视上都OK
但加入ZYP就不行，只有声音没有画面，尝试切换了播放器也不行，看影视资源都正常，唯独电视不行，关闭再进也是一样

### 报错信息

没有报错，正常播放，就是没有画面

### 期望结果

有画面

### 实际结果

无画面

### 系统信息

CPU：intel，显卡：RTX3060

**Comment by Hiram-Wong** [comment]
提供下播放地址

**Comment by wtming** [comment]
http://[2409:8087:1a01:df::7005]:80/ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226559/index.m3u8  用这个试一下

**Comment by Hiram-Wong** [comment]
> http://[2409:8087:1a01:df::7005]:80/ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226559/index.m3u8 用这个试一下

这个是 hevc 格式

**Comment by wtming** [comment]
> > http://[2409:8087:1a01:df::7005]:80/ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226559/index.m3u8 用这个试一下
> 
> 这个是 hevc 格式，老版本是不支持的，最新 beta 兼容部分 hevc(h265)不能保证完全可用，可以尝试调用系统播放器

大神，我用老的版本有声音没画面，用3.3.7版本的反而什么都加载不出来了，以前有声音有画面的现在加载出来也慢很多

**Comment by Hiram-Wong** [comment]
> > > http://[2409:8087:1a01:df::7005]:80/ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226559/index.m3u8 用这个试一下
> 
> > 
> 
> > 这个是 hevc 格式，老版本是不支持的，最新 beta 兼容部分 hevc(h265)不能保证完全可用，可以尝试调用系统播放器
> 
> 
> 
> 大神，我用老的版本有声音没画面，用3.3.7版本的反而什么都加载不出来了，以前有声音有画面的现在加载出来也慢很多

没有遇到，37只在36做了播放器bug修复而已

**Comment by wtming** [comment]
> > > > http://[2409:8087:1a01:df::7005]:80/ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226559/index.m3u8 用这个试一下
> > 
> > 
> > > 
> > 
> > 
> > > 这个是 hevc 格式，老版本是不支持的，最新 beta 兼容部分 hevc(h265)不能保证完全可用，可以尝试调用系统播放器
> > 
> > 
> > 大神，我用老的版本有声音没画面，用3.3.7版本的反而什么都加载不出来了，以前有声音有画面的现在加载出来也慢很多
> 
> 没有遇到，37只在36做了播放器bug修复而已，试下艺术播放器

哦，好的，我一直用的是呆呆播放器，是从3.3.4改到3.3.7的

**Comment by chenhonghe2021** [comment]
> > http://[2409:8087:1a01:df::7005]:80/ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226559/index.m3u8 用这个试一下
> 
> 这个是 hevc 格式，老版本是不支持的，最新 beta 兼容部分 hevc(h265)不能保证完全可用，可以尝试调用系统播放器

调用系统播放器，就没成功过，不知道是不是我设置问题。

比如环境win11，播放器VLC：
C:\Program Files\VideoLAN\VLC\vlc.exe

![image](https://github.com/user-attachments/assets/d65be970-e9b0-4063-ad87-e0069cd6ff97)

同样win11 ，播放器PotPlayer：
D:\Program Files\DAUM\PotPlayer\PotPlayerMini64.exe
![image](https://github.com/user-attachments/assets/82353301-96ab-46f3-b3ba-9047079d9697)

结局都是没法成功调用

**Comment by chenhonghe2021** [comment]
> > > http://[2409:8087:1a01:df::7005]:80/ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226559/index.m3u8 用这个试一下
> > 
> > 
> > 这个是 hevc 格式，老版本是不支持的，最新 beta 兼容部分 hevc(h265)不能保证完全可用，可以尝试调用系统播放器
> 
> 调用系统播放器，就没成功过，不知道是不是我设置问题。
> 
> 比如环境win11，播放器VLC： C:\Program Files\VideoLAN\VLC\vlc.exe
> 
> ![image](https://private-user-images.githubusercontent.com/92646119/350517848-d65be970-e9b0-4063-ad87-e0069cd6ff97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MTQwODYsIm5iZiI6MTcyMTQxMzc4NiwicGF0aCI6Ii85MjY0NjExOS8zNTA1MTc4NDgtZDY1YmU5NzAtZTliMC00MDYzLWFkODctZTAwNjljZDZmZjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDE4Mjk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZjUyMDc2MzlhOTdjOTE2MzFhNzcyZjdiYTU0ZDQ3ZWJiZGJkZThkMTA1ZWFkODNiZjdiNjQ4OGEyY2U5YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s9PZYoE7KUuoJ758DMEzYhhXtVvzDalHWmUhN5MOeP4)
> 
> 同样win11 ，播放器PotPlayer： D:\Program Files\DAUM\PotPlayer\PotPlayerMini64.exe ![image](https://private-user-images.githubusercontent.com/92646119/350518293-82353301-96ab-46f3-b3ba-9047079d9697.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MTQwODYsIm5iZiI6MTcyMTQxMzc4NiwicGF0aCI6Ii85MjY0NjExOS8zNTA1MTgyOTMtODIzNTMzMDEtOTZhYi00NmYzLWIzYmEtOTA0NzA3OWQ5Njk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDE4Mjk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2MjkwOTlhNzhhYjQ0YWRhMDA3YmVjMTM0MTk2OTE2NmYyNGM4MGJlOWI3YmU5MTMxYTM3YTg2MDQ3Y2Q5ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._wKv3tsc1ZoQQWVui7J4HkphCxyjQ1ByLrSbzt9MAMY)
> 
> 结局都是没法成功调用

随意挑选了3个源都是有声音，黑屏幕没画面的

CCTV-1_综合,http://[2409:8087:4c0a:22:1::11]:6410/170000001115/UmaiCHAN111128BESTVSMGSMG/index.m3u8?AuthInfo=9kOOdBn7MFF%2F2bWjKgahUU6FFmRK8Hl0ytyd5e5kWGEwoDIwMxbrlyyVy9x6ZDKnldIYKOjBOUjRyoym5n7Kg0yIYstFTUfqtC14fzxhy5Y
CCTV-2_财经,http://[2409:8087:4c0a:22:1::11]:6410/170000001115/UmaiCHAN5000036BESTVSMGSMG/index.m3u8?AuthInfo=9kOOdBn7MFF%2F2bWjKgahUSpr1AVNI633ampcuzdN%2BfGVSARKsxkWGZw7vFUuOj2QZHeRzosIxVbl7i2QHFATHA3k5wDWG1qHkZQAleNv%2FbI
CCTV-3_综艺,http://[2409:8087:4c0a:22:1::11]:6410/170000001115/UmaiCHAN638727c125355/index.m3u8?AuthInfo=9kOOdBn7MFF%2F2bWjKgahUSPTZ4CK5oLfjaEYe9dogNMUNNEYLCPUtKY62j1Wp5u04wipypKUQ1TTuR2lXvBl5YpHqBJmlA19x22TD9bUOjk

**Comment by chenhonghe2021** [comment]
> > > > http://[2409:8087:1a01:df::7005]:80/ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226559/index.m3u8 用这个试一下
> > > 
> > > 
> > > 这个是 hevc 格式，老版本是不支持的，最新 beta 兼容部分 hevc(h265)不能保证完全可用，可以尝试调用系统播放器
> > 
> > 
> > 调用系统播放器，就没成功过，不知道是不是我设置问题。
> > 比如环境win11，播放器VLC： C:\Program Files\VideoLAN\VLC\vlc.exe
> > ![image](https://private-user-images.githubusercontent.com/92646119/350517848-d65be970-e9b0-4063-ad87-e0069cd6ff97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MTQwODYsIm5iZiI6MTcyMTQxMzc4NiwicGF0aCI6Ii85MjY0NjExOS8zNTA1MTc4NDgtZDY1YmU5NzAtZTliMC00MDYzLWFkODctZTAwNjljZDZmZjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDE4Mjk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZjUyMDc2MzlhOTdjOTE2MzFhNzcyZjdiYTU0ZDQ3ZWJiZGJkZThkMTA1ZWFkODNiZjdiNjQ4OGEyY2U5YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s9PZYoE7KUuoJ758DMEzYhhXtVvzDalHWmUhN5MOeP4)
> > 同样win11 ，播放器PotPlayer： D:\Program Files\DAUM\PotPlayer\PotPlayerMini64.exe ![image](https://private-user-images.githubusercontent.com/92646119/350518293-82353301-96ab-46f3-b3ba-9047079d9697.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MTQwODYsIm5iZiI6MTcyMTQxMzc4NiwicGF0aCI6Ii85MjY0NjExOS8zNTA1MTgyOTMtODIzNTMzMDEtOTZhYi00NmYzLWIzYmEtOTA0NzA3OWQ5Njk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDE4Mjk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2MjkwOTlhNzhhYjQ0YWRhMDA3YmVjMTM0MTk2OTE2NmYyNGM4MGJlOWI3YmU5MTMxYTM3YTg2MDQ3Y2Q5ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._wKv3tsc1ZoQQWVui7J4HkphCxyjQ1ByLrSbzt9MAMY)
> > 结局都是没法成功调用
> 
> 随意挑选了3个源都是有声音，黑屏幕没画面的
> 
> CCTV-1_综合,http://[2409:8087:4c0a:22:1::11]:6410/170000001115/UmaiCHAN111128BESTVSMGSMG/index.m3u8?AuthInfo=9kOOdBn7MFF%2F2bWjKgahUU6FFmRK8Hl0ytyd5e5kWGEwoDIwMxbrlyyVy9x6ZDKnldIYKOjBOUjRyoym5n7Kg0yIYstFTUfqtC14fzxhy5Y CCTV-2_财经,http://[2409:8087:4c0a:22:1::11]:6410/170000001115/UmaiCHAN5000036BESTVSMGSMG/index.m3u8?AuthInfo=9kOOdBn7MFF%2F2bWjKgahUSpr1AVNI633ampcuzdN%2BfGVSARKsxkWGZw7vFUuOj2QZHeRzosIxVbl7i2QHFATHA3k5wDWG1qHkZQAleNv%2FbI CCTV-3_综艺,http://[2409:8087:4c0a:22:1::11]:6410/170000001115/UmaiCHAN638727c125355/index.m3u8?AuthInfo=9kOOdBn7MFF%2F2bWjKgahUSPTZ4CK5oLfjaEYe9dogNMUNNEYLCPUtKY62j1Wp5u04wipypKUQ1TTuR2lXvBl5YpHqBJmlA19x22TD9bUOjk

版本：zyplayer-win-3.3.6-x64

**Comment by chenhonghe2021** [comment]
> > > http://[2409:8087:1a01:df::7005]:80/ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221226559/index.m3u8 用这个试一下
> > 
> > 
> > 这个是 hevc 格式，老版本是不支持的，最新 beta 兼容部分 hevc(h265)不能保证完全可用，可以尝试调用系统播放器
> 
> 调用系统播放器，就没成功过，不知道是不是我设置问题。
> 
> 比如环境win11，播放器VLC： C:\Program Files\VideoLAN\VLC\vlc.exe
> 
> ![image](https://private-user-images.githubusercontent.com/92646119/350517848-d65be970-e9b0-4063-ad87-e0069cd6ff97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MTcwNDUsIm5iZiI6MTcyMTQxNjc0NSwicGF0aCI6Ii85MjY0NjExOS8zNTA1MTc4NDgtZDY1YmU5NzAtZTliMC00MDYzLWFkODctZTAwNjljZDZmZjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDE5MTkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmM2Q3NWI3MGI4Mzg0MDUyOTY4ZjA0ZjgyODQ2ZjFiMzg5M2FhNDJlZjA4ZmYzZjEwYTg1ZWFmZmFiZmYzMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rk0HVZ0D8rNhC4xFPs0pG_DZBhPTn7eweKQZuP7nKyM)
> 
> 同样win11 ，播放器PotPlayer： D:\Program Files\DAUM\PotPlayer\PotPlayerMini64.exe ![image](https://private-user-images.githubusercontent.com/92646119/350518293-82353301-96ab-46f3-b3ba-9047079d9697.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MTcwNDUsIm5iZiI6MTcyMTQxNjc0NSwicGF0aCI6Ii85MjY0NjExOS8zNTA1MTgyOTMtODIzNTMzMDEtOTZhYi00NmYzLWIzYmEtOTA0NzA3OWQ5Njk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDE5MTkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4ODQwNDRiMDhjMjU4MTUwZWRhOGFkYTZmZjhjNzBhODkwYjEwN2ZhMTJkNzAyYTk1NzAxNDQ1Mjg3ODk3OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._2AwkmJEwkG_sBQIrWS77_QhaHjDmDVVWIZ1cOJdjNA)
> 
> 结局都是没法成功调用

指定原因了，因为路径忽略了双引号。其实际就是把软件的**目标**，全抄写就OK（如下图）
![image](https://github.com/user-attachments/assets/6a7c6df5-9fa1-4157-a8e2-6d6241a0b572)
