### ISSUE TITLE
macOS防火墙问题，每次启动应用都提示接受传入网络连接

### ISSUE THREAD

**Issue by cethink** [Hiram-Wong/ZyPlayer#262]
### zyplayer 版本

3.3.6

### 重现步骤

每次重新启动应用就提示接受传入网络连接，已在防火墙中允许
<img width="260" alt="Snipaste_2024-06-19_11-55-11" src="https://github.com/Hiram-Wong/ZyPlayer/assets/756512/4f13d794-ee4a-43ba-bfd1-efa7e54d74e0">

### 系统信息

macOS 14.5 Darwin 23.5.0 Intel

**Comment by Hiram-Wong** [comment]
m1上 macos 14 和 macos15 都没有看到这个问题

**Comment by Hiram-Wong** [comment]
可以把系统防火墙关了

**Comment by cethink** [comment]
清理了重装也是一样的，能不关么

**Comment by Hiram-Wong** [comment]
我 mac 上没发现这个问题诶，尴尬

**Comment by Hiram-Wong** [comment]
麻烦你试试前几个版本有没有这几个问题，还是说就这个版本有问题

**Comment by cethink** [comment]
我从3.2.8开始安装，装到3.3.4没有问题，3.3.5和3.3.6有问题

**Comment by cethink** [comment]
另外好像3.3.6同步盘从云端同步到本地时本地数据没有更新，要重启才会加载各种配置

**Comment by cethink** [comment]
另外自动同步功能在打开和关闭软件时能自动同步吗？

**Comment by cethink** [comment]
另外3.3.6从云端同步到本地时，窗口位置没有勾选

**Comment by cethink** [comment]
另外，一键配置如果填写了无效的源会提示成功，但没有数据

**Comment by Hiram-Wong** [comment]
> 另外，一键配置如果填写了无效的源会提示成功，但没有数据

不属于问题

**Comment by Hiram-Wong** [comment]
> 另外好像3.3.6同步盘从云端同步到本地时本地数据没有更新，要重启才会加载各种配置

左上角有一个刷新按钮

**Comment by cethink** [comment]
那我先用3.3.4😏



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年06月19日 14:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Hiram-Wong/ZyPlayer] macOS防火墙问题，每次启动应用都提示接受传入网络连接 (Issue #262) |

另外好像3.3.6同步盘从云端同步到本地时本地数据没有更新，要重启才会加载各种配置

左上角有一个刷新按钮

**Comment by cethink** [comment]
MacOS下3.3.7每次启动还是有防火墙提示
