### ISSUE TITLE
[电视] 希望在播放列表也能支持频道分类

### ISSUE THREAD

**Issue by zousizhe** [Hiram-Wong/ZyPlayer#265]
### 

在主界面的电视列表是支持列表分类的，但是在播放器右边的列表却不能显示分类，也不是定位到当前频道，现在找频道不是很方便

### 你建议的方案是什么

希望能和主界面的列表处理方式一致

**Comment by Hiram-Wong** [comment]
感谢你的建议，但查阅了大多相关软件，此部分都不会在播放页直接支持搜索，暂不做修改。播放页主要以观看为主不会做过多的逻辑，不然页面会比较卡

**Comment by zousizhe** [comment]
> 感谢你的建议，但查阅了大多相关软件，此部分都不会在播放页直接支持搜索，暂不做修改。播放页主要以观看为主不会做过多的逻辑，不然页面会比较卡

不是搜索，主界面的电视列表会显示，央视，卫视，轮播之类的，底下有二级分类，而在播放器的列表里是全部列表，也不会高亮显示当前所在的频道，要想在这里面切换不太好操作

**Comment by Hiram-Wong** [comment]
> > 感谢你的建议，但查阅了大多相关软件，此部分都不会在播放页直接支持搜索，暂不做修改。播放页主要以观看为主不会做过多的逻辑，不然页面会比较卡
> 
> 不是搜索，主界面的电视列表会显示，央视，卫视，轮播之类的，底下有二级分类，而在播放器的列表里是全部列表，也不会高亮显示当前所在的频道，要想在这里面切换不太好操作

播放中的会高亮的，状态显示的播放中，分类可以考虑

**Comment by Hiram-Wong** [comment]
3.3.8 版本已新增，关闭此 issue
