### ISSUE TITLE
[本地代理]希望支持视频本地代理

### ISSUE THREAD

**Issue by zengge99** [Hiram-Wong/ZyPlayer#268]
### 这个功能解决了什么问题

当前的proxy_rule似乎只能支持图片、m3u8文本等小文件的阻塞式代理。是否可以支持视频文件异步代理？比如夸克，必须要在http头中携带range，否则会限速，所以希望通过JS本地代理修改请求头。

### 你建议的方案是什么

是否可以支持视频文件异步代理？比如夸克，必须要在http头中携带range，否则会限速，所以希望通过JS本地代理修改请求头。

**Comment by Hiram-Wong** [comment]
该软件也不支持网盘丫😵‍💫

**Comment by zengge99** [comment]
可以支持的吧？比如玩偶哥哥，播放链接就是夸克或阿里。

**Comment by Hiram-Wong** [comment]
不支持

**Comment by zengge99** [comment]
谢谢大佬回复
