### ISSUE TITLE
cms播放

### ISSUE THREAD

**Issue by GGreyCat** [Hiram-Wong/ZyPlayer#269]
### zyplayer 版本

3.3. 6  3.3.7

### 重现步骤

https://360zy.com/api.php/provide/vod  
https://www.360jiexi.com/player/?url=
（不止这一个网站）
在3.3.4和3.3.5(播放器设置自动打开30s的不行)版本中可以秒播 但在3.3.6和3.3.7里面就不能播放，不知道是软件问题还是本地环境问题
嗅探失败，请换源

### 系统信息

windows

**Comment by Hiram-Wong** [comment]
秒波啊，

**Comment by GGreyCat** [comment]
我这3.3.7 不行啊
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/60751934/890148be-6327-4212-bef6-ca950cba1a67)

**Comment by Hiram-Wong** [comment]
> 秒波啊，



> 秒波啊，



> 我这3.3.7 不行啊 ![image](https://private-user-images.githubusercontent.com/60751934/343770502-890148be-6327-4212-bef6-ca950cba1a67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTE4MDEsIm5iZiI6MTcxOTQ5MTUwMSwicGF0aCI6Ii82MDc1MTkzNC8zNDM3NzA1MDItODkwMTQ4YmUtNjMyNy00MjEyLWJlZjYtY2E5NTBjYmExYTY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDEyMzE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NjVlZWQxMjY0NDJlMTQyNjJlNjI2ZmNmMDk2NTllMWU5NTU4NzQ0NDQ2OTU3YjU0ZTQ0MDFlMTQ0M2FjMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GigKRqE5os9FUScq8af2Z1ICGT8nSpi__75PAylitAs)

我也是 3.3.37

**Comment by Hiram-Wong** [comment]
<img width="1512" alt="image" src="https://github.com/Hiram-Wong/ZyPlayer/assets/30908279/e151a563-2fc6-45e4-bdc7-5dd3afd1dd21">

**Comment by GGreyCat** [comment]
取消解析确实可以 但我在3.3.4上面是加了解析啊 可以播  为啥3.3.7加了就不行了

**Comment by Hiram-Wong** [comment]
加啥解析，本来就不需要解析

**Comment by Hiram-Wong** [comment]
https://www.360jiexi.com/player/?url=这个只是个播放器，没逼用
