### ISSUE TITLE
【bug 报告】[播放器] 调用内置播放器异常

### ISSUE THREAD

**Issue by hinum009** [Hiram-Wong/ZyPlayer#270]
### zyplayer 版本

3.3.7.0

### 重现步骤

win11 任务栏侧置，更新某些非标源会出现此异常，调用系统播放器正常。调用西瓜/呆呆/艺术/玩家都会抛出此异常

### 报错信息

A JavaScript error occurred in the main process Uncaught Exception:
TypeError: Cannot read properties of undefined (reading 'width)  at createPlay

### 期望结果

打开播放器页面

### 实际结果

抛出异常

### 系统信息

Win11 x64

**Comment by Hiram-Wong** [comment]
win11 任务栏侧置是什么意思，没太理解

**Comment by hinum009** [comment]
> win11 任务栏侧置是什么意思，没太理解

系统任务栏放屏幕左边

**Comment by Hiram-Wong** [comment]
方便截个图吗

**Comment by Hiram-Wong** [comment]
然后怎么样能百分百复现

**Comment by Hiram-Wong** [comment]
这，

**Comment by hinum009** [comment]
> 这，

![image](https://github.com/Hiram-Wong/ZyPlayer/assets/29087287/5fb162c3-7455-43f6-a009-996294ad8feb)
可能是[这里](https://ghproxy.net/https://raw.githubusercontent.com/ls125781003/dmtg/main/zy_yuan.json)的问题，导入的 外部"key": "windowPosition"超限了，导致抛出异常或者闪退

请问配置文件写在哪里在，现在闪退补弹主窗口了，怎么手动删除配置，希望能有个"安全模式"或者“上次正确的配置”功能。

**Comment by Hiram-Wong** [comment]
> > 这，
> 
> ![image](https://private-user-images.githubusercontent.com/29087287/344195795-5fb162c3-7455-43f6-a009-996294ad8feb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2Mzg1NDQsIm5iZiI6MTcxOTYzODI0NCwicGF0aCI6Ii8yOTA4NzI4Ny8zNDQxOTU3OTUtNWZiMTYyYzMtNzQ1NS00M2Y2LWEwMDktOTk2Mjk0YWQ4ZmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDA1MTcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZDQ5NDFkZDg5YWU2NjA2YmI5YzUyOTFjZTgyNjM1ZDIyOGM3ZTFlYTkzODc1NzlmMDU2MmNmMjAwZmM5YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fyVOdQxE01G_zdYilsLVryd4wi7wW2OAqEHBdGsXhmo) 可能是[这里](https://ghproxy.net/https://raw.githubusercontent.com/ls125781003/dmtg/main/zy_yuan.json)的问题，疑似导入的 外部"key": "windowPosition"超限了，配置文件的分辨率比本机的高，导致抛出异常或者闪退
> 
> 请问配置文件写在哪里在，现在闪退补弹主窗口了，怎么手动删除配置，希望能有个"安全模式"或者“上次正确的配置”功能。

不对吧，337的windowPosition结构已经不是这样了，看 readme 里面的格式

**Comment by Hiram-Wong** [comment]
> > > 这，
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/29087287/344195795-5fb162c3-7455-43f6-a009-996294ad8feb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2Mzg1NDQsIm5iZiI6MTcxOTYzODI0NCwicGF0aCI6Ii8yOTA4NzI4Ny8zNDQxOTU3OTUtNWZiMTYyYzMtNzQ1NS00M2Y2LWEwMDktOTk2Mjk0YWQ4ZmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDA1MTcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZDQ5NDFkZDg5YWU2NjA2YmI5YzUyOTFjZTgyNjM1ZDIyOGM3ZTFlYTkzODc1NzlmMDU2MmNmMjAwZmM5YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fyVOdQxE01G_zdYilsLVryd4wi7wW2OAqEHBdGsXhmo) 可能是[这里](https://ghproxy.net/https://raw.githubusercontent.com/ls125781003/dmtg/main/zy_yuan.json)的问题，疑似导入的 外部"key": "windowPosition"超限了，配置文件的分辨率比本机的高，导致抛出异常或者闪退
> > 请问配置文件写在哪里在，现在闪退补弹主窗口了，怎么手动删除配置，希望能有个"安全模式"或者“上次正确的配置”功能。
> 
> 不对吧，337的windowPosition结构已经不是这样了，看 readme 里面的格式

数据文件在
 * on Linux: ~/.config/{app name}/logs/main.log                        ~/.config/zyplayer/logs/main.log
 * on macOS: ~/Library/Logs/{app name}/main.log                        ~/Library/Logs/zyplayer/main.log
 * on Windows: %USERPROFILE%\AppData\Roaming\{app name}\logs\main.log  %USERPROFILE%\AppData\Roaming\zyplayer\logs\main.log
 
 里面有个数据库文件直接改就行，先关软件在修改

**Comment by chenhonghe2021** [comment]
> ### zyplayer 版本
> 3.3.7.0
> 
> ### 重现步骤
> win11 任务栏侧置，更新某些非标源会出现此异常，调用系统播放器正常。调用西瓜/呆呆/艺术/玩家都会抛出此异常
> 
> ### 报错信息
> A JavaScript error occurred in the main process Uncaught Exception: TypeError: Cannot read properties of undefined (reading 'width) at createPlay
> 
> ### 期望结果
> 打开播放器页面
> 
> ### 实际结果
> 抛出异常
> 
> ### 系统信息
> Win11 x64
> 
> ### 补充说明
> _No response_

请问是怎么设置调用系统播放器呢，按照说明提示填写的电脑播放器路径，我的在怎么就没成功过呢~~（系统环境win11）

**Comment by chenhonghe2021** [comment]
> > ### zyplayer 版本
> > 3.3.7.0
> > ### 重现步骤
> > win11 任务栏侧置，更新某些非标源会出现此异常，调用系统播放器正常。调用西瓜/呆呆/艺术/玩家都会抛出此异常
> > ### 报错信息
> > A JavaScript error occurred in the main process Uncaught Exception: TypeError: Cannot read properties of undefined (reading 'width) at createPlay
> > ### 期望结果
> > 打开播放器页面
> > ### 实际结果
> > 抛出异常
> > ### 系统信息
> > Win11 x64
> > ### 补充说明
> > _No response_
> 
> 请问是怎么设置调用系统播放器呢，按照说明提示填写的电脑播放器路径，我的在怎么就没成功过呢~~（系统环境win11）

o(╥﹏╥)o知道了原因：路径要加上英文状态的双引号~~
