### ISSUE TITLE
[影视配置] 关于检测 数据配置不更新保存

### ISSUE THREAD

**Issue by GGreyCat** [Hiram-Wong/ZyPlayer#271]
### 这个功能解决了什么问题

不搞js源之后 回归cms发现 没有一键检测好麻烦   哪个源失效了都不知道 返回影视主界面 失效的源都显示在上面 太影响体验了
如果手动一个一个的检测  检测完一刷新又不行了 状态不能保存 做无用功啊

### 你建议的方案是什么

时时保存配置文件

**Comment by Hiram-Wong** [comment]
支持保存状态啊，如果不能保存只能说明你的数据结构没有按照要求导致的

**Comment by GGreyCat** [comment]
噢 低版本配置导入高版本再导出来 确实好了
