### ISSUE TITLE
[随心看] 增加源管理 滚动切换视频

### ISSUE THREAD

**Issue by GGreyCat** [Hiram-Wong/ZyPlayer#272]
### 这个功能解决了什么问题

能否可以像手机上 永恒国度 里面的随性看 添加源管理  
能否实现鼠标滚轮滑动下个视频

### 你建议的方案是什么

能否可以像手机上 永恒国度 里面的随性看 添加源管理  
能否实现鼠标滚轮滑动下个视频

**Comment by Hiram-Wong** [comment]
查阅大量资料和实践，该方案不理想，一次鼠标中间滚轮滚动会触发上百个事件

**Comment by GGreyCat** [comment]
那使用鼠标滑动呢

**Comment by Hiram-Wong** [comment]
鼠标滑动直接触发不符合逻辑
