### ISSUE TITLE
[求助]如何记住播放速度？

### ISSUE THREAD

**Issue by hinum009** [Hiram-Wong/ZyPlayer#278]
找了一圈没有找到相关功能，切集以后变速就失效了

**Comment by Hiram-Wong** [comment]
最新版本已经优化过了，老版本请更新

**Comment by hinum009** [comment]
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/29087287/3b71f6ec-c7ae-41ab-8ba5-5ef5101d9f5f)

**Comment by Hiram-Wong** [comment]
使用艺术播放器

**Comment by hinum009** [comment]
> 使用艺术播放器

ok，解决
