### ISSUE TITLE
[bug反馈]呆呆播放器不能记住倍速，艺术播放器不能跳过片头

### ISSUE THREAD

**Issue by hinum009** [Hiram-Wong/ZyPlayer#279]
呆呆播放器不能记住倍速，可以跳过片头片尾
艺术播放器不能跳过片头（可以跳过片尾），预加载下一集似乎也无效

西瓜播放器支持格式太少，兼容性差
玩家播放器用的少，还在尝试。可以跳过片头片尾，但是不能记住倍速。
相关议题https://github.com/Hiram-Wong/ZyPlayer/issues/278

**Comment by Hiram-Wong** [comment]
呆呆播放器不能记住倍速正常，没有 cookie 存储

**Comment by Hiram-Wong** [comment]
艺术播放器测试没问题的，这个我试过

**Comment by hinum009** [comment]
> 艺术播放器测试没问题的，这个我试过

艺术播放器很不稳定，记住倍速/跳过片头会随机失效，跳过片尾功能稳定，预加载下一集功能未知。
![24-06-29_223319](https://github.com/Hiram-Wong/ZyPlayer/assets/29087287/77e99d3c-8482-4333-a9cd-7ed910e1e9ac)

**Comment by hinum009** [comment]
又换其他节目试了试，艺术播放器 记住倍速/跳过片头  两个功能有冲突，不能同时生效

**Comment by Hiram-Wong** [comment]
倍速我大概知道什么问题了，和 dp 播放器一样没有记忆功能的，应该是走切换的情况下应该是还是原来的倍速，摧毁重建的情况就不记忆了

**Comment by Hiram-Wong** [comment]
倍速问题方案重构
使用这个试试，艺术播放器 ui 显示倍速可能有问题实际是生效的，已反馈播放器作者待改进
https://github.com/Hiram-Wong/ZyPlayer/actions/runs/9747587480
