### ISSUE TITLE
有个BUG，站点源都删除后，无法从文件中导入

### ISSUE THREAD

**Issue by 13174771** [Hiram-Wong/ZyPlayer#28]
我把站点源都删除了，从备份的Json文件中导入，导入不进去，还是没有，并且软件启动的时候设置开始无法进入，后来很长时间才进去！

**Comment by 13174771** [comment]
进入设置要点下刷新才可以！

**Comment by Hiram-Wong** [comment]
没有复现

**Comment by Hiram-Wong** [comment]
> > 没有复现
> 
> 
> 
> 站点源都删除了，在从本地备份的Json文件导入，能导入进去吗？我试了几次都不行。从远程接口地址可以导入

能否提供下你的备份文件，或者怎么联系你远程看下

**Comment by 13174771** [comment]
[sites.zip](https://github.com/Hiram-Wong/ZyPlayer/files/11642064/sites.zip)
就这个导出来的站源文件，在本地就导不进去了

**Comment by Hiram-Wong** [comment]
> [sites.zip](https://github.com/Hiram-Wong/ZyPlayer/files/11642064/sites.zip) 就这个导出来的站源文件，在本地就导不进去了

第 1098 行结尾多了一个逗号导致不是 json 文件哦，同时我看这个源里面格式都没有按照 readme 格式，注意修改

**Comment by 13174771** [comment]
> > [sites.zip](https://github.com/Hiram-Wong/ZyPlayer/files/11642064/sites.zip) 就这个导出来的站源文件，在本地就导不进去了
> 
> 第 1098 行结尾多了一个逗号导致不是 json 文件哦，同时我看这个源里面格式都没有按照 readme 格式，注意修改

哦好的，谢谢大佬！！！
