### ISSUE TITLE
搜索内容取消按钮 与 搜索按钮重叠

### ISSUE THREAD

**Issue by GGreyCat** [Hiram-Wong/ZyPlayer#282]
### 这个功能解决了什么问题

方便鼠标点击搜索

### 你建议的方案是什么

![image](https://github.com/Hiram-Wong/ZyPlayer/assets/60751934/80401679-e00f-42e5-a174-56bf023946f6)
取消按钮与搜索按钮重叠   应该紧跟搜索内容后面

**Comment by Hiram-Wong** [comment]
腾讯ui 组件涉及如此，本来的逻辑就是回车搜索，不予以采纳，不影响使用，
