### ISSUE TITLE
[搜索] 源太多解决选择困难症

### ISSUE THREAD

**Issue by GGreyCat** [Hiram-Wong/ZyPlayer#283]
### 这个功能解决了什么问题

减少左侧源的显示 又不让其失去源的作用    在原配置里面对源做仅搜索设置 让源处于启用状态又不在主界面源列表显示

### 你建议的方案是什么

在原配置里面对源做仅搜索设置 让源处于启用状态又不在主界面源列表显示

希望能采纳

**Comment by wanpinhuan** [comment]
应该是可以实现隐藏源名称的，你这么多源私下分享一下撒。
