### ISSUE TITLE
[搜索结果] 模糊搜索与精确搜索

### ISSUE THREAD

**Issue by GGreyCat** [Hiram-Wong/ZyPlayer#284]
### 这个功能解决了什么问题

模糊就不用说了  精确搜索让搜索结果符合期望要求

### 你建议的方案是什么

那精确搜索 在搜索显示的结果上再与搜索内容进行匹配 屏蔽掉那些一点不相关的结果

**Comment by Hiram-Wong** [comment]
爱优腾都没有精确搜索的说法，大厂都做不到

**Comment by Hiram-Wong** [comment]
不相关的结果是源返回的，这种多半建议直接屏蔽这个的源搜索

**Comment by Hiram-Wong** [comment]
> 不相关的结果是源返回的，这种源一般不支持搜索，这种多半建议直接屏蔽这个的源搜索

**Comment by GGreyCat** [comment]
一个一个屏蔽不现实啊 还怕屏蔽掉不该屏蔽的

**Comment by Hiram-Wong** [comment]
你这种需求根本不可控，数据不在自己手上

**Comment by GGreyCat** [comment]
我的建议是对返回结果通过代码匹配名称不让他显示啊 这应该能实现啊

**Comment by Hiram-Wong** [comment]
要么就是这个原不支持搜索乱返回的直接关闭这个源的搜索，针对单独一两个数据不准确根本可以忽略不计，没必要做专项过滤

**Comment by Hiram-Wong** [comment]
做过滤的代价主程序卡死，多并发源获取数据后过滤大批量数据假死

**Comment by Hiram-Wong** [comment]
js 是单线程，没有多线程概念

**Comment by GGreyCat** [comment]
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/60751934/df55fa40-5f31-4aae-8042-8bbead047765)
这结果数据不是显示到手了吗 就这也没多少数据吧

**Comment by GGreyCat** [comment]
不太懂

**Comment by GGreyCat** [comment]
你看百度资源里面有要的内容也有不要的  这要是把源屏蔽掉不现实啊

**Comment by GGreyCat** [comment]
> 爱优腾都没有精确搜索的说法，大厂都做不到

这个应该不是做不到 可能是不想这么做 人家为了盈利啊  就算人家没有这个视频 也要推荐你去看相关的 要是搜索出来没有 这不影响用户对网站的印象吗 就算有这个视频 也得推荐相关内容 增加播放啊 万一有喜欢的相关视频呢

**Comment by jahem** [comment]
不现实，单源做过滤可以做到，单大多都全源，全源必卡可线程堵塞
