### ISSUE TITLE
[H5Player] 增强型播放器，主要支持亮度，对比度伽马调节，音轨对齐，和生成式双语字幕

### ISSUE THREAD

**Issue by hinum009** [Hiram-Wong/ZyPlayer#286]
### 这个功能解决了什么问题

调用potplayer/mplayer等本地播放器没法回调zyplayer，导致就不能自动下一集。

### 你建议的方案是什么

是不是可以通过开放油猴接口曲线救国
https://github.com/xxxily/h5player
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/29087287/f5a776dd-65bd-4030-8841-db818e28adbd)

https://github.com/immersive-translate/immersive-translate/
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/29087287/756e3491-93e2-4b15-ac7f-5c6b457c6b58)

或者彻底解决
1增加zyplayer的api，比如zyplayer://这样的协议，可以由potplayer等第三方播放器直接调用
2生成全剧播放列表，不过因为三方源的反盗链和时效性问题，可能需要专有格式，每一集都通过zyplayer解析然后通过临时直链呼出本地播放器。

**Comment by jahem** [comment]
potplayer应该是没提供多链接播放的调起api的，功能应该不能实现

**Comment by hinum009** [comment]
> potplayer应该是没提供多链接播放的调起api的，功能应该不能实现

zyplayer是有本地服务的，可不可以通过本地推流实现呢，播放逻辑操作还是在zyp这边，通过DLNA或者其他投屏协议发送到pp，这样就可以实现进度条拖动和上下集切换。

**Comment by jahem** [comment]
> > potplayer应该是没提供多链接播放的调起api的，功能应该不能实现
> 
> zyplayer是有本地服务的，可不可以通过本地推流实现呢，播放逻辑操作还是在zyp这边，通过DLNA或者其他投屏协议发送到pp，这样就可以实现进度条拖动和上下集切换。

好久没看源代码了，之前使用pp，调用的是pp的调起协议，播放地址作为参数带过去，没看到pp有提供可以调起并构建列表，或许可以生成复制数据，用\n分割，手动去pp复制播放

**Comment by Hiram-Wong** [comment]
> > > potplayer应该是没提供多链接播放的调起api的，功能应该不能实现
> 
> > 
> 
> > zyplayer是有本地服务的，可不可以通过本地推流实现呢，播放逻辑操作还是在zyp这边，通过DLNA或者其他投屏协议发送到pp，这样就可以实现进度条拖动和上下集切换。
> 
> 
>
> 好久没看源代码了，之前使用pp，调用的是pp的调起协议，播放地址作为参数带过去，没看到pp有提供可以调起并构建列表，或许可以生成复制数据，用\n分割，手动去pp复制播放
> 
> 

不现实，当这个源需要嗅探，哪怕有十几集，你光嗅探时间就不少时间，还有失败的情况

**Comment by Hiram-Wong** [comment]
而且如果不同播放器存在传参不同格式，这种情况是兼容不完的

**Comment by Hiram-Wong** [comment]
这个是需要开通 pro 会员才能显示双语没，我似乎几个视频网站都不显示
该插件的双语字幕应该是翻译出来的，这样的话还要在加入翻译接口比较麻烦
