### ISSUE TITLE
[cms源] 是否可以添加屏蔽分类

### ISSUE THREAD

**Issue by GGreyCat** [Hiram-Wong/ZyPlayer#288]
### 这个功能解决了什么问题

大多数源仅有几个分类是空的，要按现在方式需要把其他分类都填上太麻烦，能不能只填写没内容的分类，毕竟大多数都是 电影 电视剧分类是空的，这样的源下面的小分类会很多 

### 你建议的方案是什么

添加屏蔽分类  或者 把现有的分类 改成屏蔽
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/60751934/a69cd156-d707-4d20-a622-97128f5e2656)

**Comment by jahem** [comment]
屏蔽主分类

**Comment by Hiram-Wong** [comment]
该提示词可优化，下个版本改进
