### ISSUE TITLE
[软件启动] WIN10蓝屏后进不去了

### ISSUE THREAD

**Issue by murazi** [Hiram-Wong/ZyPlayer#289]
### zyplayer 版本

不知道具体版本，3以上，软件里找不到哪里看版本

### 重现步骤

不行，试了几次都进不去了

### 报错信息

![image](https://github.com/Hiram-Wong/ZyPlayer/assets/4424520/49620aa5-27a3-4e35-847d-62b9da37faa8)

### 期望结果

不报错

### 实际结果

报错

### 系统信息

windows 10

### 补充说明

正在看剧，突然电脑蓝屏，重新启动后就报错无法进入了
覆盖安装也不行了

**Comment by Hiram-Wong** [comment]
数据库损坏了，删除图上显示那个路径的文件
