### ISSUE TITLE
[播放器]是否可以无感切换不刷新全局页面

### ISSUE THREAD

**Issue by hinum009** [Hiram-Wong/ZyPlayer#290]
不全局重加载，只切换地址
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/29087287/217ba3ed-c55f-49f5-b5ef-3d2e3e45bdf2)
另外 能不能在暂停按钮边上加个下一集

**Comment by Hiram-Wong** [comment]
做不了

**Comment by Hiram-Wong** [comment]
下一集需要传入完整的播放列表，即使是当前线路，嗅探全部列表，你电脑都直接冒烟了
