### ISSUE TITLE
应用无法打开

### ISSUE THREAD

**Issue by Hiram-Wong** [Hiram-Wong/ZyPlayer#296]
请问这个问题最后如何解决的？我也遇到了类似问题……双击打不开，zyplayer.exe 进程出现一下然后就消失了。托盘里也没有任何图标

_Originally posted by @WaterCalm in https://github.com/Hiram-Wong/ZyPlayer/issues/175#issuecomment-2227208098_

**Comment by Hiram-Wong** [comment]
@WaterCalm 提供操作系统版本，芯片架构，软件版本

**Comment by WaterCalm** [comment]
操作系统版本： Windows 11 专业工作站版 23H2
芯片架构：x64  Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz   3.70 GHz
软件版本：3.3.6

**Comment by Hiram-Wong** [comment]
有装什么杀毒软件吗

**Comment by WaterCalm** [comment]
只装了火绒，版本是5.0.75.8

**Comment by Hiram-Wong** [comment]
先把火绒关了，重新安装下软件试试

**Comment by WaterCalm** [comment]
重启了下电脑……又好了……谢谢
