### ISSUE TITLE
MacBook M1 系统12.0.1 (21A559) 安装3.3.5以上版本提示安装文件损坏无法安装

### ISSUE THREAD

**Issue by geyaowei** [Hiram-Wong/ZyPlayer#299]
### zyplayer 版本

3.3.5及以上

### 重现步骤

MacBook M1 系统12.0.1 (21A559) 安装3.3.5以上版本提示安装文件损坏无法安装

### 报错信息

提示安装文件损坏

### 期望结果

可以正常安装

**Comment by Hiram-Wong** [comment]
请详细阅读首页 Readme-macOS 安装问题解决方案，已做说明谢谢。
