### ISSUE TITLE
第二步软件优化问题。

### ISSUE THREAD

**Issue by SONGjiemo** [Hiram-Wong/ZyPlayer#3]
![image](https://user-images.githubusercontent.com/46627639/224610217-c48d624a-5e8c-466e-8c0c-6a1842dd43fc.png)
打开之后，仍然有部分的视频播放存在问题。
![image](https://user-images.githubusercontent.com/46627639/224610307-bd5c0407-c706-4678-bf31-fc506362c084.png)
点击复制地址后应该有一个颜色的变化或者提示复制成功。同时我还发现了一个问题，就是用浏览器打开该地址后，却可以完美的播放。并且经过我多番测试，我发现用浏览器复制该地址似乎永远都可以播放。没有失败过。
![image](https://user-images.githubusercontent.com/46627639/224610694-b4ce2f56-6007-4e52-b5cf-907dbd475428.png)
用户添加源之后，可以。进行提示，大概3秒钟的请用户选择默认的播放源。
然后就是提示完成之后自动刷新当前页面，也就是相当于用户手动的点击了那个刷新的按钮。
![image](https://user-images.githubusercontent.com/46627639/224611060-abbf22a5-1818-436f-ac15-16083de23cc4.png)

目前的跳过片头片尾的设计方法，不是在设置里面进行设置。而是在播放页面放两个按钮，一个按钮是片头，另外一个按钮是片尾。
操作步骤如下。
    第一步。当播放视频的时候，播放到刚刚片头广告结束，用户点击第一个按钮，记住广告的最后时间点。
    第二步。当电视剧播放结束时候，开始了片尾的广告。此时用户点击第二个按钮。记住即将播放片尾广告的时间点。
   第三步操作了。并记住了片头片尾的广告时间点后，那么同一个连续剧下，它就会自动的跳过片头片尾。
   好果。这个时候退出了当前的连续剧下去播放其他的视频，那么就重复第一步第二步，这样去操作就可以了。嗯。查。

**Comment by itscolor** [comment]
支持，期待更多人加入
