### ISSUE TITLE
[解析] 影视配置的接口编辑里的解析框里添加解析接口还是不能用那个接口解析

### ISSUE THREAD

**Issue by CatBoxs** [Hiram-Wong/ZyPlayer#301]
### zyplayer 版本

3.3.6

### 重现步骤

点击影视配置，点击配置的任意一个接口，点击编辑，在解析里填写解析接口，返会播放后没有调用这个接口进行解析

### 报错信息

无报错

### 期望结果

调用配置的解析即可

### 实际结果

你应该懂我的意思吧，大佬

### 系统信息

win11

**Comment by CatBoxs** [comment]
3.3.7测试版也有这个问题哦

**Comment by Hiram-Wong** [comment]
请添加标识
<img width="1000" alt="image" src="https://github.com/user-attachments/assets/46cc99e6-b52b-406d-941c-76c218b171f0">

**Comment by QQ2661136929** [comment]
![4219F65B49CA5FB82618551C2486BB05](https://github.com/user-attachments/assets/17e1287c-a7e7-4056-b301-f9a01ddb4929)
是这个配置了之后他不会调用这个进行解析，识别也都配置了的

**Comment by Hiram-Wong** [comment]
把每个配置项信息发到我的邮箱看下 hiram@catni.cn
