### ISSUE TITLE
影视菜单显示空白

### ISSUE THREAD

**Issue by hereTac** [Hiram-Wong/ZyPlayer#304]
### zyplayer 版本

3.3.6 amd deb

### 重现步骤

配置 t4
源：https://raw.liucn.cc/box/libs/js/drpy2.min.js
检测 9999 正常

### 报错信息

回到影视菜单，点击上述添加的，显示空白

### 系统信息

linux deb

**Comment by Hiram-Wong** [comment]
哥们 t4 配置地址怎么可能是库的地址
