### ISSUE TITLE
[Linux安装编译问题] 用Arch Linux安装ZyPlayer-bin有些疑惑

### ISSUE THREAD

**Issue by wkr111** [Hiram-Wong/ZyPlayer#305]
### 这个功能解决了什么问题

![图片](https://github.com/user-attachments/assets/e447fc9a-efc5-4573-bd76-77b207ba8bc4)

不是哥们，最近这次更新版本，我用Arch Linux安装ZyPlayer-bin，你在ZyPlayer.sh文件里写了啥，下载完整的.deb安装包，还要我下载整个Chromium仓库以及第三方组件源代码，重新构建一遍，下载50G了还没下载完。上一个版本只叫我构建Electron我觉得还能接受，但我也是第一次见*-bin软件版本还要编译源代码。别人的*-bin软件都是打包好的，不同格式的软件包只需要重新打包.pacman就能在Arch Linux上用了。

### 你建议的方案是什么

……

**Comment by Hiram-Wong** [comment]
这看起来是electron的Chrome依赖，不是有变异好的版本吗不能用吗

**Comment by Hiram-Wong** [comment]
编译也不需要拉去github仓库，只拉的npm仓库。我不明白其中的逻辑
