### ISSUE TITLE
能否增加现在”影视仓“和”FM猫影视“都有的AI去广告功能？

### ISSUE THREAD

**Issue by arlingus** [Hiram-Wong/ZyPlayer#306]
### 这个功能解决了什么问题

自动去除视频源中的广告，”影视仓“和”FM猫影视“现在都具有AI去广告功能，播放站点视频基本没有广告了

### 你建议的方案是什么

增加AI去广告功能

**Comment by Hiram-Wong** [comment]
早有了，上上个版本就有了

**Comment by arlingus** [comment]
同样的片源，”影视仓“和”FM猫影视“都去除的广告，zyplayer依然存在，去广告逻辑缺陷？
















在 2024-07-31 10:22:38，"Hiram·Wong" ***@***.***> 写道：

早有了，上上个版本就有了

**Comment by Hiram-Wong** [comment]
算法只能针对部分
