### ISSUE TITLE
可否默认增加一个默认站点页面”豆瓣推荐“

### ISSUE THREAD

**Issue by arlingus** [Hiram-Wong/ZyPlayer#307]
### 这个功能解决了什么问题

可否默认增加一个默认站点页面”豆瓣推荐“，这个页面基本是各个TVBOX站点源的标配，例如”“饭太硬”喵影视“的源，对于观影很有帮助

### 你建议的方案是什么

增加一个默认站点页面”豆瓣推荐“

**Comment by Hiram-Wong** [comment]
没必要，热搜列表就有豆瓣推荐数据

**Comment by arlingus** [comment]
豆瓣推荐的意义是剧荒找片，比如TOP250 ，比如高分电影推荐。这个跟热播没什么关系
















在 2024-07-31 10:25:37，"Hiram·Wong" ***@***.***> 写道：

没必要，热搜列表就有豆瓣推荐数据

**Comment by Hiram-Wong** [comment]
不做，这没任何实际意义

**Comment by arlingus** [comment]
这是排名第一的用户需求！为什么会觉得没意义？真的不太理解，能看到影片评分是最基本的用户需要。这里只提个建议，做不做你是老大。

提醒你的是每个人都在转向使用具有豆瓣评分和推荐的源，都在转向使用具有这个功能的软件！我还是继续使用我的喵影视WINDOWS版吧，GOOD LUCK！













在 2024-07-31 10:48:10，"Hiram·Wong" ***@***.***> 写道：

不做，这没任何实际意义

**Comment by Hiram-Wong** [comment]
首先你希望用什么软件是你权利，哪个好用就用哪个就好了，并没有没强迫你一定要用 xxx
我当然知道你说的这些软件都是用的豆瓣作为首页，既然是排名第一的用户需求，为什么其他用户没有提，从我接手这个软件一年半了，没有用户反馈过这个问题。
我了解到的大部分用户都是上来直接选择一个源直接点开他的推荐数据，还有一部分是根据热搜推荐。
