### ISSUE TITLE
换源之后播放就一直出现A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by iarjian** [Hiram-Wong/ZyPlayer#310]
### zyplayer 版本

3.3.7

### 重现步骤

换源之后播放就一直出现A JavaScript error occurred in the main process
![1722742640588](https://github.com/user-attachments/assets/8b9d2570-d255-42af-b725-f9f0b714340e)

**Comment by Hiram-Wong** [comment]
说明你的数据库里数据又脏数据，请严格参照readme中的数据格式说明

**Comment by iarjian** [comment]
> 说明你的数据库里数据又脏数据，请严格参照readme中的数据格式说明

但是卸载重装之后，或者清除缓存依然无效，降级到3.3.6之后源是可以用的
源是github上找的
https://raw.githubusercontent.com/lxhfans/zyplayer/main/config_v3.json

**Comment by Hiram-Wong** [comment]
因为有一个参数在 3.7 做的变更

**Comment by Hiram-Wong** [comment]
你可以把这个文件下载下来后，删除这个数据,
    {
      "key": "windowPosition",
      "value": {
        "status": true,
        "position": {
          "x": 37,
          "y": 216,
          "width": 1000,
          "height": 640
        }
      },
      "id": "f8c3529b-7880-4f2f-b048-729335a1fd27"
    }
    重置软件后重新导入

**Comment by iarjian** [comment]
删掉之后能用了 感谢
