### ISSUE TITLE
播放电影或视频的时候，列表页点击出现异常

### ISSUE THREAD

**Issue by CloverAn** [Hiram-Wong/ZyPlayer#312]
### zyplayer 版本

最新版本

### 重现步骤

![image](https://github.com/user-attachments/assets/d699a414-d065-48e2-bb27-09984b190169)

### 报错信息

![image](https://github.com/user-attachments/assets/0641d43b-d55a-4498-9d0e-7a698ec5b8fe)

### 系统信息

Win10家庭版22H2 - 19045.4651

**Comment by Hiram-Wong** [comment]
不是bug不是bug不是bug
因为你们数据格式没按照readme要求

**Comment by Hiram-Wong** [comment]
参考issue#310

**Comment by CloverAn** [comment]
昂   这个应该要向下兼容哇。。。已经解决了。
