### ISSUE TITLE
网盘功能存在bug

### ISSUE THREAD

**Issue by CloverAn** [Hiram-Wong/ZyPlayer#314]
### zyplayer 版本

最新版本

### 重现步骤

![recording](https://github.com/user-attachments/assets/8032045f-070a-4ca8-b296-9090be747a91)

### 报错信息

无报错信息，但页面内容不正确。详见gif

### 系统信息

Win10家庭版22H2 - 19045.4651

**Comment by Hiram-Wong** [comment]
已更新，关闭此 issue
