### ISSUE TITLE
添加视频源后无法解析

### ISSUE THREAD

**Issue by xiaranyueming** [Hiram-Wong/ZyPlayer#315]
### zyplayer 版本

3.3.7

### 重现步骤

在设置的影视配置添加视频源如：https://[download.kstore.space/download/2883/nzk/nzk0722.json](https://download.kstore.space/download/2883/nzk/nzk0722.json)，但是无法解析

**Comment by Hiram-Wong** [comment]
这个是纯 tvbox 接口，zy 不适配

**Comment by xiaranyueming** [comment]
那该使用什么样的接口，有什么推荐嘛



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月14日(周三) 下午3:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hiram-Wong/ZyPlayer] 添加视频源后无法解析 (Issue #315)




 
这个是纯 tvbox 接口，zy 不适配
