### ISSUE TITLE
抓取线路问题

### ISSUE THREAD

**Issue by raychn** [Hiram-Wong/ZyPlayer#316]
### zyplayer 版本

337

### 重现步骤

![2024-08-17_111214](https://github.com/user-attachments/assets/8acafb97-862a-4196-a757-b946817a41ab)
https://www.yjys02.com/
这个线路在播放器，请教怎么抓取呢

**Comment by Hiram-Wong** [comment]
说下大致思路
1. 会请求这个地址获取到线路[f12 刷新后可以看到] https://www.yjys02.com/lines
2.这个请求里data 有5 个对象，tos和ptoken可以直接过滤掉（有能力的话可以继续挖），每个线路以,分隔，线路名以#分隔
3.可以使用js 写源的lazy中实现

**Comment by Hiram-Wong** [comment]
写源问题 请前往Discussions #318 讨论
此帖关闭

**Comment by raychn** [comment]
你好，对JS不懂，想学一下，但是不会调试JS。
 还有个问题在写源里面测试都成功，包括调试。但是加进影视配置里面，个别会显示分类异常或者打开播放器嗅探失败。但是在写源里面分类没问题，也能嗅探到地址。



***@***.***
 
发件人： Hiram-Wong
发送时间： 2024-08-19 18:38
收件人： Hiram-Wong/ZyPlayer
抄送： raychn; Author
主题： Re: [Hiram-Wong/ZyPlayer] 抓取线路问题 (Issue #316)
说下大致思路
1.会请求这个地址获取到线路[f12 刷新后可以看到] https://www.yjys02.com/lines
2.这个请求里data 有5 个对象，tos和ptoken可以直接过滤掉（有能力的话可以继续挖），每个线路以,分隔，线路名以#分隔
3.可以使用js 写源的lazy中实现

**Comment by Hiram-Wong** [comment]
个别可能是正常的，网络不稳定或者结构不对应导致的
