### ISSUE TITLE
[安装问题] zyplayer-win-3.3.7.exe下载后双击无反应，右键选择“以管理员身份运行”也无反应

### ISSUE THREAD

**Issue by JohnFantasy** [Hiram-Wong/ZyPlayer#317]
### zyplayer 版本

zyplayer-win-3.3.7.exe

### 重现步骤

1、下载软件3.3.7安装包（win X64版本 或win版本）
2、运行安装程序
3、无反应。。。

### 报错信息

无

### 期望结果

能正常安装

### 系统信息

Windows 11 最新版

### 补充说明

以管理员身份运行安装程序，也无反应

**Comment by Hiram-Wong** [comment]
卸载后重启电脑 关闭杀毒软件 重新装

**Comment by Hiram-Wong** [comment]
可以了吗

**Comment by JohnFantasy** [comment]
我电脑除了win11自带的defender未安装任何杀毒软件。

**Comment by Hiram-Wong** [comment]
可以远程吗

**Comment by JohnFantasy** [comment]
还没睡啊，是不是因为我安装了原版的ZY Player 2.8.8版本？
可以远程，如何联系？用什么软件？

**Comment by Hiram-Wong** [comment]
向日葵或者 todesk 都可以

**Comment by JohnFantasy** [comment]
todesk  老范儿邀请您进行远程控制
ToDesk设备代码:153 501 614
临时密码:x32dxzu8
点击链接直接进行远程控制：
https://wechat.todesk.com/invite-page?id=uu-UPL6TyNO6fceWqmwn9

**Comment by CatBoxs** [comment]
大佬，能做一下tvbox源的适配吗，我tvbox源在手机和电视盒子都可以用，导入到ZyPlayer就都不能用了

**Comment by CatBoxs** [comment]
还有调用解析好像都很慢，能像tvbox那样直接匹配到playURL的链接进行解析吧

**Comment by Hiram-Wong** [comment]
> 大佬，能做一下tvbox源的适配吗，我tvbox源在手机和电视盒子都可以用，导入到ZyPlayer就都不能用了

已经适配 drpy 源和 xbpq，pg 包适配不了，因为 pc 加载不了安卓依赖

**Comment by Hiram-Wong** [comment]
> playURL

慢不慢取决于解析，支持两种原里带playURL直接解析需要 json 格式，还一种是整体解析需要嗅探

**Comment by daiyang94815** [comment]
同不行，是不是没有适配win11呀？

**Comment by CatBoxs** [comment]
大佬，能做一个刷新拉取接口按钮吗（每次刷新就重新拉取一次接口），要不然有些源失效了，重新导入接口（不便于接口更新），播放记录那些就会失效，还有能做一下网盘资源的适配吗，像玩偶哥哥，多多影音等，配置上去无法播放，也不能扫码推送tk和ck

**Comment by freefly22** [comment]
最后怎么解决的？win11同样问题

**Comment by CatBoxs** [comment]
没办法，现在作者不更新了

**Comment by Hiram-Wong** [comment]
> 大佬，能做一个刷新拉取接口按钮吗（每次刷新就重新拉取一次接口），要不然有些源失效了，重新导入接口（不便于接口更新），播放记录那些就会失效，还有能做一下网盘资源的适配吗，像玩偶哥哥，多多影音等，配置上去无法播放，也不能扫码推送tk和ck

做不了，能力有限，而且网盘这玩意受限于网盘，法律风险过大且限速
