### ISSUE TITLE
聚合搜索时出现搜索电视剧名称和实际显示名称不匹配的问题

### ISSUE THREAD

**Issue by ldqqq11** [Hiram-Wong/ZyPlayer#319]
### zyplayer 版本

3.3.6

### 重现步骤

每次搜索电视剧或者电影时，都会只出现某**一两个源**的该电视剧，然后出现其他和搜索标题**完全不相干的内容**，其他源的搜索结果往往放在最后面。
![image](https://github.com/user-attachments/assets/3c489aaa-57c4-4de9-bbad-1f781f1b2017)
![image](https://github.com/user-attachments/assets/b47f8896-963c-4352-aa29-a30de62d4b47)
如上图所示，搜索【唐朝诡事录】，没有把我要的**所有源中标题相同**的电视剧展示出来，反而扰乱我想换源的操作。
希望能够将和**搜索结果相同的所有源**内容展示在一起，去掉**完全不相干的内容**。

### 系统信息

Windows11

**Comment by Hiram-Wong** [comment]
这不是软件的问题，是源不支持搜索或者乱返回导致的。
这部分逻辑在 337 版本中了加了一个筛选过滤开关，开启会过滤掉没包含搜索关键词的结果
