### ISSUE TITLE
怎么设置站点源，直播源，解析源呀

### ISSUE THREAD

**Issue by bianningtao** [Hiram-Wong/ZyPlayer#32]
怎么设置站点源，直播源，解析源呀

**Comment by shylockWu** [comment]
同问

**Comment by bianningtao** [comment]
我弄好了，那个JSON文件，保存格式里面从数组开始，不要有别的，然后保存为文件，拖到对应的设置源里面就好了



| |
ab2961513324
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月11日 12:57 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Hiram-Wong/ZyPlayer] 怎么设置站点源，直播源，解析源呀 (Issue #32) |

同问

**Comment by shylockWu** [comment]
有举例吗，给个例子呗
