### ISSUE TITLE
[网络连接] 每次启动都会弹窗网络连接的授权

### ISSUE THREAD

**Issue by es3344520** [Hiram-Wong/ZyPlayer#321]
### zyplayer 版本

3.3.7

### 重现步骤

ZyPlayer为3.3.7版本， 设备是MAC系统，M芯片。 
   
如题，每次启动软件都会弹窗要授权， 防火墙设置没问题，以前用的旧版没有出现过这个问题。
![iShot_2024-08-23_11 36 11](https://github.com/user-attachments/assets/239a7127-076a-410d-93bb-cc5d72bbbfb9)

**Comment by Hiram-Wong** [comment]
暂时关闭防火墙吧，咱为找到解决方案

**Comment by Hiram-Wong** [comment]
能提供下具体 mac 系统版本和芯片信息吗

**Comment by es3344520** [comment]
> 能提供下具体 mac 系统版本和芯片信息吗
 
系统版本：12.7.6    M1芯片

**Comment by Hiram-Wong** [comment]
> > 能提供下具体 mac 系统版本和芯片信息吗
> 
> 系统版本：12.7.6 ， M1芯片

你这是一次都没更新过啊，真古董

**Comment by es3344520** [comment]
> > > 能提供下具体 mac 系统版本和芯片信息吗
> > 
> > 
> > 系统版本：12.7.6 ， M1芯片
> 
> 你这是一次都没更新过啊，真古董

不用更新，用起来丝滑得很。 新版本也没什么新鲜功能。

**Comment by Hiram-Wong** [comment]
尝试用 338版本是否解决该问题

**Comment by es3344520** [comment]
> 尝试用 338版本是否解决该问题

已解决，辛苦啦，感谢
