### ISSUE TITLE
可否考虑，在设置老板键时暂停播放。

### ISSUE THREAD

**Issue by vankeoa** [Hiram-Wong/ZyPlayer#323]
### 这个功能解决了什么问题

可否考虑，在设置老板键时隐藏的同时暂停播放。

### 你建议的方案是什么

可否考虑，在设置老板键时隐藏的同时暂停播放。

**Comment by Hiram-Wong** [comment]
暂无找到相关接口

**Comment by vankeoa** [comment]
谢谢

**Comment by Hiram-Wong** [comment]
338 版本重构后实现该逻辑，等待版本发布更新
