### ISSUE TITLE
Qbox最近会闪退

### ISSUE THREAD

**Issue by LizzyLee22** [Hiram-Wong/ZyPlayer#329]
### zyplayer 版本

qbox纪念版

### 重现步骤

点击片名，可以出现多个搜索结果，点击某个搜索结果就闪退到首页。我现在在投影仪上只能用的了qbox，其他版本显示都有点问题，6月到9月都能成功使用，最近这两天会闪退，求解决一下。

### 报错信息

闪退

### 实际结果

请解决闪退问题

**Comment by Hiram-Wong** [comment]
官方版本没有你说的qbox纪念版

**Comment by Hiram-Wong** [comment]
qbox是 tvbox 壳子，与此软件无关故关闭
