### ISSUE TITLE
能否增加自定义缓存文件夹的设置选项

### ISSUE THREAD

**Issue by dsjskeu** [Hiram-Wong/ZyPlayer#33]
如题，能否增加自定义缓存文件夹的设置选项，目前用着ramdisk，希望可以将缓存文件夹转移到内存盘上

**Comment by boy3510817** [comment]
复议，这个需求有的

**Comment by Hiram-Wong** [comment]
实际是chrome 内容，简单说就是浏览器缓存

**Comment by boy3510817** [comment]
明白，但是因为用了内存盘，想把缓冲能单独设置到内存盘目录里

**Comment by Hiram-Wong** [comment]
> 明白，但是因为用了内存盘，想把缓存能单独设置到内存盘目录里

这个只能先看下 electron 有没有提供对于的 api 了，没有就没办法了(chrome 好像是没有的)，其次我觉得软件已经内置可以清除缓存的功能，有没有都没必要吧

**Comment by boy3510817** [comment]
> > 明白，但是因为用了内存盘，想把缓存能单独设置到内存盘目录里
> 
> 这个只能先看下 electron 有没有提供对于的 api 了，没有就没办法了(chrome 好像是没有的)，其次我觉得软件已经内置可以清除缓存的功能，有没有都没必要吧

好吧，不行就用mklink吧

**Comment by Hiram-Wong** [comment]
> > > 明白，但是因为用了内存盘，想把缓存能单独设置到内存盘目录里
> > 
> > 
> > 这个只能先看下 electron 有没有提供对于的 api 了，没有就没办法了(chrome 好像是没有的)，其次我觉得软件已经内置可以清除缓存的功能，有没有都没必要吧
> 
> 好吧，不行就用mklink吧

window玩这么 6 吗，mklink都会
