### ISSUE TITLE
请教订阅源相关问题，我订阅成功后所有源都不能用为什么？

### ISSUE THREAD

**Issue by Darling-Lee** [Hiram-Wong/ZyPlayer#331]
各位大佬好，我跟着新版发布中的指引进入到源动力页面，按照上面的说明注册并登录，填写页面中提示的请求IP，按订阅，并把订阅链接拷贝到ZyPlayer的数据管理-配置导入-远端导入里，提示导入成功了，在影视配置里也出现了列表，但是每个源都不可用的，检测提示完成但是所有源都没给我激活，也没有数据，我是哪步做错了吗？

**Comment by Hiram-Wong** [comment]
导入选的 hipy

**Comment by Hiram-Wong** [comment]
确认 ip 是不是变了，变了重新授权

**Comment by Darling-Lee** [comment]
> 确认 ip 是不是变了，变了重新授权

大佬好，我刷新了源动力页面确认了请求IP没变，也重新订阅了，然后把zyplayer数据清空后，在数据管理-一键配置里选择hipy，把地址粘贴进去点确定，提示成功，但是影视配置中没有数据，试了几次也重启过Zyplayer都一样

**Comment by Hiram-Wong** [comment]
用的啥版本

**Comment by Darling-Lee** [comment]
> 用的啥版本

抱歉大佬，现在好了，我尝试直接在浏览器打开订阅链接，提示我IP不允许访问，原来我IP变了但是源动力页面上刷新是不更新我的ip的，我根据订阅链接那个提示把我的IP再次订阅就可以了

**Comment by Darling-Lee** [comment]
好用，已打赏

**Comment by Darling-Lee** [comment]
结了

**Comment by Hiram-Wong** [comment]
> > 用的啥版本
> 
> 抱歉大佬，现在好了，我尝试直接在浏览器打开订阅链接，提示我IP不允许访问，原来我IP变了但是源动力页面上刷新是不更新我的ip的，我根据订阅链接那个提示把我的IP再次订阅就可以了

又缓存应该是
