### ISSUE TITLE
可否考虑内置使用IINA播放器

### ISSUE THREAD

**Issue by vankeoa** [Hiram-Wong/ZyPlayer#332]
### 这个功能解决了什么问题

可否考虑内置使用IINA播放器，这个的格式好像更多，处理一些不适用的视频

### 你建议的方案是什么

可否考虑内置使用IINA播放器，这个的格式好像更多，处理一些不适用的视频

**Comment by Hiram-Wong** [comment]
内置是不可能的
1.没有 iina 授权
2.iina 也没有提供sdk

**Comment by vankeoa** [comment]
谢谢，以为它是开源的

**Comment by Hiram-Wong** [comment]
感谢你对该软件的支持和喜欢

**Comment by fredyu642** [comment]
> 内置是不可能的 1.没有 iina 授权 2.iina 也没有提供sdk

新的3.3.7播放器都不能使用，调用的IINA反倒能用，求解决

**Comment by fredyu642** [comment]
新的3.3.7 Mac m2 下载ARM安装包，总显示已损坏，通用和X86的都能用

**Comment by Hiram-Wong** [comment]
> 新的3.3.7 Mac m2 下载ARM安装包，总显示已损坏，通用和X86的都能用

一看你就没看 README，里面说明了解决办法，只要你的应用没签名都会有这个问题
