### ISSUE TITLE
[組件外掛] 廣告處理

### ISSUE THREAD

**Issue by linitfor** [Hiram-Wong/ZyPlayer#335]
### 这个功能解决了什么问题

在您的wiki 有看到處理廣告的相關說明，
但不確定要怎麼使用
亦或是這個部分有沒有一些規畫可以讓我們了解呢?

### 你建议的方案是什么

提供處理mask 廣告的功能

**Comment by Hiram-Wong** [comment]
首先须知：不是所有都能处理干净，只针对部分插播有效
1.在播放页面设置里可以开启
2.重新选集播放生效
