### ISSUE TITLE
[影视配置] 添加播放源时能设置http请求的timeout值

### ISSUE THREAD

**Issue by karma-sun** [Hiram-Wong/ZyPlayer#336]
### 这个功能解决了什么问题

部分播放源返回数据所需时间超过默认timeout，导致界面提示无数据

### 你建议的方案是什么

添加播放源界面增加一个设置http请求timeout值的设置，可以单独设置值覆盖默认

**Comment by Hiram-Wong** [comment]
设置可直接修改
