### ISSUE TITLE
第一次使用如何设置源？

### ISSUE THREAD

**Issue by shengxiaolei** [Hiram-Wong/ZyPlayer#34]
第一次下载软件提示“暂无数据,请前往设置-影视源设置默认源!”
但是找不到设置的地方 也不知道默认源是啥，文档中也找不到相关操作

求大神指点

**Comment by DaveBoy** [comment]
设置方法：点击设置按钮，在设置的"最下方"找到“一键配置”功能，在软件接口中，输入下方接口地址，点击确定即可
源：在issues里面或者vx搜索ZyPlayer找找别人分享的
