### ISSUE TITLE
UA功能问题

### ISSUE THREAD

**Issue by YanG-1989** [Hiram-Wong/ZyPlayer#340]
### 这个功能解决了什么问题

电视直播UA的问题

### 你建议的方案是什么

虽然直播方面可以进行修改ua...但是你只修改了请求源时候的ua，我希望远程订阅m3u的时候，也能和修改后是ua保持一致，而不是默认的浏览器ua

**Comment by Hiram-Wong** [comment]
其实没有实际效果，因为 m3u 里面不同域名那是不是又要不同 ua 了能

**Comment by YanG-1989** [comment]
实际上确实没什么用😂...为了个人需求。
比如有些获取m3u是屏蔽了浏览器请求。
现在很多播放器都不会用浏览器ua作为默认ua，基本上都用自己的app命名。

**Comment by YanG-1989** [comment]
> 其实没有实际效果，因为 m3u 里面不同域名那是不是又要不同 ua 了能

有部分iptv播放器确实有对m3u8支持独立ua的参数设置..
那是另外一回事了。

**Comment by Hiram-Wong** [comment]
先放放吧这个需求，目前再重构整个软件

**Comment by YanG-1989** [comment]
> 先放放吧这个需求，目前再重构整个软件

OK，坐等好消息在🤓
