### ISSUE TITLE
[电视] 频道名称显示不完整。

### ISSUE THREAD

**Issue by hi-jaylen** [Hiram-Wong/ZyPlayer#342]
### zyplayer 版本

3.3.7

### 重现步骤

![2024-11-06_081032](https://github.com/user-attachments/assets/d4bd729c-5870-4f70-ae6a-8d723cc2b9cc)
其实完整名称如下，当频道名称有空格时zyplayer只会显示空格前面的内容。
#EXTINF:-1 tvg-name="CCTV1"  group-title="央视频道",CCTV-1 综合

### 期望结果

希望改进。

### 系统信息

windows

**Comment by Hiram-Wong** [comment]
其实没必要取后面综合，取了综合两字epg可能就匹配不出来了

**Comment by ENiENG** [comment]
确实是个问题，光Sky sport就十几个频道，频道名全都是sky，都不知道哪个是哪个

**Comment by Hiram-Wong** [comment]
> 确实是个问题，光Sky sport就十几个频道，频道名全都是sky，都不知道哪个是哪个

给出链接

**Comment by Hiram-Wong** [comment]
> > > 确实是个问题，光Sky sport就十几个频道，频道名全都是sky，都不知道哪个是哪个
> > 
> > 
> > 给出链接
> 
> https://www.mytvsuper.xyz/m3u/Sport.m3u

<img width="1000" alt="image" src="https://github.com/user-attachments/assets/2505bd9e-9536-4331-bdc7-00587c32fa87">
下个版本安排
