### ISSUE TITLE
电视播放界面切换频道，节目不会跟着更新，还是最开始打开的频道的节目信息

### ISSUE THREAD

**Issue by u2o** [Hiram-Wong/ZyPlayer#346]
### zyplayer 版本

3.3.7

### 重现步骤

进到电视节目，双击频道播放，在播放界面切换频道，节目信息不更新，还是之前频道的节目信息

### 报错信息

无

### 期望结果

在播放界面切换频道，节目信息同步更新

### 实际结果

在播放界面切换频道，节目信息没有同步更新

### 系统信息

win 11

**Comment by Hiram-Wong** [comment]
338 版本已解决，等新版本发布

**Comment by Hiram-Wong** [comment]
> > 338 版本已解决，等新版本发布
> 
> 好的，谢谢。还有希望能显示软件版本号，方便查看。

右小角托盘关于有

**Comment by u2o** [comment]
> > > 338 版本已解决，等新版本发布
> > 
> > 
> > 好的，谢谢。还有希望能显示软件版本号，方便查看。
> 
> 右小角托盘关于有

好的，谢谢

**Comment by Hiram-Wong** [comment]
已更新，关闭此 issue
