### ISSUE TITLE
[更新]  win在线更新无限提醒

### ISSUE THREAD

**Issue by Hiram-Wong** [Hiram-Wong/ZyPlayer#349]
### zyplayer 版本

3.3.8

### 重现步骤

1. window 检查更新
2. 下载安装包(不点安装)
3. 重复点下载会出现多次提示

### 系统信息

macos15.1 m1pro arm

### 补充说明

1. 仅 window 支持在线更新
2. 监听器重复监听导致

**Comment by 1728430580** [comment]
3.3.8版本快捷配置drpy 默认是js0 导致道长的本地宝用不了 得手动改t3

**Comment by 1728430580** [comment]
好多bug怎么越做越难用 全站搜索会显示数据源出现问题 tvbox的直播源也不兼容了

**Comment by Hiram-Wong** [comment]
> 好多bug怎么越做越难用 全站搜索会显示数据源出现问题 tvbox的直播源也不兼容了

首先你觉得不好用你可以选择其他软件
其次搜索部分数据源出现问题不是很正常吗，然后你得上截图我才知道是什么问题
然后我不知道 tvbox的直播源不兼容了是什么意思，同理你得上截图我才知道是什么问题
