### ISSUE TITLE
主界面变成空白了

### ISSUE THREAD

**Issue by MillionZBW** [Hiram-Wong/ZyPlayer#35]
刚安装时好好的，重启下电脑，再启动就变成空白了（左侧所有功能点击都是空白）。刚启动时能看到主界面内容一闪而过，即使覆盖安装也不行。除了主页，其他页面可以点击左下刷新重新出现。
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/23210456/78c97d47-4ee2-49ec-97ec-d418d6236db9)

**Comment by Hiram-Wong** [comment]
重装应用
