### ISSUE TITLE
导入 饭太硬 报错误500

### ISSUE THREAD

**Issue by happymy** [Hiram-Wong/ZyPlayer#350]
### zyplayer 版本

last

### 重现步骤

数据管理-》快捷配置 选tvbox 直接导入在线的饭太硬网址。

### 报错信息

错误代码500 或显示成功 但是导入后还是空的。
试了其他几个tvbox源，都这样。
我看软件说明是兼容tvbox 。求教程指导。

**Comment by Hiram-Wong** [comment]
不支持，饭太硬这些都是加密的，需要解密后导入

**Comment by happymy** [comment]
我把接口解密了。
放在了https://raw.githubusercontent.com/happymy/tempfiles/refs/heads/main/fty.json
错误代码还是
Axios Error 500

**Comment by Hiram-Wong** [comment]
因为数据不是标准的 json 格式而是 json5 格式导致（就是里面有注释），删掉就行

**Comment by Hiram-Wong** [comment]
下个版本改为 json5 格式化

**Comment by happymy** [comment]
谢谢。

**Comment by zhouzhiqing8426** [comment]
> 我把接口解密了。 放在了https://raw.githubusercontent.com/happymy/tempfiles/refs/heads/main/fty.json 错误代码还是 Axios Error 500

![image](https://github.com/user-attachments/assets/8543e5e9-160d-42fa-8bfe-e4f5eb5375a1)
老哥，你是这样配置的吗，能用吗，我好像没解析出来几个有用的源啊，视频的都没有

**Comment by happymy** [comment]
目前不支持json5 等新版吧。
