### ISSUE TITLE
分类功能点击失败

### ISSUE THREAD

**Issue by wang2650** [Hiram-Wong/ZyPlayer#351]
### zyplayer 版本

最新版

### 重现步骤

点击任何一个来源的分类的时候，都会报错。
![image](https://github.com/user-attachments/assets/07bdf65e-7cd2-445a-a18d-1d299cf1d9ed)
如上图，点击电影分类的时候，报错。 切换其他量子资源，快车资源等都报同样的错误。之前的版本也是同样的错误。我的系统是win11

### 系统信息

win11

**Comment by Hiram-Wong** [comment]
非软件问题，数据源如此
