### ISSUE TITLE
搜素功能失效。

### ISSUE THREAD

**Issue by wang2650** [Hiram-Wong/ZyPlayer#352]
### zyplayer 版本

最新版

### 重现步骤

以前的版本没问题。最新的版本搜搜功能失败。 只要进行搜索，返回的都是同样的内容，且是错误的。
<img width="614" alt="1732025311818" src="https://github.com/user-attachments/assets/3fa7293d-5975-4822-a6b4-73406eb45d88">
不论搜索什么内容都是返回同样错误的内容

### 系统信息

win11

**Comment by wang2650** [comment]
<img width="614" alt="1732025311818" src="https://github.com/user-attachments/assets/0c85721d-8eeb-4391-97c9-448d3708f8e7">

**Comment by Hiram-Wong** [comment]
说明这个数据源乱返回，自行关闭此源搜索
