### ISSUE TITLE
[主程序] 软件崩溃

### ISSUE THREAD

**Issue by Hiram-Wong** [Hiram-Wong/ZyPlayer#354]
### zyplayer 版本

3.3.8

### 重现步骤

当已经打开一个程序再去打开一个程序的时候软件会奔溃

### 期望结果

规避打开两次情况

### 系统信息

mac15.1 arm m1pro

**Comment by user2144410132** [comment]
安装好了，打开没反应是为啥啊，从电脑资源管理器可以看见在后台运行，但是桌面没反应。😢

**Comment by Hiram-Wong** [comment]
> 安装好了，打开没反应是为什么啊，从电脑资源管理器可以看见在后台运行，但是桌面没反应。😢

参考文档https://zy.catni.cn/guide/usage.html#_1-3-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
