### ISSUE TITLE
[播放器] 播放不流畅及CPU占用高

### ISSUE THREAD

**Issue by Maxthos** [Hiram-Wong/ZyPlayer#355]
### zyplayer 版本

3.3.8

### 重现步骤

经过和其他播放器同源同集同时播放对比，zyfun播放不流畅，进度条加载很慢，其他播放器能流畅播放，还有存在CPU占用比较高的问题，试了很多源，都存在播放不流畅的现象，加载跟不上播放速度。

**Comment by Hiram-Wong** [comment]
那就设置调用系统播放器不就好了

**Comment by Hiram-Wong** [comment]
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/131b7739-e96c-49ac-9987-987c4dd3ba76">
