### ISSUE TITLE
Request failed with status code 500

### ISSUE THREAD

**Issue by Heriec** [Hiram-Wong/ZyPlayer#356]
使用源动力导入的数据，已关闭代理，浏览器页面禁用了缓存刷新了ip，但是首页出现了很多影视还是报错：哎呀, 出了点差错。没有给我展示出来

然后我开启调试，显示500错误
![image](https://github.com/user-attachments/assets/a8614623-3304-4fa1-b379-6b80060f0c4c)

所以哪一步搞错了，issue看了出现相同问题的，没有解决我的问题

**Comment by Hiram-Wong** [comment]
先查看文档https://zy.catni.cn/guide/usage.html

**Comment by Heriec** [comment]
所以按照文档的意思是**数据类型不对**？
可我就是直接使用源动力给的json，需要修改还是什么意思？
而且我在点击源动力->数据->某个源->一键导入 仍然提示报错500

**Comment by Heriec** [comment]
我就是把源动力的源导入然后就显示`哎呀，出了点差错`
![image](https://github.com/user-attachments/assets/1d76ff6a-4941-4e4d-89c2-24bf00daebeb)

而且我还说明了我没有挂代理、浏览器刷新了缓存，不存在ip变了的问题；最后我使用调试发现就是axios报错500
我提供了这么多信息，我什么都没有提供吗？你给个文档我也看了，内容只写到了`1.数据类型不对[手动修改]; 2.尝试刷新或者重启软件[数据处理错误];`

你说我什么都不提供？那我应该提供什么？怎么才叫你猜？

**Comment by Hiram-Wong** [comment]
数据类型截图能

**Comment by Hiram-Wong** [comment]
而且 01 这个源本来就是坏的，

**Comment by Heriec** [comment]
所以源动力源就不是正确的是吧，那我懂了，我以为是你官方维护的

**Comment by Hiram-Wong** [comment]
源动力只是一个分享平台，不保证所有数据源都可用

**Comment by Heriec** [comment]
我是在discussions部分看到的，如果本身源动力存在问题，建议说明一下
https://github.com/Hiram-Wong/ZyPlayer/discussions/48#discussion-5381608

**Comment by sir2024** [comment]
版本：3.3.10
源： http://xiaoguozitv.cn/catys/zyplay.json
使用在线导入，或者下载json文件后导入都显示500

![Image](https://github.com/user-attachments/assets/e354217c-9357-4fc4-ba93-500b436e86d9)

![Image](https://github.com/user-attachments/assets/bd217715-9a27-4ae6-bd81-512cbbd34e30)

**Comment by Hiram-Wong** [comment]
> 版本：3.3.10 源： http://xiaoguozitv.cn/catys/zyplay.json 使用在线导入，或者下载json文件后导入都显示500
> 
> ![Image](https://github.com/user-attachments/assets/e354217c-9357-4fc4-ba93-500b436e86d9)
> 
> ![Image](https://github.com/user-attachments/assets/bd217715-9a27-4ae6-bd81-512cbbd34e30)

新版本中该格式已被抛弃，请参考 readme 数据说明
