### ISSUE TITLE
在苹果M1电脑上，安装后不显示窗口

### ISSUE THREAD

**Issue by vankeoa** [Hiram-Wong/ZyPlayer#358]
### zyplayer 版本

3.3.8

### 重现步骤

在苹果M1电脑上，安装后不显示窗口

### 补充说明

在苹果M1电脑上，安装后不显示窗口

**Comment by Hiram-Wong** [comment]
查看文档https://zy.catni.cn/guide/usage.html#_1-3-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by Hiram-Wong** [comment]
m1整体来说应该没啥问题，因为我自己的电脑是 m1pro
