### ISSUE TITLE
为什么我打不开

### ISSUE THREAD

**Issue by wl1128-dy** [Hiram-Wong/ZyPlayer#360]

**Comment by Hiram-Wong** [comment]
查看文档https://zy.catni.cn/guide/usage.html#_1-3-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by wxyttty** [comment]
> 查看文档https://zy.catni.cn/guide/usage.html#_1-3-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

不起作用，没有后台进程，删除数据库目录，甚至全删重装依然不行

**Comment by Hiram-Wong** [comment]
上截图说明问题, 不然只能瞎猜

**Comment by wxyttty** [comment]
> 上截图说明问题, 不然只能瞎猜
没有图，就是双击没有任何反应。
测试发现D盘下不行，安装到C:\Program Files可以启动

**Comment by Hiram-Wong** [comment]
> > 上截图说明问题, 不然只能瞎猜
> > 没有图，就是双击没有任何反应。
> > 测试发现D盘下不行，安装到C:\Program Files可以启动

我自己 d 盘没问题，你什么版本

**Comment by wxyttty** [comment]
> > > 上截图说明问题, 不然只能瞎猜
> > > 没有图，就是双击没有任何反应。
> > > 测试发现D盘下不行，安装到C:\Program Files可以启动
> 
> 我自己 d 盘没问题，你什么版本

3.3.7到3.3.9D盘都不行，D是exfat

**Comment by Hiram-Wong** [comment]
我也是exfat
