### ISSUE TITLE
[影视] 导航栏不显示数据

### ISSUE THREAD

**Issue by aker-pc** [Hiram-Wong/ZyPlayer#361]
### zyplayer 版本

ZyPlayer 11f1dcb(git commit id)

### 重现步骤

- 函数调用栈
```
src/main/core/server/routes/v1/db/utils/data.ts: formatSearch
src/main/core/server/routes/v1/db/utils/data.ts: easy2tvbox
src/renderer/src/pages/film/index.vue: getSetting
```
![image](https://github.com/user-attachments/assets/96fddb14-bc73-4218-a88c-70039a94f6ef)
- 用于debug的版本
![image](https://github.com/user-attachments/assets/291becf1-6e85-42c5-ad04-b4202dc677db)
- 产生问题的提交并未处于正式版中：
```
https://github.com/Hiram-Wong/ZyPlayer/commit/0d7352a0f336dd5b31657d71e2a7ce4a127acb39#diff-0ef5ae84a4211d6abbca222fba9084500e47efb145dff87705f688ad7e2df43eR49
```
![image](https://github.com/user-attachments/assets/da48aecb-e780-4d9a-8f43-9f26d795dd30)

### 期望结果

- 目的：仅是想加点小功能自己玩，clone下来film标签页左边选单无法正常显示，故仅做反馈
- PS：不是搞前端的，可能部分内容理解上有所偏差，见谅

### 实际结果

- 产生结果（侧边导航栏无显示）
![image](https://github.com/user-attachments/assets/96a21ddc-e78e-4b2b-bee0-9196d039a100)

**Comment by Hiram-Wong** [comment]
已知，后续代码不在对 quickSearch 判断

**Comment by Hiram-Wong** [comment]
也可以在数据源中将搜索改成关闭或聚搜索即可，仅搜索数据不在侧边栏显示

**Comment by aker-pc** [comment]
> 也可以在数据源中将搜索改成关闭或聚搜索即可，仅搜索数据不在侧边栏显示

好的 谢谢
