### ISSUE TITLE
zyplayer 兼容性问题。

### ISSUE THREAD

**Issue by happymy** [Hiram-Wong/ZyPlayer#364]
### zyplayer 版本

last

### 重现步骤

导入饭太硬的源（解密和格式化），只能部分识别。大部分不能识别。
[fty.zip](https://github.com/user-attachments/files/17989263/fty.zip)
导入alist-tvbox（牙仙女里的饭太硬）的源（格式化） 报错误500
[yxn.zip](https://github.com/user-attachments/files/17989281/yxn.zip)

json存于本地的http服务。均使用数据管理-》快捷配置 导入。

试了几次后，软件无法打开。可以看到后台有进程，无软件界面。卸载重装后仍然如此。

### 系统信息

CPU:AMD64,OS:win11 home 23h2

**Comment by Hiram-Wong** [comment]
第一个问题：<img width="418" alt="image" src="https://github.com/user-attachments/assets/db44e1ee-7aa0-4441-aa4f-c78ff4fad1d2">
第二个问题看文档 https://zy.catni.cn

**Comment by happymy** [comment]
1 大佬加油，早日完全兼容。
2 删除了%USERPROFILE%\AppData\Roaming\{appname}\database\ 正常了。

我会继续关注大佬你的。
谢谢你。
