### ISSUE TITLE
ARM64版打开后不显示界面，但是后台显示有多个进程

### ISSUE THREAD

**Issue by wfg2000** [Hiram-Wong/ZyPlayer#365]
### zyplayer 版本

3.3.9 arm64

### 重现步骤

![截图_选择区域_20241204095324](https://github.com/user-attachments/assets/1d677ba8-0a0c-47c2-958d-6bf0123a6d82)

### 系统信息

linux-UOS-arm

**Comment by Hiram-Wong** [comment]
查看文档 https://zy.catni.cn
