### ISSUE TITLE
站点源分类不全

### ISSUE THREAD

**Issue by homepp1** [Hiram-Wong/ZyPlayer#37]
比较新旧两款软件,发现新版站点源分类不齐,比如量子资源站点中就缺少国产动漫,日韩动漫等等分类,不方便查找资源,希望改进.

**Comment by Hiram-Wong** [comment]
> 比较新旧两款软件,发现新版站点源分类不齐,比如量子资源站点中就缺少国产动漫,日韩动漫等等分类,不方便查找资源,希望改进.

因为你设置分类过滤
