### ISSUE TITLE
[组件名称] 从旧版本导出的源站不能被新版本完全识别；源检测正常但是在影视页面无法正常显示

### ISSUE THREAD

**Issue by NgChin** [Hiram-Wong/ZyPlayer#371]
### zyplayer 版本

3.3.9

### 重现步骤

1. 旧版本ZY Player：设置-数据管理-配置-数据导出，新版本ZY Fun:设置-数据管理-配置-数据导入
2. 影视配置-操作-检测-影视页面
![屏幕截图 2024-12-08 225346](https://github.com/user-attachments/assets/70c1029c-7a36-4a73-84c9-1310afee3d8c)

### 报错信息

网络请求失败, 请尝试手动刷新
![屏幕截图 2024-12-08 225417](https://github.com/user-attachments/assets/2b83f605-4b89-4d71-a0bf-0e1494c09c4e)

### 期望结果

1.实现新旧版本资源正常转换
2.检测结果正常的站源可以正常显示

### 系统信息

64位Windows11 23H2 处理器：11th Gen Intel(R) Core(TM) i5-11400H

**Comment by Hiram-Wong** [comment]
更新日志和文件都已经说明: 检测知识一个辅助，不能保证完全可用须知
不在回复

**Comment by Hiram-Wong** [comment]
数据源失效了吧，数据发一下看看

**Comment by NgChin** [comment]
![屏幕截图 2024-12-08 233740](https://github.com/user-attachments/assets/087e02eb-5276-48a2-aaa7-949a591485d5)
旧版本3.3.7 ZY Player可以正常播放
![屏幕截图 2024-12-08 232937](https://github.com/user-attachments/assets/6e5d9f2e-a958-4e34-81f3-d8e2b7b4f2e9)
新版本3.3.9 ZY Fun显示“网络请求失败”
![屏幕截图 2024-12-08 233352](https://github.com/user-attachments/assets/6eade6f2-43cf-4d01-97af-85593b836a43)
新版本3.3.9检测正常页面

源名称：闪电资源
接口：https://sdzyapi.com/api.php/provide/vod/at/xml/

**Comment by Hiram-Wong** [comment]
因为这个源首页没有数据，没问题的，
337-338 中重构了首页数据逻辑
<img width="1000" alt="image" src="https://github.com/user-attachments/assets/5866fe26-9a6d-4415-b096-2785923f3f30">

**Comment by NgChin** [comment]
数据重构也会影响播放吗？
![屏幕截图 2024-12-09 000037](https://github.com/user-attachments/assets/88a17807-ef9a-4f62-9c8d-f99ee3fee4f2)
3.3.9 ZY Fun播放界面（艺术播放器）
![屏幕截图 2024-12-09 000140](https://github.com/user-attachments/assets/bdfc1ef5-f6fb-452b-a6e8-2ae82fca224e)
3.3.7 ZY Player播放器（艺术播放器）
备注：闪电资源（https://sdzyapi.com/api.php/provide/vod/at/xml/）

**Comment by Hiram-Wong** [comment]
xml 格式写了一个 bug，下个版本更新

**Comment by NgChin** [comment]
收到，谢谢作者。期待新版本的到来~

**Comment by sjnhnp** [comment]
@NgChin 
请问 https://sdzyapi.com/api.php/provide/vod/at/xml/ 闪电资源，用 3.3.7的版本，你可以搜索吗？我发现凡是xml的都无法进行搜索，json的可以搜索出来结果。
