### ISSUE TITLE
[影视首页] 首页能否加个启用开关

### ISSUE THREAD

**Issue by GGreyCat** [Hiram-Wong/ZyPlayer#377]
### 这个功能解决了什么问题

不想要首页 能否在基础配置 影视里加个首页启动开关（总感觉首页在本地包上打开慢）

### 你建议的方案是什么

给首页加个开关

**Comment by Hiram-Wong** [comment]
所有设置应在设置中完成，该建议属于冗余设计，不给予采纳，需要可自己二开

**Comment by GGreyCat** [comment]
设置里没看到哪里可以关闭首页分类的啊

**Comment by GGreyCat** [comment]
或者 我在哪个文件中 注释掉哪些代码可以关闭

**Comment by Hiram-Wong** [comment]
<img width="878" alt="image" src="https://github.com/user-attachments/assets/b312fcc8-99d7-4787-be56-18fc88811398" />

**Comment by GGreyCat** [comment]
好的 屏蔽掉了  发现代码中好像是拼写错误 netwotkError networkError 有几处 另一个文件也有

**Comment by Hiram-Wong** [comment]
收到
