### ISSUE TITLE
黑苹果系统，下载通用版或者下载x64版，均显示java错误

### ISSUE THREAD

**Issue by ARMINCHEN789** [Hiram-Wong/ZyPlayer#379]
### zyplayer 版本

3.3.9

### 重现步骤

<img width="632" alt="截屏2024-12-14 11 26 29" src="https://github.com/user-attachments/assets/3e2ec78f-4dfe-4e7d-83c1-3cbeb0640e3a" />
<img width="692" alt="截屏2024-12-14 11 27 32" src="https://github.com/user-attachments/assets/34e0658e-5ee1-4b49-afed-515f77f6e400" />

### 系统信息

macOS15.2（24c101）系统Intel cpu

**Comment by Hiram-Wong** [comment]
见 issue #375
不在说明
