### ISSUE TITLE
配置动力源后影视配置等无数据

### ISSUE THREAD

**Issue by lijiuxing1** [Hiram-Wong/ZyPlayer#383]
### zyplayer 版本

3.39

### 重现步骤

1. 注册动力源账号
2. 使用自己的ip授权
3. 使用授权地址配置
![image](https://github.com/user-attachments/assets/2c6748cf-c0e4-4744-b799-dfbb5084eaf1)

### 报错信息

配置成功后影视配置等无数据，我理解成功后这里应该有可用的配置，不清楚是操作错误还是理解错误，或是软件问题
![image](https://github.com/user-attachments/assets/3b48d0a3-d6f4-4f91-acc5-63695b7bd861)

### 期望结果

期望配置动力源成功后，影视配置等有数据

### 系统信息

Windows 10 专业版  22H2  19045.5247

**Comment by Hiram-Wong** [comment]
先参考文档https://zy.catni.cn/guide/usage.html#_1-3-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
看看
