### ISSUE TITLE
[tv] tv的接口是否支持txt、m3u8格式

### ISSUE THREAD

**Issue by WendouXie** [Hiram-Wong/ZyPlayer#384]
### zyplayer 版本

3.3.9

### 重现步骤

zyfun的iptv接口是否支持txt、m3u8格式？有部分源提供的是txt格式，还需要转换

### 系统信息

win11

**Comment by Hiram-Wong** [comment]
<img width="501" alt="image" src="https://github.com/user-attachments/assets/d36dbb60-d865-42e1-9af6-6a1380603767" />
先看文档谢谢
