### ISSUE TITLE
[搜索] 搜索 火影 关键字，一会有资料，一会又没有资料

### ISSUE THREAD

**Issue by xueyitan** [Hiram-Wong/ZyPlayer#385]
### zyplayer 版本

3.3.9

### 重现步骤

[搜索] 搜索 火影 关键字，一会有资料，一会又没有资料，组内，站内，全站都试了。这个就很奇怪，不明白问题出在哪里了，然后是接口超时引起的，但是接口超时时间好像设置限制了不能超过5秒。。。

### 系统信息

mac inter 15.1.1

**Comment by xueyitan** [comment]
我手动在外面修复好超时时间99999粘进去才修改成功，不然它首位好像只能是5，把超时时间改成这么大后，好像搜索正常了，正常是指每次结果都差不多了

**Comment by Hiram-Wong** [comment]
正常，非 bug，这和自己网络已经站点网络有关

**Comment by Hiram-Wong** [comment]
超过 5 秒一般来说已经严重影响体验，也没必要继续加载了。虽然全局超时可以自己控制
