### ISSUE TITLE
[播放] T4 hipy的爬虫播放逻辑是不是有些问题

### ISSUE THREAD

**Issue by Meroser** [Hiram-Wong/ZyPlayer#387]
### zyplayer 版本

3.3.9

### 重现步骤

按照T4，标准接口，播放返回的数据如下
{
    "parse": 0,
    "playUrl": "",
    "url": "https://ppvod01.blbtgg.com/splitOut/20241123/556398/V2024112313211974594556398/index.m3u8?auth_key=1735289813-272570be7c0f41b2ab7336666a3b5dc6-0-aeaa8dd4e5b357fb3cd062fcdb5ab6fc",
    "header": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0",
        "Referer": "https://www.sunnafh.com/"
    }
}
从后台接口调用历史，确实也看到了这个请求，127.0.0.1 - - [27/Dec/2024 16:56:54] "GET /vod/sjys?extend=&flag=视觉影视&play=131065-1120485 HTTP/1.1" 200 -
可却确定的是播放器已经获取到了播放url，可能是软禁解析逻辑问题，没办法播放
cms的接口可以正常播放

### 系统信息

Window 11 pro

### 补充说明

127.0.0.1 - - [27/Dec/2024 16:47:59] "GET /vod/sjys?ac=detail&ids=131166&extend= HTTP/1.1" 200 -
127.0.0.1 - - [27/Dec/2024 16:48:01] "GET /vod/sjys?extend=&flag=视觉影视&play=131166-1122303 HTTP/1.1" 200 -
127.0.0.1 - - [27/Dec/2024 16:49:12] "GET /vod/sjys?ac=detail&ids=131337&extend= HTTP/1.1" 200 -
127.0.0.1 - - [27/Dec/2024 16:49:16] "GET /vod/sjys?extend=&flag=视觉影视&play=131337-1124724 HTTP/1.1" 200 -
127.0.0.1 - - [27/Dec/2024 16:56:54] "GET /vod/sjys?extend=&flag=视觉影视&play=131065-1120485 HTTP/1.1" 200 -
除了播放，其余4个接口，主页、分类、详情、搜索均正常

**Comment by Hiram-Wong** [comment]
试试最新的开发版，这个问题我记得开发版修了

**Comment by Meroser** [comment]
> 试试最新的开发版，这个问题我记得 339 正式版是又这个问题的，开发版修了

刚刚试了开发版，正常了。谢谢大佬的开发
