### ISSUE TITLE
本地打包exe火山播放器不能使用

### ISSUE THREAD

**Issue by jahem** [Hiram-Wong/ZyPlayer#42]
yarn electron:dev 运行是可以使用的
yarn electron:build:win 打包成exe后,安装就不能使用了

系统
win10 + node v18.14.0

**Comment by Hiram-Wong** [comment]
需要把node 包里面，链接//改成 https

**Comment by jahem** [comment]
node_modules/@volcengine/veplayer/dist/index.min.js 里面吗？

**Comment by Hiram-Wong** [comment]
是的

**Comment by jahem** [comment]
可以了，感谢
