### ISSUE TITLE
亲测，有效的源，使用“一键配置”即可上车

### ISSUE THREAD

**Issue by wwb521** [Hiram-Wong/ZyPlayer#43]
http://xiaoguozitv.cn/catys/zyplay.json
https://ghproxy.com/https://raw.githubusercontent.com/ls125781003/dmtg/main/zy_yuan.json
https://fastly.jsdelivr.net/gh/ls125781003/dmtg@main/zy_yuan.json
https://ghproxy.net/https://raw.githubusercontent.com/ls125781003/dmtg/main/zy_yuan.json
https://raw.fastgit.org/ls125781003/dmtg/main/zy_yuan.json
这些源都差不多，翻来覆去就是那几个，所以麻辣的五香的，挑点大家最爱的，希大家踊跃分享一下其他源

**Comment by Hiram-Wong** [comment]
> http://xiaoguozitv.cn/catys/zyplay.json
> 
> 希大家踊跃分享一下其他高质量源

看了下文件，其实数据没有按照 readme 里规定格式哦

**Comment by kkxxcxll** [comment]
微信上搜一大堆接口，我建议这个跟阿里云盘配合资源多多。tvbox的是本地包

**Comment by kkxxcxll** [comment]
接口微信上搜很多的，搜tvbox就有，我想建议这个能否跟云盘配合，tvbox那个好像叫本地包。

**Comment by Mubai-meng** [comment]
编辑源里重置没有反应啊

**Comment by Hiram-Wong** [comment]
> 编辑源里重置没有反应啊

编辑源里，哪有重置  我咋不知道

**Comment by Mubai-meng** [comment]
> > 编辑源里重置没有反应啊
> 
> 编辑源里，哪有重置  我咋不知道 

版本下错了，我的

**Comment by murazi** [comment]
> 接口微信上搜很多的，搜tvbox就有，我想建议这个能否跟云盘配合，tvbox那个好像叫本地包。

ZYPlayer的信息源可以用tvbox的？

**Comment by yang66** [comment]
> http://xiaoguozitv.cn/catys/zyplay.json https://ghproxy.com/https://raw.githubusercontent.com/ls125781003/dmtg/main/zy_yuan.json https://fastly.jsdelivr.net/gh/ls125781003/dmtg@main/zy_yuan.json https://ghproxy.net/https://raw.githubusercontent.com/ls125781003/dmtg/main/zy_yuan.json https://raw.fastgit.org/ls125781003/dmtg/main/zy_yuan.json 这些源都差不多，翻来覆去就是那几个，所以麻辣的五香的，挑点大家最爱的，希大家踊跃分享一下其他源

Mark

**Comment by lowy** [comment]
小白 没搞懂 有没有谁能说明一下 到底哪些是站内源 哪些是直播源 哪些又是解析源 有点傻傻分不清楚

**Comment by yaliklinty** [comment]
cy

**Comment by DOXUU** [comment]
最新版的 是不是没有一键配置的了  只能一个一个添加

**Comment by Hiram-Wong** [comment]
> 最新版的 是不是没有一键配置的了 只能一个一个添加

数据管理支持导入，但数据格式有变动，参考 readme

**Comment by WhiteSpiny** [comment]
> > 最新版的 是不是没有一键配置的了 只能一个一个添加
> 
> 数据管理支持导入，但数据格式有变动，参考 readme

最新版导入没有反应，重新加载一秒后还是空白

**Comment by 122778740** [comment]
http://xiaoguozitv.cn/catys/zyplay.json
https://ghproxy.com/https://raw.githubusercontent.com/ls125781003/dmtg/main/zy_yuan.json
https://fastly.jsdelivr.net/gh/ls125781003/dmtg@main/zy_yuan.json
https://ghproxy.net/https://raw.githubusercontent.com/ls125781003/dmtg/main/zy_yuan.json
https://raw.fastgit.org/ls125781003/dmtg/main/zy_yuan.json
这些源都差不多，翻来覆去就是那几个，所以麻辣的五香的，挑点大家最爱的，希大家踊跃分享一下其他源

**Comment by ddwinhzy** [comment]
有些可以，然后导入第二次就提示：一键配置失败：TypeError: Cannot read properties of undefined (reading 'default')

**Comment by PSRBest** [comment]
> > https://raw.fastgit.org/ls125781003/dmtg/main/zy_yuan.json
> 
> 最新版 3.3.1中从设置 - 数据管理 - 配置导入 处进行导入 <img alt="image" width="600" src="https://private-user-images.githubusercontent.com/12553514/293622580-d94474b6-69a4-40e2-8aff-cc4ff4518f77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTM3NzYsIm5iZiI6MTcwNDE5MzQ3NiwicGF0aCI6Ii8xMjU1MzUxNC8yOTM2MjI1ODAtZDk0NDc0YjYtNjlhNC00MGUyLThhZmYtY2M0ZmY0NTE4Zjc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDExMDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwOTFmYjAwNjZhZDQzZWZjZmEyMDYxYmFiM2RhZDg2MjU4ZjcyMDZlY2ZiMWQ2OThlMTVmMzFjNWFmN2E1MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tkv3V6T6MxXkP9FPP5-otKbMMzDI4pDGZWV2YSq1p44">

最新不是2.8.8么？导入json没反应。。。

**Comment by PSRBest** [comment]
看到二开了。不过还是原版简洁一些符合我的需求，已经配置好源了。

**Comment by springculture** [comment]
这些源和tvbox比起来实在太差了

**Comment by PhenixFeather** [comment]
这层楼里的源好像都不太行了，有大哥分享下什么地方能找到好用的源吗

**Comment by Beaverno** [comment]
是啊tvbox的源真的快
