### ISSUE TITLE
可以使用tvbox的线路嘛

### ISSUE THREAD

**Issue by 347823891** [Hiram-Wong/ZyPlayer#5]
一键配置怎么使用的

**Comment by blueskysk** [comment]
玩不懂源配置，TVBOX的订阅源不能直接导入吗。。。

**Comment by Hiram-Wong** [comment]
请参考README说明格式，暂不兼容如上说的其他线路

**Comment by itscolor** [comment]
> 请参考README说明格式，暂不兼容如上说的其他线路
希望可以尽快开发功能，可以兼容TVBOX的源，这样电脑用这款软件就很秀了，毕竟TVBOX没有电脑版本。
