### ISSUE TITLE
需求：设置的站点源信息，增加“资源数”

### ISSUE THREAD

**Issue by xchnotxzh** [Hiram-Wong/ZyPlayer#50]
评价站点源好坏，除了可用性，”资源数“也是重要标准，比如，有的“坏站点源”可以是"可用但资源数少得可怜"。

在想切换站点源或设置默认站点源时，目前只能到主页面一个个查看站点源的资源数，对于站点源很多的情况会很麻烦。

所以，希望能在设置的站点源信息列表中加上“资源数”。

**Comment by Hiram-Wong** [comment]
感谢您的支持及建议，改需求已于 v3.2.6已经实现，更新最新版

**Comment by xchnotxzh** [comment]
> 感谢您的支持及建议，改需求已于 v3.2.6已经实现，更新最新版

大佬，能否给资源数加个排序，这样用起来更方便，配置时通常找资源数最多的为默认。
