### ISSUE TITLE
第三方播放器

### ISSUE THREAD

**Issue by caiyusheng1005** [Hiram-Wong/ZyPlayer#55]
现在内置的第三方播放器实在不敢恭维，能不能内置其他的开源播放器比如vlc，kmp什么的，或者给用户留一个选择本地播放器的选项。谢谢

**Comment by Hiram-Wong** [comment]
暂时没有好方法解决，此软件使用的是 web技术，所以引入的也是web播放器，和 vlc 这些比不了，不是一个技术栈，也无法直接调用

**Comment by modestH** [comment]
好像可以在下载页复制当前播放视频的链接，然后到本地的pot player里打开进行播放，不过也是卡就是了

**Comment by Hiram-Wong** [comment]
3.3.3 版本支持自定义播放器
