### ISSUE TITLE
希望添加appv1接口解析功能

### ISSUE THREAD

**Issue by wishdq** [Hiram-Wong/ZyPlayer#58]
http://app.ishen520.com/api.php/v1.vod

接口参数基本和cms一致

**Comment by Hiram-Wong** [comment]
> 
> 
> http://app.ishen520.com/api.php/v1.vod
> 
> 
> 
> 接口参数基本和cms一致

请提供完整等我参数
包括不限于 搜索，详情，首页，分类，热搜等

**Comment by wishdq** [comment]
示例 ：
搜索 ：http://app.ishen520.com/api.php/v1.vod?wd=千年


接收参数：
全部列表   ac=list
类别          t=type_id
页码          pg=页码
搜索          wd=搜索关键字
时限          h=8                    8小时内的数据


内容接收参数：
ids=vod_id，多个ID逗号分割。

**Comment by qallen028** [comment]
> 示例 ： 搜索 ：[http://app.ishen520.com/api.php/v1.vod?wd=千年](http://app.ishen520.com/api.php/v1.vod?wd=%E5%8D%83%E5%B9%B4)
> 
> 接收参数： 全部列表 ac=list 类别 t=type_id 页码 pg=页码 搜索 wd=搜索关键字 时限 h=8 8小时内的数据
> 
> 内容接收参数： ids=vod_id，多个ID逗号分割。

参数好像是错误的

**Comment by Hiram-Wong** [comment]
> > 示例 ： 搜索 ：[http://app.ishen520.com/api.php/v1.vod?wd=千年](http://app.ishen520.com/api.php/v1.vod?wd=%E5%8D%83%E5%B9%B4)
> > 接收参数： 全部列表 ac=list 类别 t=type_id 页码 pg=页码 搜索 wd=搜索关键字 时限 h=8 8小时内的数据
> > 内容接收参数： ids=vod_id，多个ID逗号分割。
> 
> 参数好像是错误的

我目前知道的是 v1 有两个不同版本，所以我没适配 😂

**Comment by qallen028** [comment]
测试接口：http://app.qianju.cc/api.php/v1.vod
列表：?ac=list 可传参数 page type

那个大佬补充一下分类接口

**Comment by qallen028** [comment]
> > > 示例 ： 搜索 ：[http://app.ishen520.com/api.php/v1.vod?wd=千年](http://app.ishen520.com/api.php/v1.vod?wd=%E5%8D%83%E5%B9%B4)
> > > 接收参数： 全部列表 ac=list 类别 t=type_id 页码 pg=页码 搜索 wd=搜索关键字 时限 h=8 8小时内的数据
> > > 内容接收参数： ids=vod_id，多个ID逗号分割。
> > 
> > 
> > 参数好像是错误的
> 
> 我目前知道的是 v1 有两个不同版本，所以我没适配 😂

这样呀，那我也不加了😂

**Comment by Hiram-Wong** [comment]
> > > > 示例 ： 搜索 ：[http://app.ishen520.com/api.php/v1.vod?wd=千年](http://app.ishen520.com/api.php/v1.vod?wd=%E5%8D%83%E5%B9%B4)
> > > > 接收参数： 全部列表 ac=list 类别 t=type_id 页码 pg=页码 搜索 wd=搜索关键字 时限 h=8 8小时内的数据
> > > > 内容接收参数： ids=vod_id，多个ID逗号分割。
> > > 
> > > 
> > > 参数好像是错误的
> > 
> > 
> > 我目前知道的是 v1 有两个不同版本，所以我没适配 😂
> 
> 这样呀，那我也不加了😂

下面是v1 的一种，还有v2 的

https://www.laimi.me/api.php/v1.vod/types
https://www.laimi.me/api.php/v1.vod?limit=12&page=1
https://www.laimi.me/api.php/v1.vod/detail?vod_id=18815&token=&key=0710
https://www.laimi.me/api.php/v1.vod?wd=%E6%96%97%E7%BD%97&limit=20&page=1&ac=videolist

**Comment by qallen028** [comment]
> > > > > 示例 ： 搜索 ：[http://app.ishen520.com/api.php/v1.vod?wd=千年](http://app.ishen520.com/api.php/v1.vod?wd=%E5%8D%83%E5%B9%B4)
> > > > > 接收参数： 全部列表 ac=list 类别 t=type_id 页码 pg=页码 搜索 wd=搜索关键字 时限 h=8 8小时内的数据
> > > > > 内容接收参数： ids=vod_id，多个ID逗号分割。
> > > > 
> > > > 
> > > > 参数好像是错误的
> > > 
> > > 
> > > 我目前知道的是 v1 有两个不同版本，所以我没适配 😂
> > 
> > 
> > 这样呀，那我也不加了😂
> 
> 下面是v1 的一种，还有v2 的
> 
> https://www.laimi.me/api.php/v1.vod/types https://www.laimi.me/api.php/v1.vod?limit=12&page=1 https://www.laimi.me/api.php/v1.vod/detail?vod_id=18815&token=&key=0710 https://www.laimi.me/api.php/v1.vod?wd=%E6%96%97%E7%BD%97&limit=20&page=1&ac=videolist

这个和我上面接的那个一样，我是从tvbox 刘备源那里解析出来的，有第二种吗？也想看看

**Comment by Hiram-Wong** [comment]
感谢您的支持及建议，该需求已于 v3.2.6已经实现，更新最新版
