### ISSUE TITLE
已经搜索过视频，切换源的时候会把搜索条件清理掉

### ISSUE THREAD

**Issue by akschy** [Hiram-Wong/ZyPlayer#61]
已经搜索过视频，切换源的时候会把搜索条件清理掉
如果之前的源没有对应的视频或者视频源质量差想要切换源，切换之后还要重新输入搜索内容，比较不方便
希望能够在切换源的时候保留搜索内容，也可以在搜索弹出框里加入搜索历史记录最近几次的搜索内容，这样避免换源重新搜索

**Comment by Hiram-Wong** [comment]
这个需求可以设置搜索模式为全部搜索或者组内搜索就可以解决你的问题，暂不会修改
