### ISSUE TITLE
需求：更新后保留数据

### ISSUE THREAD

**Issue by xchnotxzh** [Hiram-Wong/ZyPlayer#62]
目前更新（在windows上通过exe覆盖更新）会清空设置、历史和收藏等数据，需要重新设置，希望能够保留数据。

**Comment by Hiram-Wong** [comment]
不会删除数据的，只要软件名不变数据一直是同一份

**Comment by xchnotxzh** [comment]
> 不会删除数据的，只要软件名不变数据一直是同一份

数据应该还在，但页面上会清空的，每次更新完都一片空白，得重新配置。

**Comment by Hiram-Wong** [comment]
> > 不会删除数据的，只要软件名不变数据一直是同一份
> 
> 数据应该还在，但页面上会清空的，每次更新完都一片空白，得重新配置。

不应该，我测试了几次都可以

**Comment by xchnotxzh** [comment]
我又测试了几次，复现不了了。。。

**Comment by Che-Eridanus** [comment]
可能是重新安装会清数据吧，我覆盖安装以后配置都丢了

**Comment by xchnotxzh** [comment]
> > > 不会删除数据的，只要软件名不变数据一直是同一份
> > 
> > 
> > 数据应该还在，但页面上会清空的，每次更新完都一片空白，得重新配置。
> 
> 不应该，我测试了几次都可以

3.2.7 版本这个问题又复现了

**Comment by Hiram-Wong** [comment]
> > > > 不会删除数据的，只要软件名不变数据一直是同一份
> > > 
> > > 
> > > 数据应该还在，但页面上会清空的，每次更新完都一片空白，得重新配置。
> > 
> > 
> > 不应该，我测试了几次都可以
> 
> 3.2.6升级到3.2.7 该问题复现了，3.2.7重复安装是正常保留数据的。

用的软件自带的更新吗，还是直接安装的 3.2.7，什么操作系统

**Comment by xchnotxzh** [comment]
> 

exe安装程序覆盖更新，win10系统。

**Comment by Hanoch-J** [comment]
> 

win11 用的软件设置自带检测更新，之后，任何配置都没有了，现在在到处找【源】。而且，最新版没有了【一键配置】
