### ISSUE TITLE
  win8.1 64启动不了（都试过了）

### ISSUE THREAD

**Issue by cymcn** [Hiram-Wong/ZyPlayer#65]
![捕获](https://github.com/Hiram-Wong/ZyPlayer/assets/95155750/92b8d862-b87f-4286-bb75-10536b166496)

  大佬  win8.1企业版64系统   https://github.com/Hiram-Wong/ZyPlayer/releases都下载试过了启动不了 

Hunlongyu/ZY-Player大佬的2.88是正常的，可以启动使用的。

这是什么原因，怎么解决

**Comment by Hiram-Wong** [comment]
> ![捕获](https://github.com/Hiram-Wong/ZyPlayer/assets/95155750/92b8d862-b87f-4286-bb75-10536b166496)
> 
> 
> 
>   大佬  win8.1企业版64系统   https://github.com/Hiram-Wong/ZyPlayer/releases都下载试过了启动不了 
> 
> 
> 
> Hunlongyu/ZY-Player大佬的2.88是正常的，可以启动使用的。
> 
> 
> 
> 
> 
> 
> 
> 这是什么原因，怎么解决

下载win7版本即可，electron已经在20.x版本不支持8.1 readme🀄️已说明

**Comment by cymcn** [comment]
感谢  大佬https://github.com/Hiram-Wong/ZyPlayer/releases 那个版本还支持 win8.1企业版64系统

**Comment by Hiram-Wong** [comment]
> 感谢 大佬https://github.com/Hiram-Wong/ZyPlayer/releases 那个版本还支持 win8.1企业版64系统

最新的就支持，选择包含 win7 的 x64
