### ISSUE TITLE
怎么下载非m3u8或MP4的视频？

### ISSUE THREAD

**Issue by modestH** [Hiram-Wong/ZyPlayer#66]
比较老的资源，不是m3u8或MP4格式的，不知道该用什么下载器下载，有没有老哥有推荐的？

**Comment by modestH** [comment]
> 比较老的资源，不是m3u8或MP4格式的，不知道该用什么下载器下载，有没有老哥有推荐的？

不对，好像是选择批量下载的时候，复制的链接，没有带/index.m3u8的后缀

**Comment by Hiram-Wong** [comment]
这个没办法批量下载，不可能每个都嗅探
