### ISSUE TITLE
需求：更精细的历史记录

### ISSUE THREAD

**Issue by xchnotxzh** [Hiram-Wong/ZyPlayer#67]
希望历史记录，能精确到退出视频时的播放时刻，从而下次能从历史记录无缝继续播放。

**Comment by Hiram-Wong** [comment]
目前实现逻辑就是这套逻辑

**Comment by Hiram-Wong** [comment]
> 目前实现逻辑就是这套逻辑

监听的进度变化时间

**Comment by xchnotxzh** [comment]
> > 目前实现逻辑就是这套逻辑
> 
> 监听的进度变化时间

不好意思，我另一台电脑可能还是老版本，我试了最新版本的确实现了该功能。👍
