### ISSUE TITLE
uncaught exception

### ISSUE THREAD

**Issue by caiyusheng1005** [Hiram-Wong/ZyPlayer#69]
如图：
[zyplayer bug.pdf](https://github.com/Hiram-Wong/ZyPlayer/files/12425826/zyplayer.bug.pdf)

**Comment by Hiram-Wong** [comment]
> 如图： [zyplayer bug.pdf](https://github.com/Hiram-Wong/ZyPlayer/files/12425826/zyplayer.bug.pdf)

已经发现了该问题，正在研究解决方案

**Comment by Hiram-Wong** [comment]
3.2.8 中更新
