### ISSUE TITLE
众筹iOS自签版

### ISSUE THREAD

**Issue by babiq233** [Hiram-Wong/ZyPlayer#71]
# iOS的兄弟们
## 大家支持给作者众筹出一个iOS版吗？

大家一起投个票啊

**Comment by CxiaoyuN** [comment]
支持

**Comment by jian263994241** [comment]
iOS有更好用的 。 vidhub（完全免费）， iiva（不订阅也挺好用）， infuse（需要订阅）

**Comment by q123458384** [comment]
ios 用巨魔永久安装呀，不过ios版本不太好用，太久没更新了，添加视频源一直假死。
上面推荐的vidhub infuse 都不能添加自定义视频源

**Comment by Hiram-Wong** [comment]
可以是下 apple store 商店的阿七播放器 ，我觉得还行，只支持 cms json

**Comment by q123458384** [comment]
IOS找到个更好用的 猫影视 ：https://github.com/catvod/CatVodOpen
需要自签 我是巨魔装的

**Comment by babiq233** [comment]
老哥，我们想要的是zyplayer 桌面版的完整体验呀，希望你能搞个iOS版吧，把收款码发出来我们给你众筹，你也是很辛苦的，或者等你搞好了和趣听音乐一样搞个TF内测模式，然后付费内测也好啊，老哥求求🥹zyplayer是我用过最好用的系统手机端iOS版也能整一个> 可以试下 apple store 商店的阿七播放器 ，我觉得还行，只支持 cms json

**Comment by babiq233** [comment]
我们想要的是和zy一样添加自定义视频源的呀，老哥，主要是可高度自定义> 可以试下 apple store 商店的阿七播放器 ，我觉得还行，只支持 cms json
