### ISSUE TITLE
3.2.8 远端导入不了！！

### ISSUE THREAD

**Issue by woshiayi1** [Hiram-Wong/ZyPlayer#74]
提示导入成功！但是什么都没有！！是不是我哪里没弄好啊！！
https://ghproxy.net/https://raw.githubusercontent.com/ls125781003/dmtg/main/zy_yuan.json

**Comment by Hiram-Wong** [comment]
数据格式右边，具体查看readme
可以试下我的https://zy.catni.cn/config.json

**Comment by woshiayi1** [comment]
可以了，是格式的问题。谢了！！
