### ISSUE TITLE
3.2.8更新之后怎么没有一键配置选项了？本地导入和远程导入使用原来一键配置的json文件都不能成功啊

### ISSUE THREAD

**Issue by arlingus** [Hiram-Wong/ZyPlayer#76]
3.2.8更新之后怎么没有一键配置选项了？本地导入和远程导入使用原来一键配置的json文件都不能成功啊

**Comment by woshiayi1** [comment]
格式换了，主页里面有格式介绍！！！

**Comment by arlingus** [comment]
3.2.8的配置文件问题太多了，从反馈来看好像还没有成功的，只能一条一条配置。强烈建议兼容老版本的一键配置JSON文件格式，https://www.mefcl.com/zy-player/810

**Comment by jahem** [comment]
[已有重复issues](https://github.com/Hiram-Wong/ZyPlayer/issues/74)https://github.com/Hiram-Wong/ZyPlayer/issues/74

**Comment by Hiram-Wong** [comment]
> 3.2.8的配置文件问题太多了，从反馈来看好像还没有成功的，只能一条一条配置。强烈建议兼容老版本的一键配置JSON文件格式，https://www.mefcl.com/zy-player/810

3.2.9 上会做改进，一键配置会加回来，一路既往收听用户心声

**Comment by arlingus** [comment]
大佬威武！祝产品越来越好！

**Comment by Hanoch-J** [comment]
> > 3.2.8的配置文件问题太多了，从反馈来看好像还没有成功的，只能一条一条配置。强烈建议兼容老版本的一键配置JSON文件格式，https://www.mefcl.com/zy-player/810
> 
> 3.2.9 上会做改进，一键配置会加回来，一路既往收听用户心声

那现在这个版本怎么用呀？

**Comment by Hiram-Wong** [comment]
> > > 3.2.8的配置文件问题太多了，从反馈来看好像还没有成功的，只能一条一条配置。强烈建议兼容老版本的一键配置JSON文件格式，https://www.mefcl.com/zy-player/810
> > 
> > 
> > 3.2.9 上会做改进，一键配置会加回来，一路既往收听用户心声
> 
> 那现在这个版本怎么用呀？

先用老版本，然后等待新版本

**Comment by Hiram-Wong** [comment]
最新版本已支持
