### ISSUE TITLE
3.2.8版本后，一键导入功能，有没有配置成功的？

### ISSUE THREAD

**Issue by WendouXie** [Hiram-Wong/ZyPlayer#77]
折腾了一天，对着接口范例修改，一直提示错误，没有折腾成功的？

**Comment by jahem** [comment]
[已有重复issues](https://github.com/Hiram-Wong/ZyPlayer/issues/74)https://github.com/Hiram-Wong/ZyPlayer/issues/74

**Comment by WendouXie** [comment]
<img width="617" alt="image" src="https://github.com/Hiram-Wong/ZyPlayer/assets/25963538/0610b6d4-d74b-44a8-aafd-9b63cb9edb74">
使用https://zy.catni.cn/config.json一直提示这个错误：请求一键配置地址失败：TypeError: Cannot read properties of undefined (reading 'protocol')；有什么解决办法吗？

**Comment by dasu88** [comment]
> <img alt="image" width="617" src="https://user-images.githubusercontent.com/25963538/265872254-0610b6d4-d74b-44a8-aafd-9b63cb9edb74.png"> 使用https://zy.catni.cn/config.json一直提示这个错误：请求一键配置地址失败：TypeError: Cannot read properties of undefined (reading 'protocol')；有什么解决办法吗？

应该是从基础配置处导入

**Comment by WendouXie** [comment]
<img width="501" alt="image" src="https://github.com/Hiram-Wong/ZyPlayer/assets/25963538/ee86022c-03d3-46fb-b404-df7d93862676">
搞定了，确实是从基础配置导入的，没注意这里。
