### ISSUE TITLE
视窗问题

### ISSUE THREAD

**Issue by dasu88** [Hiram-Wong/ZyPlayer#78]
目前的运行模式是，主视窗点击影片后，会另外开启播放器视窗，形成两个视窗，如果先行关掉主视窗再关闭播放器视窗，会出现再次呼叫出主视窗的状况，是否可以改为直觉一些，一次只开启一个作业视窗，避免误按关闭的情形。

**Comment by Hiram-Wong** [comment]
逻辑如此，爱 xx，腾 x，x 酷都是这么设计
