### ISSUE TITLE
自己找的视频网站怎么制作成视频源

### ISSUE THREAD

**Issue by NEO-LION** [Hiram-Wong/ZyPlayer#79]
我打开视频网站的源代码,没有找到像已经做好的视频源那样的节目列表.抓包工具也没有抓到想要的,能给我支个招吗

**Comment by Hiram-Wong** [comment]
看是不是 cms，不是cms 建议使用 drpy

**Comment by Hiram-Wong** [comment]
参考道长项目 https://zy.catni.cn/edit-source.html
