### ISSUE TITLE
本地导入zyplayer.json文件读取成功但是影视配置空空如也

### ISSUE THREAD

**Issue by wangvhero** [Hiram-Wong/ZyPlayer#83]
使用的源是https://agit.ai/guot54/ygbh/raw/branch/master/zy.json为什么文件导入不成功？

**Comment by tanghengvip** [comment]
一样。提示导入成功，但是影视配置里还是没有数据

**Comment by Hiram-Wong** [comment]
使用 3.2.9 版本，设置-数据管理-一键配置-软件接口

**Comment by jiaorong2023** [comment]
状态批量检测失败, 错误信息:TypeError: Cannot read properties of undefined (reading 'key')
