### ISSUE TITLE
帮忙把这个网站制作成视频源，最好直接按照json格式组装好。能有制作步骤最好了。

### ISSUE THREAD

**Issue by NEO-LION** [Hiram-Wong/ZyPlayer#84]
http://www.feijisu30.com/mov/
这个视频网站视频质量还是挺好的，速度也很快

**Comment by Hiram-Wong** [comment]
这个好像不是 cms 的，你可以尝试用 drpy

**Comment by soyuzom** [comment]
这个不是资源站，是采集后的视频网站，看他的内容都是采集其他资源站整合的，要站长后台开放API接口才行
