### ISSUE TITLE
第三方播放器

### ISSUE THREAD

**Issue by Aueadiss** [Hiram-Wong/ZyPlayer#85]
希望大佬可以出个自选第三方播放器的功能想使用自己的第三方播放器软件

**Comment by Hiram-Wong** [comment]
没那么简单，第三方播放器不一定支持传参，也不是到传参格式

**Comment by zmwv823** [comment]
内置的几个播放器放tv源，一个都没法播放，把链接添加到pot，秒播放。。。。

**Comment by Hiram-Wong** [comment]
> 内置的几个播放器放tv源，一个都没法播放，把链接添加到pot，秒播放。。。。

播放器兼容性问题，web播放器通病

**Comment by yxxyun** [comment]
调用mpv呢？

**Comment by Aueadiss** [comment]
是的想调用mpv或者mpvnet

**Comment by Hiram-Wong** [comment]
调用mpv，mpv 软件会闪退，你们遇到过吗

**Comment by Hiram-Wong** [comment]
3.3.3版本支持自定义第三方播放器
