### ISSUE TITLE
channel在哪？

### ISSUE THREAD

**Issue by ysztcn** [Hiram-Wong/ZyPlayer#86]
channel配置好的，软件里在哪？

**Comment by Hiram-Wong** [comment]
> channel配置好的，软件里在哪？

就是iptv

**Comment by ysztcn** [comment]
问题是配置文件里2个都有时，找不到channel里的配置tv

**Comment by Hiram-Wong** [comment]
> 问题是配置文件里2个都有时，找不到channel里的配置tv

没懂
