### ISSUE TITLE
几个小建议

### ISSUE THREAD

**Issue by soyuzom** [Hiram-Wong/ZyPlayer#87]
1. 首页【影视】增加顶部显示的标签 数量，最好能用户自定义，或者自动根据窗口大小增加，这样方便用户操作。
2. 同上问题，在【设置】【影视配置】里给“影视源”编辑里增加一个屏蔽过滤更能，和类别类似，只是添加了之后不再首页显示。
    大部分影视源标签“电影-电视剧” 之类第一分类标签是不存放影视的，这样首页显示很多余。
3. 搜索方面，增强搜索功能，搜索演员和内容。3.2. 如果把设置里的 搜索选项放到 搜索栏里更好，方便选择本站还是组内。
4. 播放器，有个别源 无法播放，可以增加个换源搜索，直接搜索别的同名视频源
5. 影片增加右键菜单，可以：收藏(追剧)，搜同名影片，稍后播放(需要安排播放列表功能)，简介(弹出简介内容)，……

**Comment by qallen028** [comment]
> 1. 首页【影视】增加顶部显示的标签 数量，最好能用户自定义，或者自动根据窗口大小增加，这样方便用户操作。
> 2. 同上问题，在【设置】【影视配置】里给“影视源”编辑里增加一个屏蔽过滤更能，和类别类似，只是添加了之后不再首页显示。
>    大部分影视源标签“电影-电视剧” 之类第一分类标签是不存放影视的，这样首页显示很多余。
> 3. 搜索方面，增强搜索功能，搜索演员和内容。3.2. 如果把设置里的 搜索选项放到 搜索栏里更好，方便选择本站还是组内。
> 4. 播放器，有个别源 无法播放，可以增加个换源搜索，直接搜索别的同名视频源
> 5. 影片增加右键菜单，可以：收藏(追剧)，搜同名影片，稍后播放(需要安排播放列表功能)，简介(弹出简介内容)，……

看大佬沒空，我來暫時回復一下
1.分類長度不是固定字數，如設定固定數量，恐會影響顯示樣式
2.對應問題，你可以配置自定義分類
3.搜索内容是根據接口返回處理，是接口不支持搜索演员和内容
4和5應該是可以實現的

**Comment by WFNDVS** [comment]
有没有办法可以不用梯子就可以看啊

**Comment by Hiram-Wong** [comment]
> 为什么需要挂梯子才能看啊，不然就显示网络错误啊
> 
> 

这明显是源限制地域无法访问，和软件无关

**Comment by Hiram-Wong** [comment]
1.最新版本会自动跟随宽度
2.源里面自己设置
3.站点不支持
45 开发成本大，不基于实现
