### ISSUE TITLE
出现原生标题栏

### ISSUE THREAD

**Issue by Aurora-Simba** [Hiram-Wong/ZyPlayer#88]
![图片](https://github.com/Hiram-Wong/ZyPlayer/assets/106955617/a22f55fd-d471-4384-a1b8-9aeae2ad35c9)

**Comment by Hiram-Wong** [comment]
删错了一个参数导致的，稍等下，我重新打个包

**Comment by Hiram-Wong** [comment]
> 删错了一个参数导致的，稍等下，我重新打个包

重新下载 3.2.10 版本即可
