### ISSUE TITLE
撞车 龙门视频

### ISSUE THREAD

**Issue by dh53128** [Hiram-Wong/ZyPlayer#90]
今日在 www.looo.top 发现win客户端和zyplayer 99%相似。不知道是不是抄你的

**Comment by Hiram-Wong** [comment]
> 今日在 www.looo.top 发现win客户端和zyplayer 99%相似。不知道是不是抄你的

不能说抄，因为我本身就是开源

**Comment by 8966216** [comment]
> > 今日在[www.looo.top](http://www.looo.top)发现win客户端和zyplayer 99%相似。不知道是不是抄袭你的
> 
> 不能说抄，因为我本身就是开源

有没有IOS下载
