### ISSUE TITLE
上传失败  怎么解决？不知道是我的添加方式是否有问题，我是在设置-源管理-导入，如果方法有误请指正

### ISSUE THREAD

**Issue by LSDGQ** [Hiram-Wong/ZyPlayer#95]
上传失败  怎么解决 且我懒的一个一个的添加  不知道是我的添加方式是否有问题，我是在设置-源管理-导入，如果方法有误请指正，还是我的源有问题  我用的是问题中大家提到过的源，希望得到大佬们的帮助QWQ
![G{UU28{D10D9AQV{VKXP4PS](https://github.com/Hiram-Wong/ZyPlayer/assets/106037312/78eda952-7e4a-4f3d-bb98-90dfc2fb672a)

**Comment by aa1555** [comment]
试试这个，选第二个配置导入，别用第一个一键配置
https://zy.hiram.top/config.json
![image](https://github.com/Hiram-Wong/ZyPlayer/assets/144973990/5a01e609-8b33-4365-bc30-4c03b7bc8254)

**Comment by Hiram-Wong** [comment]
> 上传失败  怎么解决 且我懒的一个一个的添加  不知道是我的添加方式是否有问题，我是在设置-源管理-导入，如果方法有误请指正，还是我的源有问题  我用的是问题中大家提到过的源，希望得到大佬们的帮助QWQ
> 
> ![G{UU28{D10D9AQV{VKXP4PS](https://github.com/Hiram-Wong/ZyPlayer/assets/106037312/78eda952-7e4a-4f3d-bb98-90dfc2fb672a)
> 
> 

老版本请在原作者github下题issue
