### ISSUE TITLE
为什么有些源站点在ZYPlayer中导入后不能显示内容，而在其他软件中是没有问题的，比如下面这些

### ISSUE THREAD

**Issue by arlingus** [Hiram-Wong/ZyPlayer#96]
为什么有些源站点在ZYPlayer中导入后不能显示内容，而在其他软件中是没有问题的，比如下面这些
http://www.caiji25.com/ ，按照采集站的说明，采集地址是https://www.caiji25.com/cjapi/sda/vod/json/m3u8.html  ，而这用zyplayer添加站点成功但是内容访问总是失败。还有http://cjmygzy.com/inc/sapi.php?ac=videolist ，在zyplayer中也是内容访问总是失败。

**Comment by Hiram-Wong** [comment]
https://www.caiji25.com/cjapi/sda/vod/json/m3u8.html 这个明显有问题数据都没有返回
http://cjmygzy.com/inc/sapi.php?ac=videolist这个你用 xml 导入应该是可以的

**Comment by arlingus** [comment]
http://cjmygzy.com/inc/sapi.php?ac=videolist这个我也试过了xml,json,js0 appv3 appv1各种格式添加数据源，就是不能显示。而且我也试过了用TVBOX软件APP是使用这个地址是没有问题的，所以比较奇怪，你也可以试试就是不行啊

**Comment by liky0904** [comment]
为什么总是显示网络请求失败，请尝试手动刷新

**Comment by Hiram-Wong** [comment]
> [http://cjmygzy.com/inc/sapi.php?ac=videolist这个我也试过了xml,json,js0](http://cjmygzy.com/inc/sapi.php?ac=videolist%E8%BF%99%E4%B8%AA%E6%88%91%E4%B9%9F%E8%AF%95%E8%BF%87%E4%BA%86xml,json,js0) appv3 appv1各种格式添加数据源，就是不能显示。而且我也试过了用TVBOX软件APP是使用这个地址是没有问题的，所以比较奇怪，你也可以试试就是不行啊

是哪里有问题

**Comment by liky0904** [comment]
我换了网络还是一样的

**Comment by Hiram-Wong** [comment]
> 我换了网络还是一样的

发下地址

**Comment by liky0904** [comment]
ip地址吗

**Comment by Hiram-Wong** [comment]
> ip地址吗

源地址

**Comment by liky0904** [comment]
就是你给的链接下载的

**Comment by liky0904** [comment]
大佬源地址要怎么看

**Comment by Hiram-Wong** [comment]
> 大佬源地址要怎么看

设置里面

**Comment by liky0904** [comment]
http://diyp.112114.xyz/是这个吗

**Comment by arlingus** [comment]
> > [http://cjmygzy.com/inc/sapi.php?ac=videolist这个我也试过了xml,json,js0](http://cjmygzy.com/inc/sapi.php?ac=videolist%E8%BF%99%E4%B8%AA%E6%88%91%E4%B9%9F%E8%AF%95%E8%BF%87%E4%BA%86xml,json,js0) appv3 appv1各种格式添加数据源，就是不能显示。而且我也试过了用TVBOX软件APP是使用这个地址是没有问题的，所以比较奇怪，你也可以试试就是不行啊
> 
> 是哪里有问题

之前的版本3.2.9导入的确实不行，现在的3.3.0版本已经可以了，不知道为什么，感谢大佬答复
