### ISSUE TITLE
配置文件可否放跟目录下？

### ISSUE THREAD

**Issue by woshiayi1** [Hiram-Wong/ZyPlayer#99]
配置文件能放在根目录下面吗？
现在的位置C:\Users\Administrator\AppData\Roaming\zyplayer
放在U盘里，可以去网吧用。
或者直接压缩在一起，发给我同事解压可以直接用。

**Comment by Hiram-Wong** [comment]
直接导出 json 文件即可，说有数据都可导出，会这保存到 webdev 也可以

**Comment by Hiram-Wong** [comment]
最新版本已支持
